library/src/main/java/com/finecinnamon/kats/Option.kt

Port of https://github.com/scala/scala/blob/v2.12.1/src/library/scala/Option.scala

Create Option type and base combinators

---

core/src/main/java/kats/Option.kt
core/src/main/java/kats/dummy.md

Issue #4 
Port of https://github.com/scala/scala/blob/v2.12.1/src/library/scala/Option.scala

Create Option type with base combinators

---

README.md

I have translated all the thoughts @raulraja exposed about how things could be done in terms of contributions and added it to the README, since I think it's pretty neat and is going to help everybody trying to contribute.

Update readme with How to contribute section

---

katz/src/main/kotlin/katz/NonEmptyList.kt

Taken from https://github.com/FineCinnamon/Bandhook-Kotlin/blob/rr-fp-refactor/core/src/main/java/com/github/finecinnamon/predef.kt

Initial NonEmptyList implementation

---

katz/src/main/kotlin/katz/NonEmptyList.kt
katz/src/main/kotlin/katz/Option.kt
katz/src/main/kotlin/katz/Try.kt

Our types should accept only types non-nullable.

Remove support for null in our types

---

.travis.yml
README.md
build.gradle
katz/build.gradle

Recommended extension: https://github.com/codecov/browser-extension

Added codecov step to travis.

---

README.md

Allow other use this library via [jipack.io](https://jitpack.io) until stabilize it and move it to jcenter or maven central

support versioning using jitpack.io

---

.travis.yml
README.md
build.gradle
katz/build.gradle
katz/src/main/kotlin/katz/data/Either.kt
katz/src/main/kotlin/katz/data/Ior.kt
katz/src/main/kotlin/katz/instances/EitherMonad.kt
katz/src/main/kotlin/katz/instances/IorMonad.kt
katz/src/main/kotlin/katz/typeclasses/HigherKinds.kt
katz/src/test/kotlin/katz/data/EitherTest.kt
katz/src/test/kotlin/katz/data/IorTest.kt

I'm not sure about the Ior implementation due to the shitty implicit semigroup I had to grokk for Ior. Also, I'm forced to use `*` for non-bias type over `Nothing` else flatMap couldn't be inlined due to the reified type C.
Other than some phantom UI errors by the Kotlin parser it seems to pass the test so...yeah. I'm happy to finally contribute to the project :D

Add HKTs for 2-5 types. Implement monad for Either and Ior

---

katz/src/main/kotlin/katz/typeclasses/Applicative.kt
katz/src/test/kotlin/katz/data/OptionTest.kt

Cartesian Builder for Applicative instances
Pain Driven Development :tm:

Cartesian Builder

---

.travis.yml
build.gradle
detekt.gradle
detekt.yml
katz/build.gradle
katz/src/main/kotlin/katz/data/Either.kt
katz/src/main/kotlin/katz/data/Id.kt
katz/src/main/kotlin/katz/data/Ior.kt
katz/src/main/kotlin/katz/data/Option.kt
katz/src/main/kotlin/katz/data/Try.kt
katz/src/main/kotlin/katz/instances/NonEmptyListMonad.kt
katz/src/main/kotlin/katz/typeclasses/ContinuationUtils.kt
katz/src/main/kotlin/katz/typeclasses/Monad.kt
katz/src/main/kotlin/katz/typeclasses/MonadError.kt
reports/baseline.xml

Add detekt

---

katz/src/main/kotlin/katz/arrow/FunctionK.kt
katz/src/main/kotlin/katz/data/Coproduct.kt
katz/src/main/kotlin/katz/data/Either.kt
katz/src/main/kotlin/katz/instances/CoproductComonad.kt
katz/src/main/kotlin/katz/typeclasses/Comonad.kt
katz/src/main/kotlin/katz/typeclasses/Inject.kt
katz/src/main/kotlin/katz/typeclasses/Monad.kt

@pakoito This is ready and can't really test the properties in this clases until we have something like `discipline`. I'm gonna attempt to implement `Free` after this one and there we can add some test examples over Free algebras that use Coproduct, Inject and others.

Progress toward Coproduct, FunctionK, and Inject, next Free :)

---

katz/src/main/kotlin/katz/data/OptionT.kt
katz/src/main/kotlin/katz/instances/EitherMonad.kt
katz/src/main/kotlin/katz/instances/IdMonad.kt
katz/src/main/kotlin/katz/instances/IorMonad.kt
katz/src/main/kotlin/katz/instances/OptionMonad.kt
katz/src/main/kotlin/katz/instances/OptionTMonad.kt
katz/src/main/kotlin/katz/typeclasses/HigherKinds.kt
katz/src/test/kotlin/katz/data/EitherTest.kt
katz/src/test/kotlin/katz/data/IorTest.kt
katz/src/test/kotlin/katz/data/OptionTTest.kt

Not all combinator are teststed

Add OptionT and OptionTMonad datatype

---

katz/src/main/kotlin/katz/data/Validated.kt
katz/src/main/kotlin/katz/instances/ValidatedApplicative.kt
katz/src/main/kotlin/katz/instances/ValidatedApplicativeError.kt
katz/src/test/kotlin/katz/data/ValidatedTest.kt
reports/baseline.xml

Create Validated type

---

katz/src/main/kotlin/katz/data/Try.kt
katz/src/main/kotlin/katz/instances/OptionMonad.kt
katz/src/main/kotlin/katz/instances/TryMonad.kt
katz/src/main/kotlin/katz/instances/TryMonadError.kt
katz/src/main/kotlin/katz/typeclasses/MonadError.kt
katz/src/test/kotlin/katz/data/TryTest.kt

Create Monad Instance for Try type

---

katz/src/main/kotlin/katz/data/EitherT.kt
katz/src/main/kotlin/katz/data/Eval.kt
katz/src/main/kotlin/katz/data/Ior.kt
katz/src/main/kotlin/katz/data/Kleisli.kt
katz/src/main/kotlin/katz/data/NonEmptyList.kt
katz/src/main/kotlin/katz/data/Option.kt
katz/src/main/kotlin/katz/data/OptionT.kt
katz/src/main/kotlin/katz/data/Validated.kt

Two changes done:
* Removed unnecessary reified from Option's companion object in order for the method to be called from Java.
* Also added @JvmStatic to some other companion object methods to generate easier to use methods.

Small issues with reified from Java

---

katz/src/main/kotlin/katz/data/Cokleisli.kt
katz/src/main/kotlin/katz/data/Coreader.kt
katz/src/main/kotlin/katz/data/Id.kt
katz/src/main/kotlin/katz/data/Kleisli.kt
katz/src/main/kotlin/katz/data/Reader.kt
katz/src/main/kotlin/katz/instances/IdComonad.kt
katz/src/main/kotlin/katz/typeclasses/Comonad.kt
katz/src/main/kotlin/katz/typeclasses/Typeclass.kt
katz/src/test/kotlin/katz/UnitSpec.kt
katz/src/test/kotlin/katz/data/CoreaderTest.kt
katz/src/test/kotlin/katz/data/KleisliTest.kt
katz/src/test/kotlin/katz/data/OptionMonoidTest.kt
katz/src/test/kotlin/katz/data/OptionTest.kt
katz/src/test/kotlin/katz/data/ReaderTest.kt
katz/src/test/kotlin/katz/data/ValidatedTest.kt

Add Cokleisli

---

katz/src/test/kotlin/katz/data/EvalTest.kt

Add tests for Eval

---

katz/src/main/kotlin/katz/effects/internal/AndThen.kt
katz/src/test/kotlin/katz/effects/internal/AndThenTest.kt
reports/baseline.xml

AndThen is an internal construct used by IO to compose effects without blowing up the stack.
I'm working on IO, Effect, and the rest. This is the first diff to get the Effects package rolling.

Add Effects package with class AndThen

---

README.md

Remove outdated info in the README

Remove outdated info from the README

---

.travis.yml

Extra memory:
https://docs.travis-ci.com/user/reference/precise/#Virtualization-environments
Early migration to new Ubuntu:
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

Update .travis.yml to sudo-enabled for extra memory

---

README.md

Just a stupid PR to show the fancy new kategory logo also on the README (since it's the main kategory org product) and the so coolio Λ on the title -> **KΛTEGORY**
Check the lookout [here](https://github.com/kategory/kategory/tree/add-kategory-logo-to-readme)

Add kategory logo and new title to readme

---

kategory/src/main/kotlin/kategory/data/StateT.kt
kategory/src/main/kotlin/kategory/instances/IterableInstances.kt
kategory/src/main/kotlin/kategory/instances/StateTInstances.kt
kategory/src/main/kotlin/kategory/typeclasses/MonadState.kt
kategory/src/test/kotlin/kategory/data/StateTTests.kt
kategory/src/test/kotlin/kategory/laws/MonadStateLaws.kt

#fixes #145
* Added MonadState
* Added MonadStateLaws
* Test laws

MonadState

---

kategory/src/main/kotlin/kategory/data/Either.kt
kategory/src/main/kotlin/kategory/data/Option.kt

#perf 
May also be useful once https://youtrack.jetbrains.com/issue/KT-19288 lands

Add crossinline to fold for Either and Option

---

kategory/src/main/kotlin/kategory/typeclasses/Functor.kt
kategory/src/test/kotlin/kategory/data/OptionTest.kt

Hey, I've implemented some of the methods, how should I test them? 
I have some questions regarding the others unimplemented methods:
[this](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/Functor.scala#L17) is the same as the map function, right? 🤔 
[this](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/Functor.scala#L32) Can I do something like B >: A in kotlin?
[this](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/Functor.scala#L65-L75) what is this? Should I implement this too?
Thanks :D

[WIP] Add missing methods in Functor enhancement

---

kategory-effects/src/main/kotlin/kategory/effects/typeclass/Async.kt
kategory-effects/src/test/kotlin/kategory/effects/laws/AsyncLaws.kt
kategory/src/main/kotlin/kategory/typeclasses/Monad.kt
kategory/src/main/kotlin/kategory/typeclasses/MonadError.kt
reports/baseline.xml

Add a new bindingAsync method for Async that allows to call bindAsync without passing an AsyncContext.
Add a bunch of extension functions for it.
Add laws for all error cases.

Async Enhancements

---

build.gradle
detekt.gradle
kategory-effects/build.gradle
kategory-test/build.gradle
kategory/build.gradle

After running https://github.com/ben-manes/gradle-versions-plugin#dependencyupdates I've updated all dependencies in our project. I've also made the kotlin-annotations version into an external variable.

Update all dependencies

---

kategory-effects/src/test/kotlin/kategory/effects/data/IOTest.kt
kategory-effects/src/test/kotlin/kategory/effects/laws/AsyncLaws.kt
kategory/src/main/kotlin/kategory/typeclasses/Comonad.kt
kategory/src/main/kotlin/kategory/typeclasses/Monad.kt
kategory/src/test/kotlin/kategory/data/CoproductTest.kt
kategory/src/test/kotlin/kategory/data/EitherTTest.kt
kategory/src/test/kotlin/kategory/data/EitherTest.kt
kategory/src/test/kotlin/kategory/data/Function0Test.kt
kategory/src/test/kotlin/kategory/data/Function1Test.kt
kategory/src/test/kotlin/kategory/data/IdTest.kt
kategory/src/test/kotlin/kategory/data/IorTest.kt
kategory/src/test/kotlin/kategory/data/NonEmptyListTest.kt
kategory/src/test/kotlin/kategory/data/OptionTTest.kt
kategory/src/test/kotlin/kategory/data/OptionTest.kt
kategory/src/test/kotlin/kategory/data/TryTest.kt
kategory/src/test/kotlin/kategory/data/WriterTTest.kt
kategory/src/test/kotlin/kategory/free/CofreeTest.kt
kategory/src/test/kotlin/kategory/free/FreeTest.kt

As it says in #194 the "!" mark it's already removed.

Remove instances of ! from tests

---

build.gradle

Downgrade Kotlin version to 1.1.4 as it prevents us from loading Kategory in dependent modules.

Downgrade Kotlin version to 1.1.4

---

kategory/src/main/kotlin/kategory/data/NonEmptyList.kt
kategory/src/main/kotlin/kategory/instances/NonEmptyListInstances.kt
kategory/src/test/kotlin/kategory/data/NonEmptyListTest.kt

Fixes  #202
Added `Foldable` and `Traverse` for NonEmptyList.
Added tests for `TraverseLaws`.

Added traverse and foldable instance for NonEmptyList

---

kategory/src/main/kotlin/kategory/data/OptionT.kt
kategory/src/test/kotlin/kategory/data/OptionTTest.kt

It was a fixme since the class was written

Add functions to convert OptionT to EitherT

---

kategory-effects-rx2/src/main/kotlin/kategory/effects/data/FlowableKW.kt
kategory-effects-rx2/src/main/kotlin/kategory/effects/data/ObservableKW.kt
kategory-effects-rx2/src/main/kotlin/kategory/effects/instances/FlowableKWInstances.kt
kategory-effects-rx2/src/main/kotlin/kategory/effects/instances/ObservableKWInstances.kt
kategory-effects-rx2/src/test/kotlin/kategory/effects/data/FlowableKWTests.kt

Add Rx2 Flowable wrapper

---

kategory-optics/src/main/kotlin/kategory/optics/Getter.kt
kategory-optics/src/main/kotlin/kategory/optics/Iso.kt
kategory-optics/src/main/kotlin/kategory/optics/Lens.kt
kategory-optics/src/test/kotlin/kategory/optics/GetterTest.kt

I had Getter ready and it is not polymorphic so it will not interfere with the open PR for polymorphic optics.

Add getter optic

---

deploy-scripts/deploy.sh

This time it should execute the right script

Automated deployment - Part trois

---

deploy-scripts/deploy.sh
deploy-scripts/deploy_common.sh
deploy-scripts/deploy_release.sh
deploy-scripts/deploy_snapshot.sh

automated deployment - One more time

---

kategory-docs/docs/docs/patterns/errorhandling/README.md

`Functional Error Handling` docs

---

kategory-docs/docs/docs/patterns/errorhandling/README.md

Fixed Either sample

---

README.md
ank-core/gradle.properties
gradle.properties

* Fixed a problem on Typeclass instance retrieval system causing Android apps to crash. (It was using a method just present on JDK 8).

Release 0.3.10

---

README.md
build.gradle
kategory-effects-rx2/build.gradle

* Upgrading Kotlin to the last stable release: `1.1.51`.

Upgrade kotlin to last stable release

---

kategory-core/src/test/kotlin/kategory/data/MapKWTest.kt
kategory-core/src/test/kotlin/kategory/free/FreeApplicativeTest.kt
kategory-core/src/test/kotlin/kategory/free/FreeTest.kt
kategory-docs/docs/docs/typeclasses/applicative/README.md
kategory-docs/docs/docs/typeclasses/eq/README.md
kategory-docs/docs/docs/typeclasses/functor/README.md
kategory-test/src/main/kotlin/kategory/laws/EqLaws.kt
kategory-test/src/main/kotlin/kategory/laws/MonadFilterLaws.kt

Closes #348 
This PR adds documentation for the Eq typeclass. I noticed that we had no laws for Eq, so I added one and applied it to the instances we already have.

Docs and laws for Eq

---

kategory-docs/docs/docs/datatypes/option/README.md

Update option docs

---

kategory-docs/docs/docs/optics/prism/README.md
kategory-optics/src/main/kotlin/kategory/optics/Prism.kt
kategory-optics/src/test/kotlin/kategory/optics/PrismTest.kt

Prism docs

---

build.gradle
deploy-scripts/deploy_release.sh

Brings back the release bintray plugin and adds it to the release script

Release deploy re-enabled

---

kategory-core/src/main/kotlin/kategory/data/Ior.kt
kategory-core/src/main/kotlin/kategory/data/NonEmptyList.kt
kategory-core/src/test/kotlin/kategory/data/IorTest.kt
kategory-docs/docs/docs/datatypes/ior/README.md

* Fixed an issue when combining Both and Right returning Right instead of Both.
* Added Ior docs (fixes #313)
* Added Nel typealias and show function for NonEmptyList.
* Added IorNel typealias for Ior.
* Fix some Ior docs
* Added leftNel and bothNel
* Added toValidated function
* Removed unnecessary types parameters for rightIor and leftIor

Added Ior docs

---

kategory-effects-rx2/src/main/kotlin/kategory/effects/data/FlowableKW.kt
kategory-effects-rx2/src/main/kotlin/kategory/effects/data/ObservableKW.kt
kategory-effects-rx2/src/test/kotlin/kategory/effects/data/FlowableKWTests.kt
kategory-effects-rx2/src/test/kotlin/kategory/effects/data/ObservableKWTests.kt

Rx2 traverse and foldable instances

---

kategory-docs/docs/docs/typeclasses/applicative/README.md
kategory-docs/docs/docs/typeclasses/eq/README.md

Some quick fixes to the documentation

Fix links in documentation

---

kategory-core/src/main/kotlin/kategory/data/Eval.kt
kategory-core/src/test/kotlin/kategory/data/EvalTest.kt

Add eval comonad and bimonad instances

---

kategory-docs/docs/docs/optics/iso/README.md
kategory-docs/docs/docs/optics/optional/README.md
kategory-docs/docs/docs/optics/prism/README.md
kategory-docs/docs/docs/optics/setter/README.md
kategory-optics/src/main/kotlin/kategory/optics/Setter.kt
kategory-optics/src/test/kotlin/kategory/optics/SetterTest.kt

Setter docs

---

kategory-docs/docs/docs/patterns/monadcomprehensions/README.md

Took a bit to get out, I think it turned out okay.

Add documentation for Monadic Comprehensions

---

kategory-docs/docs/docs/optics/traversal/README.md
kategory-optics/src/main/kotlin/kategory/optics/Traversal.kt
kategory-optics/src/main/kotlin/kategory/optics/instances/TupleInstances.kt
kategory-optics/src/test/kotlin/kategory/optics/TraversalTest.kt
kategory-optics/src/test/kotlin/kategory/optics/data/TupleInstancesTest.kt
kategory-test/src/main/kotlin/kategory/generators/Generators.kt

Traversal docs

---

kategory-docs/docs/docs/effects/async/README.md

Add lightweight docs for AsyncContext
Closing https://github.com/kategory/kategory/issues/350

Add docs to AsyncContext

---

kategory-docs/docs/docs/datatypes/either/README.md
kategory-docs/docs/docs/effects/io/README.md
kategory-effects/src/test/kotlin/kategory/effects/data/IOTest.kt

Adds docs for IO, instances for Either, and a couple of new tests.

Add docs for IO

---

kategory-docs/docs/docs/effects/io/README.md
kategory-docs/docs/docs/integrations/rx2/README.md
kategory-docs/docs/docs/patterns/monadcomprehensions/README.md

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/tDWu96gBffU/0.jpg)](https://www.youtube.com/watch?v=tDWu96gBffU)

Add docs for RxJava2 integration

---

kategory-core/src/main/kotlin/kategory/typeclasses/Monoid.kt
kategory-core/src/main/kotlin/kategory/typeclasses/Semigroup.kt
kategory-core/src/test/kotlin/kategory/typeclass/MonoidTest.kt
kategory-docs/docs/docs/typeclasses/monoid/README.md
kategory-docs/docs/docs/typeclasses/semigroup/README.md
kategory-test/src/main/kotlin/kategory/laws/TraversalLaws.kt

Moved `combineAll` to `Monoid` typeclass

Semigroup cannot combineAll

---

deploy-scripts/deploy.sh

Instead of relying on the tag from github, let's try to determine where to deploy from the actual version from the gradle properties

Update deploy script

---

kategory-annotations-processor/src/main/java/kategory/derive/DerivingFileGenerator.kt
kategory-annotations-processor/src/main/java/kategory/higherkinds/HigherKindsFileGenerator.kt
kategory-annotations-processor/src/main/java/kategory/implicits/ImplicitsFileGenerator.kt
kategory-annotations-processor/src/main/java/kategory/instances/InstanceFileGenerator.kt
kategory-core/src/main/kotlin/kategory/data/Const.kt
kategory-effects/src/test/kotlin/kategory/effects/data/internal/AndThenTest.kt
kategory-optics/src/test/kotlin/kategory/optics/OptionalTest.kt

Hopefully addresses a few warnings in #219 
If you've got any other tips for me to cleanup others, let me know. There are a bunch of 'inline performance warnings', but I'm not experienced enough with Kotlin or Kategory to know if these are fixable.

Various compiler warnings.

---

kategory-docs/docs/docs/patterns/monadcomprehensions/README.md

nothing crazy here, just a 404 fix

Fix applicative builder link

---

.travis.yml
build.gradle
deploy-scripts/deploy_docs.sh
kategory-docs/build.gradle

- Automate publish docs to `gh-pages` as part of the CI process
👀 @pakoito @raulraja

Automate publish docs

---

deploy-scripts/deploy.sh

Updating scripts to see what's going on. (update coming after this runs)

Updating deploy scripts

---

kategory-annotations-processor/src/main/java/kategory/derive/DerivingFileGenerator.kt
kategory-annotations-processor/src/main/java/kategory/instances/InstanceFileGenerator.kt
kategory-annotations/src/main/java/kategory/Typeclass.kt
kategory-core/src/main/kotlin/kategory/data/EitherT.kt
kategory-core/src/main/kotlin/kategory/data/Eval.kt
kategory-core/src/main/kotlin/kategory/data/Ior.kt
kategory-core/src/main/kotlin/kategory/data/NonEmptyList.kt
kategory-core/src/main/kotlin/kategory/data/Option.kt
kategory-core/src/main/kotlin/kategory/data/OptionT.kt
kategory-core/src/main/kotlin/kategory/data/Validated.kt
kategory-core/src/main/kotlin/kategory/instances/CoproductInstances.kt
kategory-core/src/main/kotlin/kategory/instances/EitherTInstances.kt
kategory-core/src/main/kotlin/kategory/instances/NumberInstances.kt
kategory-core/src/main/kotlin/kategory/instances/NumberInstancesJava.kt
kategory-core/src/main/kotlin/kategory/instances/StringInstances.kt
kategory-core/src/main/kotlin/kategory/instances/StringInstancesJava.kt
kategory-core/src/main/kotlin/kategory/instances/UnitInstances.kt
kategory-core/src/test/kotlin/kategory/data/SortedMapKWTest.kt
kategory-effects/src/main/kotlin/kategory/effects/data/Duration.kt

Removed all @JvmStatic occurences.

---

README.md
gradle.properties

Release 0.3.12

---

arrow-docs/docs/docs/quickstart/blogs/README.md

videos not shown, see https://github.com/kategory/arrow/issues/537

Probable fix for issue #537

---

README.md
arrow-docs/docs/docs/README.md

currently, the travis ci badge is gray. let's make it shiny green again :-)

fix travis-ci badge

---

arrow-annotations/src/main/java/arrow/TypeclassResolution.kt
arrow-annotations/src/main/java/arrow/typeclass.kt
arrow-docs/build.gradle

Also adds `@typeclass` and `interface Typeclass` under the same file

Rename Typeclass.kt to TypeclassResolution.kt and doc publish fixes

---

gradle.properties

This is intended to be the first Arrow beta release, covering all the new module segregation thanks to @raulraja. After a conversation with @MarioArias on the official #arrow channel on the **Kotlinlang** Slack, we have agreed on keeping beta versioning at least during a while, even though Funktionale was already under 1.x.x versions. The main rationale behind this is that we are still not in a place to declare an official release. May be it'll be ready for the official announcement? We will see. In the meantime we can keep iterating fast over it.

First Arrow beta release

---

README.md
arrow-docs/docs/docs/README.md

fix github link in nav and adjust readme

some more renaming fixes

---

arrow-docs/docs/_data/commons.yml

Functional companion to Kotlin's Standard Library

Add new tagline 

---

arrow-annotations/build.gradle

This update fixes a compiler warning about binary compatibility

Update KindedJ to 1.1.0

---

arrow-annotations-processor/build.gradle
build.gradle

Update dependencies of the annotation processor

---

arrow-docs/docs/_includes/_doc-wrapper.html

[Docs] Fix Edit for urls with underscores

---

arrow-core/src/main/kotlin/arrow/core/Eval.kt
arrow-data/src/test/kotlin/arrow/data/EvalTest.kt

Fix Eval stack safety

---

arrow-optics/build.gradle
arrow-optics/src/main/kotlin/arrow/optics/Optional.kt
arrow-optics/src/test/kotlin/arrow/optics/StackOverflowTest.kt

Fix combining Optional with Traversable

---

arrow-core/src/main/kotlin/arrow/core/Either.kt
arrow-data/src/test/kotlin/arrow/data/EitherTest.kt
arrow-docs/docs/docs/datatypes/either/README.md

Add Either.getOrElseGet that allows clients to resolve to Right using the value of Left.

Add Either.getOrHandle

---

ank-core/build.gradle
ank-gradle-plugin/build.gradle
gradle.properties

- Releases `0.6.1`
👀 @raulraja

Release 0.6.1

---

README.md
arrow-docs/docs/docs/README.md
gradle.properties

- Bumps to `0.6.2-SNAPSHOT`
- Updates docs in `README` and quick start pointing to `0.6.1`
👀 @raulraja @pakoito

Next iteration 0.6.2-SNAPSHOT

---

arrow-docs/docs/docs/datatypes/setkw/README.md

Doc for SetKW

---

arrow-core/src/main/kotlin/arrow/core/PartialFunction.kt
arrow-data/src/test/kotlin/arrow/data/PartialFunctionTests.kt

`toPartialFunction` is broken (i.e, it nevers throws `IEA`)

Fix implementation of `toPartialFunction`

---

arrow-annotations-processor/src/main/java/arrow/tc/TypeclassFileGenerator.kt

Enables `fa.map { ... }` as opposed to `fa.map({ ... })`

Improvements to type class lambda syntax to not require ()

---

.travis.yml
modules/docs/arrow-docs/docs/docs/datatypes/either/README.md

either video

---

modules/core/arrow-annotations/src/main/java/arrow/TypeclassResolution.kt

Handle the case where there are multiple parameter types and multiple raw types such as `Either<String, Int>`. tbh, I don't fully understand the logic and don't know all use cases. But for my `Either` case, there are 4 `parameterTypes`: `EQ`, `HS`, `EQ`, `HS`; and 2 raw types: `String`, `Int`.
I group the `parameterTypes` by the raw type:
`String`: `EQL`  `HSL`
`Int`: `EQR`, `EQR`
not sure if this works for all cases but based on all existing tests, nothing breaks.

Update instance resolution

---

modules/docs/arrow-docs/docs/docs/datatypes/nonemptylist/README.md
modules/docs/arrow-docs/docs/docs/effects/io/README.md

Fix #705 
This PR we should merge tomorrow about 8 am.

NonEmptyList video

---

modules/docs/arrow-docs/build.gradle

- Removes unnecessary `exclude` dependency after fixing ΛNK
👀 @raulraja @pakoito

Remove unnecessary exclude dependency after fixing ΛNK

---

modules/docs/arrow-docs/docs/docs/typeclasses/intro/README.md

@raulraja  could you review this PR please?
Fix #726

Typeclasses video

---

modules/docs/arrow-docs/docs/docs/datatypes/listk/README.md

ListK video

---

modules/docs/arrow-docs/docs/docs/datatypes/kleisli/README.md

This adding Kleisli documentation with an explanation for their functions
Fixes #315

Add Kleisli documentation

---

modules/docs/arrow-docs/docs/docs/datatypes/eval/README.md

@calvellido @raulraja could you review this PR please?

Eval video

---

modules/docs/arrow-docs/docs/docs/datatypes/optiont/README.md

@raulraja could you review this PR please?

(WIP) OptionT video

---

modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md

Add Uberto's talk to the docs

---

modules/core/arrow-core/src/main/kotlin/arrow/core/FunctionK.kt
modules/core/arrow-data/src/main/kotlin/arrow/data/Coproduct.kt
modules/core/arrow-data/src/test/kotlin/arrow/free/CofreeTest.kt
modules/core/arrow-data/src/test/kotlin/arrow/free/FreeApplicativeTest.kt
modules/core/arrow-data/src/test/kotlin/arrow/free/FreeTest.kt
modules/core/arrow-data/src/test/kotlin/arrow/free/Interpreters.kt
modules/core/arrow-free/src/main/kotlin/arrow/free/Cofree.kt
modules/core/arrow-free/src/main/kotlin/arrow/free/Free.kt
modules/core/arrow-free/src/main/kotlin/arrow/free/FreeApplicative.kt
modules/core/arrow-free/src/main/kotlin/arrow/free/Trampoline.kt
modules/core/arrow-free/src/main/kotlin/arrow/free/instances/free.kt
modules/core/arrow-free/src/main/kotlin/arrow/free/instances/freeaplicative.kt
modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Inject.kt

Rolling manual FreeEq instances instead.

Turns out FunctionK is not a typeclass

---

modules/docs/arrow-docs/docs/docs/datatypes/setk/README.md

Setk video

---

modules/core/arrow-instances-core/gradle.properties
modules/core/arrow-instances-data/gradle.properties

- Fixes arrow instances artifact ids adding core and data suffixes (`arrow-instances-core` and `arrow-instances-data` respectively)
👀 @pakoito

Fix arrow instances artifact ids 

---

.travis.yml
build.gradle
modules/docs/arrow-docs/build.gradle

- Bumps ank dependency which now includes latest 0.7 syntax changes 
- Unblocks docs generation
👀 @pakoito @raulraja @benjymontoya

Bump ank dependency which now includes latest 0.7 syntax changes

---

modules/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/composition.kt
modules/core/arrow-syntax/src/test/kotlin/arrow/syntax/test/function.kt

Aditional forward compose methods

---

modules/docs/arrow-docs/docs/_data/menu.yml
modules/docs/arrow-docs/docs/docs/datatypes/intro/README.md
modules/docs/arrow-docs/docs/docs/datatypes/listk/README.md
modules/docs/arrow-docs/docs/docs/datatypes/mapk/README.md
modules/docs/arrow-docs/docs/docs/datatypes/sequencek/README.md
modules/docs/arrow-docs/docs/docs/datatypes/setk/README.md
modules/docs/arrow-docs/docs/docs/datatypes/sortedmapk/README.md
modules/docs/arrow-docs/docs/docs/effects/io/README.md
modules/docs/arrow-docs/docs/docs/optics/at/README.md
modules/docs/arrow-docs/docs/docs/optics/filterindex/README.MD
modules/docs/arrow-docs/docs/docs/optics/index/README.MD
modules/docs/arrow-docs/docs/docs/patterns/glossary/README.md
modules/docs/arrow-docs/docs/docs/typeclasses/eq/README.md

* Fix all references to these links.
* Fix other bad link references along the lines.

Homogenize all permalinks following an all lowercase pattern

---

modules/docs/arrow-docs/docs/docs/README.md
modules/docs/arrow-docs/docs/docs/datatypes/either/README.md
modules/docs/arrow-docs/docs/docs/patterns/glossary/README.md

Mostly minor grammar bits and bobs and a couple of areas were the docs were vague: e.g. add it in your root `build.gradle` at the end of repositories.

Minor documentation amendments

---

modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md

Add some dates and versions to the articles that didn't have them

Add Introduction to Kotlin Arrow by Jacob Bass

---

modules/docs/arrow-docs/docs/docs/datatypes/kleisli/README.md

@arrow-kt/maintainers  could you review this PR please? Thanks ;)

Kleisli video

---

modules/docs/arrow-docs/docs/docs/datatypes/state/README.md

@calvellido could you review this PR please? Not merge
Fix #828

State video

---

build.gradle
modules/docs/arrow-docs/build.gradle

- Bumps Λnk dependencies to `0.7.1`

Bump Λnk dependencies to 0.7.1

---

modules/docs/arrow-docs/docs/docs/optics/dsl/README.md

Fix wrong superclass

---

modules/docs/arrow-docs/docs/docs/typeclasses/functor/README.md

Functor video

---

modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md

Adding the link to a Medium blog post explaining how to build an Android app using Arrow.

arrow 101 article

---

modules/docs/arrow-docs/docs/docs/legal/licenses/README.md

Update the license on the docs to match the one at the root

---

modules/docs/arrow-docs/docs/docs/datatypes/intro/README.md

Add recursion schemes info to data types intro.

Add recursion schemes info to data types intro

---

modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md

Fixes the code review changes requested in https://github.com/arrow-kt/arrow/pull/924

Add Jacob's Yow talk

---

.travis.yml

Fix codecov coverage upload

---

modules/docs/arrow-docs/docs/docs/datatypes/statet/README.md

StateT video

---

modules/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/pipe.kt

PipeLazy comes requested on the ASG chat by @Laimiux

Add pipeLazy

---

infographic/arrow-infographic.txt
modules/core/arrow-core/src/main/kotlin/arrow/core/Either.kt
modules/core/arrow-data/src/test/kotlin/arrow/data/EitherTest.kt
modules/docs/arrow-docs/docs/docs/datatypes/either/README.md

Practical operation when working with null. With this we can omit fold/mapLeft when starting with something that can be null.

Add rightIfNotNull to Either.

---

modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md

Video from [Milan Kotlin Community Conf](https://milan.kotlincommunityconf.com/)

Add Android Functional Validation With Arrow talk

---

modules/docs/arrow-docs/docs/docs/typeclasses/profunctor/README.md

Some fixes for `Profunctor` docs

Improving snippets and fixes

---

modules/docs/arrow-docs/docs/docs/effects/monaddefer/README.md

Remove the docs on Cancellation via coroutines too, as it's going away soon.

Specify that MonadDefer focuses on synchronous effects

---

modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md

updating blogs and presentation docs

---

modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Monad.kt
modules/docs/arrow-docs/docs/docs/typeclasses/monad/README.md

Simple helper and simple use case

Add effectM to Monad, to ignore the result of a second monadic operation

---

modules/docs/arrow-docs/docs/docs/typeclasses/applicative/README.md
modules/docs/arrow-docs/docs/docs/typeclasses/monad/README.md

Fix links to impl and laws

---

modules/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/partials.kt

Added simple caching logic for the partial object.

[partials] avoid initializing partial object multiple times

---

modules/docs/arrow-docs/docs/docs/quickstart/projects/README.md

Add two new projects to the list 😃

Update projects section for Android and Backend

---

modules/docs/arrow-docs/docs/docs/effects/async/README.md
modules/effects/arrow-effects/src/main/kotlin/arrow/effects/typeclasses/Async.kt

It also fixes the eager async `invoke`.

Add async `defer` in `Async`

---

modules/core/arrow-data/src/main/kotlin/arrow/data/ListK.kt

I was reading the code of ListK and notice that it has some unnecessary fix() calls. This PR removes then.

removing unnecessary `fix()`call

---

modules/docs/arrow-docs/docs/_data/menu.yml
modules/docs/arrow-docs/docs/docs/integrations/retrofit/README.md
modules/docs/arrow-docs/docs/docs/integrations/rx2/README.md

This PR adds documentation for the Retrofit integration

Adding integration for retrofit integration

---

modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md

@raulraja proposed to add it to [tutorials and blogs section](https://twitter.com/raulraja/status/1054060019212345346).
Is this the right page?

Add Polyjokes example

---

modules/docs/arrow-docs/docs/docs/integrations/retrofit/README.md

There were some errors in my last PR. Fixing then now.

fixing some minor problems

---

modules/docs/arrow-docs/docs/docs/integrations/retrofit/README.md
modules/integrations/arrow-integrations-retrofit-adapter/src/main/kotlin/arrow/integrations/retrofit/adapter/CallKindAdapterFactory.kt
modules/integrations/arrow-integrations-retrofit-adapter/src/test/kotlin/arrow/integrations/retrofit/adapter/CallKindAdapterFactoryTest.kt
modules/integrations/arrow-integrations-retrofit-adapter/src/test/kotlin/arrow/integrations/retrofit/adapter/retrofit/Retrofit.kt

Some tweaks to the docs, and the name of the factory.

Make some style changes to the Retrofit integration

---

README.md
gradle.properties
modules/docs/arrow-docs/docs/docs/README.md

[Release notes will be included once this is in master]

RELEASE 0.8.1

---

modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md

We can also link directly to the code - it's available on Github.

Add a blog post for Functional Hangman

---

.travis.yml

* Add S3 config parameters to deploy step

Add S3 config parameters to deploy step

---

.travis.yml

* Build jekyll site on Travis before_deploy step

Build jekyll site on Travis before_deploy step 

---

.travis.yml

Store docs pages in s3 bucket using two travis jobs

Store docs pages in s3 bucket

---

.travis.yml

* Fix Travis deploy-docs new job

Fix Travis deploy-docs new job

---

.travis.yml
modules/core/arrow-data/src/main/kotlin/arrow/data/Kleisli.kt

* Increase Java VM heap size
* Merge from master

Increase Java VM heap size

---

modules/core/arrow-annotations/src/main/java/arrow/hks.kt

This doc should help people identify how to go back from Kind to their expected type

Add docs to Kind

---

modules/docs/arrow-docs/docs/docs/effects/io/README.md

Remove docs reference to old IO constructor

---

modules/docs/arrow-docs/docs/docs/patterns/dependencyinjection/README.md
modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md

This PR adds https://www.youtube.com/watch?v=CR5h2Wq1yPE to the docs, alongside a small blurb on where to find the example.

Add video of Typeclassless to patterns/DI

---

modules/docs/arrow-docs/docs/docs/arrow/data/nonemptylist/README.md

* Fix bug on NonEmptyList docs config leading to infinite redirect.
This fixes #1212

Fix bug on NonEmptyList docs config leading to infinite redirect

---

README.md
gradle.properties
modules/docs/arrow-docs/docs/docs/README.md

Release 0.8.2

---

modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/Effect.kt

Effect: remove incorrect method

---

modules/meta/arrow-meta/models/src/main/java/arrow/ap/objects/iso/IsoSecondaryConstructor.kt
modules/meta/arrow-meta/models/src/main/java/arrow/ap/objects/lens/LensSecondaryConstructor.kt
modules/meta/arrow-meta/models/src/main/java/arrow/ap/objects/optional/OptionalSecondaryConstructor.kt
modules/meta/arrow-meta/src/main/java/arrow/common/utils/ProcessorUtils.kt
modules/meta/arrow-meta/src/test/java/arrow/ap/tests/IsoTest.kt
modules/meta/arrow-meta/src/test/java/arrow/ap/tests/LensTest.kt
modules/meta/arrow-meta/src/test/java/arrow/ap/tests/OptionalTest.kt
modules/meta/arrow-meta/src/test/resources/arrow/ap/objects/iso/IsoSecondaryConstructor.kt
modules/meta/arrow-meta/src/test/resources/arrow/ap/objects/lens/LensSecondaryConstructor.kt
modules/meta/arrow-meta/src/test/resources/arrow/ap/objects/optional/OptionalSecondaryConstructor.kt

Fix lenses generation for data classes with secondary constructors

---

modules/docs/arrow-docs/docs/_data/menu.yml
modules/docs/arrow-docs/docs/_sass/components/_blog.scss
modules/docs/arrow-docs/docs/_sass/components/_sidebar.scss
modules/docs/arrow-docs/docs/_sass/components/_wrapper.scss
modules/docs/arrow-docs/docs/blog/index.md
modules/docs/arrow-docs/docs/blog/media.md
modules/docs/arrow-docs/docs/blog/news.md

* Flip blog cards opacity interaction to show image clearer on hover.
* Align sidebar menu icon position to the text content margin.
* Update permalinks to make links properly work on totally static envs.

Minor styling fixes

---

modules/docs/arrow-docs/docs/_posts/2018-10-05-kotlin-conf-fp-in-kotlin-with-arrow.md

https://www.youtube.com/watch?v=VOZZTSuDMFE

Adds Kotlin Conf Talk to Media entries.

---

README.md

Adds statement about inclusion and links to Arrow's social.

updates join us in readme

---

modules/docs/arrow-docs/docs/docs/arrow/core/id/README.md
modules/docs/arrow-docs/docs/docs/arrow/core/id/ru/README.md

Added doc to Id monad in Russian (+ added link to translation in English version of doc). Describing abscence of effect was harder than describing effect of any complexity.
Checked for broken links, on local server all the links were clickable and worked correctly.

Ad Id doc in Russian

---

modules/docs/arrow-docs/docs/docs/aql/custom/README.md
modules/docs/arrow-docs/docs/docs/aql/from/README.md
modules/docs/arrow-docs/docs/docs/aql/intro/README.md
modules/docs/arrow-docs/docs/docs/aql/select/README.md
modules/docs/arrow-docs/docs/docs/aql/where/README.md
modules/docs/arrow-docs/docs/docs/arrow/effects/typeclasses/bracket/README.md
modules/docs/arrow-docs/docs/docs/arrow/typeclasses/hash/README.md
modules/docs/arrow-docs/docs/docs/effects/promise/README.MD
modules/docs/arrow-docs/docs/docs/integrations/reactor/README.md
modules/docs/arrow-docs/docs/docs/integrations/rx2/README.md

Made replacements in docs. @raulraja  please review this, It's ready to merge.

Replace {: data-executable='true'} to ank:playground #1236

---

modules/docs/arrow-docs/docs/_data/sidebar.yml

Totally did not forget that in #1311. My bad :/
Added them after alternative as they are somewhat related I think :)

Add new typeclasses to sidebar

---

README.md
modules/docs/arrow-docs/docs/docs/README.md
modules/meta/arrow-meta/gradle.properties
modules/meta/arrow-meta/models/gradle.properties

small fix to docs and Gradle config for broken artifact references

artifact reference fixes

---

gradle.properties

- Release notes to be added once released and tagged.

Release 0.9.0

---

README.md
modules/docs/arrow-docs/docs/docs/README.md

Let's keep the current structure for one more version.

Update READMEs after 0.9.0

---

modules/docs/arrow-docs/docs/docs/effects/fx/async/README.md

It's a shameful contribution but things need to be perfect 😂

Fix typo on fibers documentation

---

bitrise.yml

* Update Bitrise stack dependency to fix deploys

Update Bitrise stack dependency to fix deploys

---

modules/docs/arrow-docs/docs/_posts/2018-10-05-kotlin-conf-fp-in-kotlin-with-arrow.md
modules/docs/arrow-docs/docs/_posts/2019-02-10-imperative-functional-programming-arrow.md
modules/docs/arrow-docs/docs/_posts/2019-03-12-immutable-conv-1.md
modules/docs/arrow-docs/docs/_sass/components/_navigation.scss
modules/docs/arrow-docs/docs/_sass/components/_wrapper.scss

* Add Immutable Conversations video entry to the blog
* Make some small ninjafixes too 👥

Add Immutable Conversations video entry to the blog

---

modules/docs/arrow-docs/docs/_data/sidebar.yml

- Issue: Fixes #1374
The inclusion of Fiber on Sidebar
To implement this PR,  I had added two properties 'title' and 'url' on the file "modules/docs/arrow-docs/docs/_data/sidebar.yml".
I also had double checked all docs.

The inclusion of Fiber on Sidebar #1374

---

build.gradle

I also ran a clean Dokka task to see if everything worked as expected. I hope I did not miss anything.
closes #1379

Update Dokka to version 0.9.18

---

modules/docs/arrow-docs/docs/_data/sidebar.yml

:/ I messed up the link. This should fix it.

Fix Resource api docs link

---

modules/core/arrow-core-data/src/main/kotlin/arrow/core/Eval.kt
modules/core/arrow-extras-data/src/main/kotlin/arrow/data/MapK.kt
modules/core/arrow-extras-data/src/main/kotlin/arrow/data/SortedMapK.kt
modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Foldable.kt

fixing https://github.com/arrow-kt/arrow/issues/1428

`iterateRight` as extension of `Iterator`

---

build.gradle
modules/effects/arrow-effects-data/src/test/kotlin/arrow/effects/EffectsSuspendDSLTests.kt

See https://youtrack.jetbrains.com/issue/KT-31664

Bump to Kotlin 1.3.31

---

modules/docs/arrow-docs/docs/_posts/2019-07-02-modular-app-kotlin.md

As proposed, here is a MR in order to add a link to my post to the Arrow website. I don't know if I understood well the proposal, so maybe I've done something completely wrong...

New blog post for "Modular functional programming with Kotlin" article

---

modules/core/arrow-core-data/src/test/kotlin/arrow/core/MapKTest.kt
modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/mapk.kt

sure filterMap can be improved in terms of performance, but that was the most elegant version I could figure out.

added MapK's FunctorFilter & TestLaws

---

modules/docs/arrow-docs/docs/docs/optics/fold/README.md

**Super tiny** PR to add a note in order to differentiate:
* Optics `Fold`
* Collection aggregate operation `fold`

Docs: add note about fold

---

modules/docs/arrow-docs/docs/_posts/2019-06-07-kotliners-arrow-fx.md

Bitrise throws this exception in CI:
```
Configuration file: modules/docs/arrow-docs/build/site/_config.yml
Source: modules/docs/arrow-docs/build/site
Destination: modules/docs/arrow-docs/build/_site
Incremental build: disabled. Enable with --incremental
Generating... 
Error: YAML Exception reading /bitrise/src/modules/docs/arrow-docs/build/site/_posts/2019-06-07-kotliners-arrow-fx.md: (<unknown>): mapping values are not allowed in this context at line 2 column 32
```
which is fixed by this PR

quickFix Bitrise exception 

---

arrow-version/_includes/_footer.html
arrow-version/_includes/_main.html
arrow-version/_sass/components/common/_footer.scss
arrow-version/_sass/components/home/_header.scss
arrow-version/_sass/components/home/_main.scss
arrow-version/_sass/components/home/_nav.scss
arrow-version/img/home/arrow-meta-lines-white.svg
arrow-version/js/main-hovers.js
arrow-version/js/main.js

This PR fixes #1569 and home section part of #1564

Paolo 1569 hover home section

---

arrow-version/js/main-hovers.js

This PR fixes an unnecessary opacity in a p element in the footer section

Fix p elements hover

---

README.md
gradle.properties
modules/docs/arrow-docs/docs/docs/README.md

Release notes coming after tagging the release

Release 0.10.0

---

modules/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/EitherTest.kt
modules/docs/arrow-docs/docs/docs/arrow/core/either/README.md

Added rightIfNull Either extension function for kotlin.Any? type. Provides inverse functionality of rightIfNotNull.

Either right if null extension

---

arrow-site/blog/_sass/components/_tab.scss

@AntonioMateoGomez could you review this PR please?
Fix #1602

Responsive mode

---

modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/FlowableK.kt
modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/MaybeK.kt
modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/ObservableK.kt
modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/flowablek.kt
modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/maybek.kt
modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/observablek.kt
modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/FlowableKTests.kt
modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/MaybeKTests.kt
modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/ObservableKTests.kt

Here is my pr for #1501.
For now I just implemented FunctorFilter  instance for ObserableK because I want to have some feedback before implementing FunctorFilter for other types.

Implement FunctorFilter instances for Rx

---

modules/docs/arrow-docs/docs/docs/quickstart/projects/README.md

Add https://github.com/lenguyenthanh/rxarrow to projects list

Add RxArrow to 3rd party projects list

---

modules/fx/arrow-fx/src/main/kotlin/arrow/fx/internal/Utils.kt

Remove Java 8 from TreadLocal in Arrow Fx

---

arrow-site/doc/_sass/components/docs/_sidebar-nav.scss
modules/docs/arrow-docs/docs/_sass/components/docs/_doc-content.scss
modules/docs/arrow-docs/docs/_sass/components/docs/_sidebar-nav.scss
modules/docs/arrow-docs/docs/docs/arrow-meta/README.md

@AntonioMateoGomez could you review this PR please?
Fix #1630

Table style markdown

---

modules/docs/arrow-docs/docs/docs/patterns/monadcomprehensions/README.md

Replace example

---

modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/flowablek.kt
modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/maybek.kt
modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/observablek.kt
modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/FlowableKTests.kt
modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/MaybeKTests.kt
modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/ObservableKTests.kt

Add MonadFilter for rx family. This is my first commit for `ObservableK`. Will add more after making sure every thing is fine for `ObservableK`.
P/S: I'm spamming for #Hacktoberfest.

Implement MonadFilter for Rx family

---

modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/extensions/fluxk.kt
modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/extensions/monok.kt
modules/fx/arrow-fx-reactor/src/test/kotlin/arrow/effects/FluxKTest.kt
modules/fx/arrow-fx-reactor/src/test/kotlin/arrow/effects/MonoKTest.kt
modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/flowablek.kt
modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/maybek.kt
modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/observablek.kt
modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/singlek.kt
modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/FlowableKTests.kt
modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/MaybeKTests.kt
modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/ObservableKTests.kt
modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/SingleKTests.kt

Follows up on https://github.com/arrow-kt/arrow/pull/1624

Fix fx eager evaluation in Reactor and RxJava

---

modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/FluxK.kt
modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/MonoK.kt
modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/extensions/fluxk.kt
modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/extensions/monok.kt

Make Reactor family covariant

---

gradle.properties
modules/docs/arrow-docs/docs/_data/doc-versions.yml
modules/docs/arrow-docs/docs/docs/arrow/typeclasses/alternative/README.md
modules/docs/arrow-docs/docs/docs/quickstart/setup/README.md

After a couple of important hotfixes we're releasing `0.10.1`.
0.10.1 (2019-09-10)
-------------------
* TBD

Release 0.10.1

---

modules/meta/arrow-meta-prototype/testing-plugin/build.gradle

:warning: The branch `base` of this pull request isn't `master`

Fix: change dependency of testing library

---

modules/meta/arrow-meta-prototype/compiler-plugin/src/main/kotlin/kastree/ast/Node.kt
modules/meta/arrow-meta-prototype/compiler-plugin/src/main/kotlin/kastree/ast/Writer.kt
modules/meta/arrow-meta-prototype/compiler-plugin/src/main/kotlin/kastree/ast/psi/Converter.kt
modules/meta/arrow-meta-prototype/testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/Compilation.kt
modules/meta/arrow-meta-prototype/testing-plugin/src/test/resources/Example.kt.meta

:warning:  The `base` branch of this pull request isn't `master`

[META] Add commands to the AST

---

modules/meta/arrow-meta-prototype/compiler-plugin/src/main/kotlin/kastree/ast/Node.kt
modules/meta/arrow-meta-prototype/compiler-plugin/src/main/kotlin/kastree/ast/psi/Converter.kt
modules/meta/arrow-meta-prototype/testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/Compilation.kt

:warning: The base branch isn't `master`.
Small fixes:
* **Compiler**: Fix the filtering of commands with the prefix
* **Testing**: Improvement: more robust assertions

[META] Small fixes

---

modules/meta/arrow-meta-prototype/gradle-plugin/build.gradle
modules/meta/arrow-meta-prototype/gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/ArrowGradlePlugin.kt

Gradle plugin fix

---

modules/meta/arrow-meta-prototype/build.gradle
modules/meta/arrow-meta-prototype/compiler-plugin/build.gradle
modules/meta/arrow-meta-prototype/compiler-plugin/src/main/kotlin/arrow/meta/plugins/comprehensions/ComprehensionsPlugin.kt
modules/meta/arrow-meta-prototype/compiler-plugin/src/test/kotlin/arrow/meta/plugins/comprehensions/ComprehensionsTest.kt
modules/meta/arrow-meta-prototype/compiler-plugin/src/test/kotlin/arrow/meta/plugins/higherkind/HigherkindTest.kt
modules/meta/arrow-meta-prototype/testing-plugin/build.gradle
modules/meta/arrow-meta-prototype/testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/Compilation.kt
modules/meta/arrow-meta-prototype/testing-plugin/src/test/kotlin/arrow/meta/plugin/testing/CompilationTest.kt

:warning: The base branch of this PR isn't `master`
* Fix comprehensions template
* Initial tests about comprehensions

[META] Comprehensions testing

---

build.gradle

Task configuration was changed to follow the [migration guide](https://github.com/Kotlin/dokka/wiki/faq#migrating-from-older-versions-to-0100)
Fixes #1673

Update Dokka to 0.10.0

---

arrow-site/blog/_data/commons.yml
arrow-site/blog/_includes/_books-list.html
arrow-site/blog/_includes/_nav.html

This PR adds Books section description and change the navbar icon link, now pointing to arrow site.

Books section description

---

README.md
modules/docs/arrow-docs/docs/docs/quickstart/setup/README.md

**Reason**: website and main README changes in different moments during release time.

Recover setup guidelines in main page

---

modules/meta/arrow-meta-prototype/compiler-plugin/build.gradle

Target branch is pointed to `rr-meta-prototype-integration`
#1690

Removed comment from the third line of the shadowJar contents

---

.travis.yml
README.md
gradle.properties

Bumps version for next development iteration.

Next iteration 0.10.2-SNAPSHOT

---

README.md
modules/docs/arrow-docs/docs/docs/quickstart/setup/README.md

**Reason**:
- Difficult to realize about the link of libraries.
**Additional reason**:
- PR to check that everything is working as expected with the automatic checks reorganization.

Documentation: tiny format detail

---

modules/docs/arrow-docs/docs/docs/patterns/monads/README.md

Replace a method input parameter written in Java with its Kotlin counterpart

Update "Monads explained in Kotlin (again)" docs

---

modules/aql/arrow-aql/src/main/kotlin/arrow/aql/Max.kt
modules/aql/arrow-aql/src/main/kotlin/arrow/aql/Min.kt
modules/aql/arrow-aql/src/main/kotlin/arrow/aql/extensions/either.kt
modules/aql/arrow-aql/src/main/kotlin/arrow/aql/extensions/list.kt
modules/aql/arrow-aql/src/main/kotlin/arrow/aql/extensions/nonemptylist.kt
modules/aql/arrow-aql/src/main/kotlin/arrow/aql/extensions/option.kt
modules/aql/arrow-aql/src/main/kotlin/arrow/aql/extensions/sequence.kt
modules/aql/arrow-aql/src/main/kotlin/arrow/aql/extensions/try.kt
modules/aql/arrow-aql/src/test/kotlin/arrow/aql/tests/AQLTests.kt

Added implementation for Max and Min in AQL

Implemented AQL's Max and Min 

---

gradle.properties

It bumps version for the next development iteration.

Next iteration 0.10.3-SNAPSHOT

---

modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt
modules/core/arrow-test/src/main/kotlin/arrow/test/laws/ApplicativeErrorLaws.kt

Implement suspend catch for ApplicativeError

---

.gitignore
README.md
modules/docs/arrow-docs/docs/docs/generic/product/README.md
modules/docs/arrow-docs/docs/docs/quickstart/libraries/README.md
modules/docs/arrow-docs/docs/docs/quickstart/setup/README.md

Also added `**/.kotlintest/` folder to gitignore to avoid unnecessary tracked files

Fix typo and replace compile with implementation in various md files 

---

build.gradle
modules/integrations/arrow-integrations-retrofit-adapter/src/main/kotlin/arrow/integrations/retrofit/adapter/CallKindAdapterFactory.kt

Make retrofit compatible with lower API versions

---

modules/meta/arrow-annotations/src/main/java/arrow/extension.kt

* Local variable
* Function
and fix messages.

More targets for extension annotation

---

modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Applicative.kt

Just a generally very useful method on applicatives

Add replicate to applicative

---

modules/fx/arrow-fx/src/main/kotlin/arrow/fx/extensions/io.kt
modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt

this PR adds two extension functions to convert an Either to an IO
https://github.com/arrow-kt/arrow/issues/1777

#1777: add extension function that converts an Either to an IO

---

modules/docs/arrow-docs/docs/docs/arrow/data/mapk/README.md

Fix the return type of flatMap

Fix the return type of flatMap

---

modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/MonoK.kt
modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/extensions/monok.kt
modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/singlek.kt
modules/fx/arrow-fx/src/main/kotlin/arrow/fx/extensions/io.kt
modules/fx/arrow-fx/src/main/kotlin/arrow/fx/typeclasses/UnsafeRun.kt

Add unsafeCancellableRun

---

modules/docs/arrow-docs/docs/docs/arrow/effects/typeclasses/bracket/README.md

Looks like the directory structure changed a bit ... 😄

Fix broken link to Bracket.kt

---

README.md
gradle.properties

It bumps version for the next development iteration.

Next iteration 0.10.4-SNAPSHOT

---

modules/core/arrow-core-data/src/test/kotlin/arrow/core/SortedMapKTest.kt
modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/sortedmap.kt

this adds an Eq SortedMapK instance

adds a SortedMapK Eq instance

---

modules/core/arrow-core-data/src/test/kotlin/arrow/core/SortedMapKTest.kt
modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/sortedmap.kt

building on https://github.com/arrow-kt/arrow/pull/1805 this adds a SortedMapK Hash instance

add a SortedMapK Hash instance

---

modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Align.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/ListKTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/MapKTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/OptionTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/SequenceKTest.kt
modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/listk.kt
modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/mapk.kt
modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/option.kt
modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/sequenceK.kt
modules/core/arrow-test/src/main/kotlin/arrow/test/laws/AlignLaws.kt
modules/docs/arrow-docs/docs/_data/sidebar.yml
modules/docs/arrow-docs/docs/docs/arrow/typeclasses/align/README.md
modules/docs/arrow-docs/docs/docs/arrow/typeclasses/semialign/README.md

typeclass Align with some instances. including docs and tests

Align with instances

---

modules/core/arrow-core-data/src/test/kotlin/arrow/core/IdTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/ListKTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/MapKTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/NonEmptyListTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/OptionTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/SequenceKTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/SortedMapKTest.kt
modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/mapk.kt
modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/sortedmap.kt
modules/core/arrow-test/src/main/kotlin/arrow/test/laws/AlignLaws.kt
modules/core/arrow-test/src/main/kotlin/arrow/test/laws/SemialignLaws.kt

add SortedMapK Semialign instance

Sortedmapk semialign

---

modules/core/arrow-core-data/src/test/kotlin/arrow/core/ConstTest.kt

Additional patch for #1789 & PR #1791

Moved ConstTest (#1789)

---

modules/mtl/arrow-mtl/src/main/kotlin/arrow/mtl/extensions/kleisli.kt

Fix Kleisli fx

---

modules/core/arrow-core-data/src/test/kotlin/arrow/core/ConstTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/EitherTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/IdTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/IorTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/ListKTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/MapKTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/NonEmptyListTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/OptionTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/SequenceKTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/SetKTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/SortedMapKTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/TryTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/ValidatedTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/extensions/NumberHashTest.kt
modules/core/arrow-core-data/src/test/kotlin/arrow/core/extensions/StringInstancesTest.kt
modules/core/arrow-generic/src/test/kotlin/arrow/generic/ProductTest.kt
modules/core/arrow-test/src/main/kotlin/arrow/test/generators/Generators.kt
modules/core/arrow-test/src/main/kotlin/arrow/test/laws/EqLaws.kt
modules/core/arrow-test/src/main/kotlin/arrow/test/laws/HashLaws.kt
modules/core/arrow-test/src/main/kotlin/arrow/test/laws/OrderLaws.kt
modules/core/arrow-test/src/main/kotlin/arrow/test/laws/ShowLaws.kt
modules/free/arrow-free-data/src/test/kotlin/arrow/free/FreeApplicativeTest.kt
modules/free/arrow-free-data/src/test/kotlin/arrow/free/FreeTest.kt
modules/streams/arrow-streams/src/test/kotlin/arrow/streams/internal/FreeCTest.kt
modules/ui/arrow-ui-data/src/test/kotlin/arrow/ui/SumTest.kt

refactor EqLaws, HashLaws, OrderLaws and ShowLaws to use Gen for testdata creation (#1819)

refactor EqLaws, HashLaws, OrderLaws and ShowLaws to use Gen for testdata

---

modules/docs/arrow-docs/docs/docs/quickstart/projects/README.md

I use this part of my project to try out different features of the Arrow library. I believe some other people would benefit from looking at these simple examples.

Update README with arrow-examples link

---

modules/docs/arrow-docs/src/main/kotlin/ExtensionsHelper.kt

There is a couple of functions called `tcMarkdownList` and `dtMarkdownList` that, given a `DataType` or a `TypeClass`, generate a table containing all the typleclasses or data types that support them.
Those functions generate wrong links so the Arrow site has a lot of broken links.
This pull request changes those changes to generate the links in the expected format.

Generates Dokka API docs links

---

modules/docs/arrow-docs/docs/_code/fx-home-code.md
modules/docs/arrow-docs/docs/_code/optics-home-code.md

Update home page code snippets

---

modules/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt
modules/core/arrow-core-data/src/main/kotlin/arrow/core/ListK.kt
modules/core/arrow-core-data/src/main/kotlin/arrow/core/NonEmptyList.kt
modules/core/arrow-core-data/src/main/kotlin/arrow/core/Option.kt
modules/core/arrow-core-data/src/main/kotlin/arrow/core/Try.kt
modules/core/arrow-core-data/src/main/kotlin/arrow/core/Validated.kt

This PR removes level tags from code

Removes level tags

---

gradle.properties
modules/docs/arrow-docs/docs/_data/doc-versions.yml
modules/docs/arrow-docs/docs/docs/arrow-core/quickstart/setup/README.md

0.10.4 (2019-12-19)
-------------------
- Release 0.10.4 (#1866) [Francisco Diaz]
- Arrow-Core language edits (#1865) [Francisco Diaz]
- Removes level tags from code (#1864) [AntonioMateoGomez]
- Update home page code snippets (#1862) [Juan Valencia]
- Adding *> and <* operations to Apply (#1843) [Miguel Coleto]
- Redesign implementation (#1836) [AntonioMateoGomez]
- Update suspended KDocs (#1860) [Simon Vergauwen]
- Overwrite cancelable for EitherT (#1855) [Simon Vergauwen]
- Arrow Fx MTL (#1846) [Simon Vergauwen]
- Make CC IOConnection aware (#1848) [Simon Vergauwen]
- Update Gradle and some libs to latest version (6.0.1) (#1840) [Stojan Anastasov]
- Update README with arrow-examples link (#1841) [Attila Domokos]
- Fix typo in monad tutorial [Paco]
- Specialized aligns (#1831) [Alphonse …

Release 0.10.4

---

README.md
gradle.properties

It bumps version for the next development iteration.

Next iteration 0.10.5-SNAPSHOT

---

modules/docs/arrow-docs/docs/docs/arrow-core/typeclasses/crosswalk/README.md

s**a**quenceL -> s**e**quenceL

[doc] Crosswalk - typo

---

modules/integrations/arrow-integrations-jackson-module/build.gradle
modules/integrations/arrow-integrations-jackson-module/gradle.properties
modules/integrations/arrow-integrations-jackson-module/src/main/kotlin/arrow/integrations/jackson/module/ArrowModule.kt
modules/integrations/arrow-integrations-jackson-module/src/main/kotlin/arrow/integrations/jackson/module/NonEmptyListModule.kt
modules/integrations/arrow-integrations-jackson-module/src/main/kotlin/arrow/integrations/jackson/module/OptionModule.kt
modules/integrations/arrow-integrations-jackson-module/src/test/kotlin/arrow/integrations/jackson/module/DataHelpers.kt
modules/integrations/arrow-integrations-jackson-module/src/test/kotlin/arrow/integrations/jackson/module/NonEmptyListModuleTest.kt
modules/integrations/arrow-integrations-jackson-module/src/test/kotlin/arrow/integrations/jackson/module/OptionModuleTest.kt
settings.gradle

Ported NonEmptyListModule and OptionModule from [Jackson Module Scala](https://github.com/FasterXML/jackson-module-scala)

Arrow jackson support

---

modules/docs/arrow-docs/docs/docs/arrow-core/patterns/monadcomprehensions/README.md

Fix one example as reported on Gitter

Fixes in Monad comprehensions doc

---

modules/docs/arrow-docs/docs/docs/arrow-core/quickstart/projects/README.md

Adds Kompute

---

modules/docs/arrow-docs/docs/_includes/_head-docs.html
modules/docs/arrow-docs/docs/_includes/_head.html

This PR adds defer tag to arrow-playground head script in order to reduce loading times
Closes #1910

Reducing loading times in docs

---

modules/docs/arrow-docs/docs/_includes/_head-docs.html
modules/docs/arrow-docs/docs/_includes/_head.html

Reverts arrow-kt/arrow#1911
Closes #1918

Revert "Reducing loading times in docs"

---

.github/workflows/build_documentation.yml
.github/workflows/publish_documentation.yml
build.gradle
modules/ank/arrow-ank-gradle/build.gradle
modules/docs/arrow-docs/README.md
modules/docs/arrow-docs/build.gradle
settings.gradle

:warning: PR on `is-ank-update` branch.
It corresponds to the [second alternative](https://github.com/arrow-kt/arrow/pull/1921#discussion_r365356403) that was proposed in #1921 review.

Extract arrow-docs from build

---

modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IOParMap2.kt
modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IOParMap3.kt
modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IORacePair.kt
modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IORaceTriple.kt
modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt

Adds trampolining to parallel ops.

Fix stack safety parallel ops

---

.github/workflows/publish_documentation.yml

Current doc publication is failing because this update is missing.

Fix #1936: update doc publication

---

.github/workflows/release.yml

Config: publish artifacts from release/0.11.0 branch

---

gradle.properties

:warning:  PR on `release/0.11.0`

Fix version to upload 0.11.0-SNAPSHOT to OSS

---

build.gradle
modules/benchmarks/arrow-benchmarks-fx/build.gradle
modules/docs/arrow-docs/build.gradle

- Move` jmh` plugins to `arrow-benchmarks-fx` module
- `gitPublish` for documentation is not used
- `bintray` for uploading artifacts is not used
- Remove unused repositories

Clean dead configuration

---

README.md
modules/docs/arrow-docs/docs/docs/arrow-fx/fx/README.md
modules/docs/arrow-docs/docs/docs/arrow-fx/fx/async/README.md

Fixes #1701 
Hopefully I made the right changes. I will try to be more helpful in the future. I was told to start slow (poke @andresgalante :) )

DOCS: update slack link #arrow channel

---

modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IO.kt
modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt

See https://github.com/arrow-kt/arrow/pull/2003#discussion_r373260146

Fix unsafeRunTimedTotal for know Errors

---

modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IO.kt
modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt

Same as #2004 but against the correct branch

Fix unsafeRunTimed for errors

---

modules/fx/arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Concurrent.kt

Add note to parTraverse and parSequence explaining problems with large/infinte collections

---

modules/core/arrow-test/src/main/kotlin/arrow/test/laws/ConcurrentLaws.kt
modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IO.kt
modules/fx/arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Bracket.kt
modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt

add onError to Bracket

---

modules/docs/arrow-docs/docs/docs/arrow-fx/typeclasses/bracket/README.md

Fixes #2007 
Add clarification about Bracket's guarantee/guaranteeCase/onError/onCancel

Add clarification about Bracket's guarantee

---

modules/core/arrow-test/src/main/kotlin/arrow/test/laws/MonadThrowLaws.kt

Covers small part of #2029 .
Create test suite for MonadThrowLaws.

Add MonadThrow laws

---

modules/core/arrow-test/src/main/kotlin/arrow/test/laws/AsyncLaws.kt

Covers small part of #2029 .
Increase test suite for AsyncLaws so we can prevent the user being able to break behaviour.

Increase test suite for AsyncLaws

---

modules/docs/arrow-docs/docs/docs/arrow-core/patterns/dependencyinjection/README.md

When reviewing links that can be broken, I found this piece of old documentation.

Clean: old documentation

---

.github/workflows/check_build_integration.yml
.github/workflows/check_doc_integration.yml
README.md
docs/move-to-multi-repo/how-it-works.md
docs/move-to-multi-repo/how-to-extract-content.md
docs/move-to-multi-repo/implementation-plan.md
docs/move-to-multi-repo/scripts/copy-conf-arrow-docs.sh
docs/move-to-multi-repo/scripts/copy-conf-arrow-site.sh
docs/move-to-multi-repo/scripts/extract-content.sh

- Fixes in scripts
- Documentation updates

Doc: details about the move

---

.github/workflows/sync-release-branch-arrow.yml

To avoid similar cases like https://github.com/arrow-kt/arrow-ank/issues/17

Add sync with release/0.11.0 branch

---

.github/workflows/publish_arrow.yml
.github/workflows/run_tasks.yml
scripts/commons4gradle.sh

- Check new Gradle tasks
- Publish artifacts into OSS

Conf: add new actions

---

CONTRIBUTING.md
RELEASE.md
docs/move-to-multi-repo/README.md
docs/move-to-multi-repo/how-it-works.md
docs/move-to-multi-repo/how-to-manage-several-repositories.md
templates/workflows/publish_doc_arrow-.yml

- Improve `CONTRIBUTING.md`
- Add `RELEASE.md` (the section about documentation is missing because that flow is going to be improved in the next days).
- Include other small related changes

Adding documentation details

---

.github/workflows/check_build_integration.yml
.github/workflows/check_doc_integration.yml
.github/workflows/publish_arrow-core.yml
.github/workflows/run_tasks.yml
scripts/issue-create-description.sh
scripts/site-publish.sh
templates/workflows/build_arrow-.yml
templates/workflows/build_doc_arrow-.yml
templates/workflows/check_build_integration.yml
templates/workflows/check_doc_integration.yml
templates/workflows/publish_arrow-.yml
templates/workflows/publish_doc_arrow-.yml

- Extract env variable for ARROW_LIB
- Fix links in created issues
- Fix environment because of https://github.com/arrow-kt/arrow-core/issues/91
- Add cache invalidation
- Update templates

Conf: small fixes

---

README.md

Adds small note to add media resources in the media repo, not general Arrow repo

small update to readme about media

---

docs/move-to-multi-repo/utils/create-workspace-with-https.sh
docs/move-to-multi-repo/utils/create-workspace-with-ssh.sh

As I tried to learn more about setting up the Arrow development
environment, I noticed that the separate arrow-docs does not exist.
Removing it from the script.
See the shell output before this change:
```
% curl https://raw.githubusercontent.com/arrow-kt/arrow/master/docs/move-to-multi-repo/utils/create-workspace-with-ssh.sh | bash
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   603  100   603    0     0   2523      0 --:--:-- --:--:-- --:--:--  2523
Cloning into 'arrow'...
remote: Enumerating objects: 103, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 79565 (delta 47), reused 38 (delta 11), pack-reused 79462
Receiving objects: 100% …
```

Remove arrow-docs from the repository list to be cloned

---

scripts/commons4gradle.sh

Fix replacements

---

.github/workflows/run_tasks.yml
docs/move-to-multi-repo/how-to-manage-several-repositories.md
generic-conf.gradle
scripts/commons4gradle.sh
scripts/libs-install.sh
scripts/project-test.sh
scripts/repository-build-doc-with-local-conf.sh
scripts/repository-test.sh

**Next change**: add global checks during pull requests (it's ready; it takes into account several PRs together)

New Gradle task: buildArrowDocWithLocalDeps

---

scripts/check-build-integration.sh
scripts/check-doc-integration.sh
scripts/commons4gradle.sh
scripts/lib-publish.sh
scripts/libs-install.sh
scripts/libs-publish.sh
templates/workflows/check_previous_build_integration.yml
templates/workflows/check_previous_doc_integration.yml

It will allow to add optional global checks execution during pull requests.
If several pull requests use the same branch name, they will be considered together during those checks execution.

Add previous global checks

---

scripts/check-build-integration.sh
scripts/check-doc-integration.sh

To wait for creation/merging several related PRs before starting the global checks.

Configuration: add waiting time

---

docs/libraries/how-to-build-a-library.md
docs/libraries/how-to-propose-an-improvement.md

These guidelines appear in every README.
* How to build the library
* How to propose an improvement

[Documentation] Add details to default guidelines for all the libraries

---

.github/workflows/run_tasks.yml

Configuration: consider all the libs for checking Gradle tasks

---

docs/libraries/how-to-add-a-new-module.md

Documentation: How to add a new module

---

docs/libraries/how-to-add-a-new-module.md

Link to BOM file was pointing to a branch that no longer exists, changed to point to master.

Updated link to bom file link

---

docs/gradle/configuration.md

To be referenced during code reviews.

Doc: dependency configurations

---

gradle/main.gradle

`jCenter` is failing to detect some dependencies

Configuration: add mavenCentral

---

BOM-file/build.gradle
BOM-file/gradle.properties
gradle/android-module.gradle
gradle/main.gradle
gradle/publication.gradle

- Add arrow-continuations
- Remove arrow-streams
- Add missing data required by Maven Central
- Fix format of publish configuration
- Remove temporary repository for `kotlin-metadata` and `kotlin-compiler-lite` (use of Maven Central)

Configuration: update BOM file and add required data for Maven Central

---

.github/workflows/publish_arrow-core.yml
.github/workflows/publish_arrow.yml

- Relocate the change
- Fix the regex

Configuration: fix update documentation when release

---

.github/workflows/publish_arrow-ank.yml
.github/workflows/publish_arrow-check.yml
.github/workflows/publish_arrow-core.yml
.github/workflows/publish_arrow-fx.yml
.github/workflows/publish_arrow-incubator.yml
.github/workflows/publish_arrow-integrations.yml
.github/workflows/publish_arrow-optics.yml
.github/workflows/publish_arrow-stack.yml
.github/workflows/publish_arrow-ui.yml
.github/workflows/publish_arrow.yml

This pull request will allow different version changes:
* Just RELEASE
* Just SNAPSHOT
* Both RELEASE and SNAPSHOT
as well as other configuration changes as usual.
* Unify OSS publication
* Fix BOM file publication when release time

Configuration: improve OSS publication

---

docs/libraries/how-to-run-the-website-in-your-local-server.md
scripts/repository-run-website.sh

Because of https://github.com/arrow-kt/arrow-site/pull/78

Update site generation

---

arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Fiber.kt

Adds missing deprecations in Fiber.kt

CU-et6bmb Deprecate Fiber.kt

---

.github/workflows/publish_doc.yml

Preventing errors with the new AWS CLI.

Configuration: add default region

---

.github/workflows/build.yml
.github/workflows/build_doc.yml
.github/workflows/publish.yml
.github/workflows/publish_arrow-stack.yml
.github/workflows/publish_doc.yml

To avoid issues with new GH environments.

Configuration: explicit JDK

---

arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Either.kt
arrow-site/docs/_data/sidebar-core.yml
arrow-site/docs/_data/sidebar-fx.yml
arrow-site/docs/_data/sidebar-optics.yml
arrow-site/docs/docs/datatypes/intro/README.md
arrow-site/docs/docs/dsl/README.md
arrow-site/docs/docs/every/README.md
arrow-site/docs/docs/fold/README.md
arrow-site/docs/docs/patterns/errorhandling/README.md
arrow-site/docs/docs/patterns/glossary/README.md
arrow-site/docs/docs/patterns/monadcomprehensions/README.md
arrow-site/docs/docs/patterns/monads/README.md
arrow-site/docs/docs/quickstart/README.md
arrow-site/docs/docs/setter/README.md
arrow-site/src/main/kotlin/OpticsHelper.kt

Documentation: remove old content and fix broken links

---

arrow-site/build.gradle
arrow-site/docs/_code/meta-home-code.md

NOTE: It cannot be checked with Ank because the Kotlin version doesn't match with Arrow now. It will be checked as soon as they match.

Documentation: update Arrow Meta example

---

.github/workflows/build.yml
.github/workflows/publish.yml
arrow-libs/fx/settings.gradle

To avoid issues with the staging repositories creation.

Configuration: split deployment

---

.github/workflows/build_doc.yml
.github/workflows/publish_doc.yml
CONTRIBUTING.md
arrow-libs/build.gradle
arrow-site/build.gradle
arrow-site/gradle/scripts/generate-site.sh

* `buildDoc` to generate and validate API documentation
* `buildSite` to generate the website as well

Add missing Gradle tasks

---

.github/workflows/build.yml

This feature wasn't included when joining the repositories again.

Configuration: recover test reports

---

.github/scripts/publish-landing-page.sh
.github/scripts/publish-latest-release.sh
.github/workflows/build_doc.yml
.github/workflows/publish_doc.yml
arrow-site/build.gradle

To be able to publish _breaking_ changes

Configuration: improve doc publication

---

arrow-site/docs/_includes/_head.html

Landing page uses files from root dir.

Documentation: fix basedir for landing page (step 2)

---

.github/workflows/build_doc.yml
.github/workflows/publish_doc.yml

It happens with `compile<..>Jvm` tasks.

Fixes random failure with Dokka 0.10.0 and MPP

---

.github/scripts/set-env.sh
.github/workflows/build.yml
.github/workflows/build_doc.yml

Fixes this wrong message during build checks:
```
ARROW
A library for Typed Functional Programming in Kotlin
vmerge-SNAPSHOT (Kotlin 1.5.10)
arrow-libs [build]
```

Configuration: fixes wrong version

---

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Option.kt

fix incorrect option.zip type parameters

---

arrow-site/docs/_includes/_head-docs.html
arrow-site/docs/_includes/_head.html

@raulraja @franciscodr could you review this PR please?

Playground deleted

---

.github/workflows/pull_request.yml

Release 1.0.1

---

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/typeclasses/Semigroup.kt

The smallest PR I've ever made! :)

Make Semigroup a fun interface

---

arrow-site/docs/_code/core-home-code.md
arrow-site/docs/_code/fx-home-code.md
arrow-site/docs/_code/meta-home-code.md
arrow-site/docs/_code/optics-home-code.md
arrow-site/docs/_sass/components/docs/_code.scss
arrow-site/docs/_sass/components/home/_header.scss
arrow-site/docs/css/home-styles.scss

@could you review this PR please? ;)

Code block style

---

README.md

Clean up README after gradle upgrade

---

gradle/libs.versions.toml

Thanks to @raulraja and @JavierSegoviaCordoba changes in https://github.com/arrow-kt/arrow-gradle-config/pull/36

CU-23dm3ye support maven publication

---

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/dsl.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/isos.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/lenses.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/prism.kt

a mistake from  https://github.com/arrow-kt/arrow/pull/2678 
files before #2678 MyGenerated.kt after org.example.MyGenerated.kt

File name generation fix

---

arrow-libs/fx/arrow-fx-coroutines/api/arrow-fx-coroutines.api
arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Resource.kt

resolves https://github.com/arrow-kt/arrow/issues/2635
introduces kotlin API breaking change

resource tap deprecation

---

arrow-site/docs/docs/traversal/README.md

I'm just starting with traversals and I noticed a few code inconsistencies in the [docs examples](https://arrow-kt.io/docs/optics/traversal/#usage). Hopefully this PR will help to fix them.

Fix traversal code samples of docs

---

.github/workflows/generate-alpha-tag.yaml
.github/workflows/generate-tag.yaml
.github/workflows/publish.yml
.github/workflows/pull_request.yml

the update from https://github.com/arrow-kt/arrow/pull/2709

revert java setup

---

.github/workflows/generate-alpha-tag.yaml

fix alpha tag build task

---

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/continuations/Effect.kt
arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-effect-guide-01.kt

ensure(path.isEmpty()) { EmptyPath }
should be
ensure(path.isNotEmpty()) { EmptyPath }

Fix example in documentation

---

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Result.kt
arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/ResultTest.kt

Fixes Result.zip which results in NullPointerException instead of the correct `null` success value.

[BUGFIX] Result.zip

---

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/IterableTest.kt

add separateEither and separateValidated test

---

arrow-libs/fx/arrow-fx-coroutines/api/arrow-fx-coroutines.api
arrow-libs/fx/arrow-fx-coroutines/src/jvmMain/kotlin/arrow/fx/coroutines/ResourceExtensions.kt
arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resourceextensions-01.kt
arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resourceextensions-02.kt
arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resourceextensions-03.kt
arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resourceextensions-05.kt

Follow-up on #2847 to add deprecations and back ports of new APIs for JVM target.

Additional deprecations, and backports for JVM

---

README.md

Mention Arrow 2.0 in README

---

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt

Added `AT_MOST_ONCE`  Invocation in [`fold`](https://github.com/poseidon2060/arrow/blob/a0414b158dbe8d9e318e93377058dcdf25897514/arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt#L826)

Adding `AT_MOST_ONCE` in lambdas

---

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Fold.kt

When trying to update to `alpha.61` for the websiteI realised I missed renaming this argument.

Missed block argument in fold

---

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/utils.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/DSLTests.kt

Fix sanitization of keywords

---

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/DeclarationUtils.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/OpticsProcessor.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/domain.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/dsl.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/errors.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/isos.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/processor.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/snippets.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/IsoTests.kt

This backports the logic in #3013 for creation of isos for value classes

Backport creation of Isos for value classes

---

.github/workflows/pull_request.yml

Cancel previous PR action on new commit

---

arrow-libs/fx/arrow-fx-coroutines/build.gradle.kts

Remove test dependency from Arrow Fx

---

arrow-libs/core/arrow-core/api/arrow-core.api
arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/MemoizedDeepRecursiveFunction.kt
arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/MemoizationTest.kt

Based on [this conversation in `arrow-site`](https://github.com/arrow-kt/arrow-website/issues/213#issuecomment-1628545020)

MemoizedDeepRecursiveFunction

---

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/processor.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/LensTests.kt

From [this Slack thread](https://kotlinlang.slack.com/archives/C5UPMM0A0/p1689247117711899)

Fix problem with optics and <*> generics

---

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/MappersSpec.kt

Migrate MappersSpec to kotlin-test

---

arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/ResourceTestJvm.kt

Refactor ResourceTestJvm from Kotest Plugin to Kotlin-test runtime

---

arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/ParZip6JvmTest.kt

Refactor ParZip6JvmTest from Kotest Plugin to Kotlin-test runtime

---

arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/ParZip5JvmTest.kt

Refactor ParZip5JvmTest from Kotest Plugin to Kotlin-test runtime

---

arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/ParZip3JvmTest.kt

Refactor ParZip3JvmTest from Kotest Plugin to Kotlin-test runtime

---

arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/ParZip2JvmTest.kt

Refactor ParZip2JvmTest from Kotest Plugin to Kotlin-test runtime

---

arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/ParZip4JvmTest.kt

Refactor ParZip4JvmTest from Kotest Plugin to Kotlin-test runtime

---

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/RaiseAccumulateSpec.kt

refactor: migrate RaiseAccumulateSpec to kotlin-test

---

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/EffectSpec.kt

refactor: migrate EffectSpec to kotlin-test

---

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/test/GeneratorsTest.kt

refactor: migrate GeneratorsTest to kotlin-test

---

README.md

Update Maven badge link

---

arrow-libs/fx/arrow-fx-stm/build.gradle.kts

New warning has been added to the mix

Fix problem in build in 2.1

---

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/domain.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/lenses.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/DSLTests.kt

Fix optics generation for `object` name

---

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt

Remove deprecated getHandle() from KDoc in Either

---

.github/workflows/pull_request.yml
arrow-libs/core/arrow-core/build.gradle.kts
arrow-libs/fx/arrow-collectors/build.gradle.kts
arrow-libs/fx/arrow-fx-coroutines/build.gradle.kts
gradle/libs.versions.toml

Other targets (Browser, D8) are too expensive to run every time.

Only test on Node for WebAssembly

---

arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Traversal.kt

Fix traversal invoke

---

arrow-libs/resilience/arrow-resilience/src/commonTest/kotlin/arrow/resilience/SagaSpec.kt

This test checks the correct behavior of `saga` + `raise`.

Test for #3458

---

arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/Compilation.kt
buildSrc/src/main/kotlin/arrow.kotlin.gradle.kts

This PR is required because of changes in the _Kotlin Compatibility Testing_ program we are part of (in short, `-dev` versions of the Kotlin compiler are tested against Arrow if we are part of the program)

Upgrade configuration for Kotlin User Projects

---

.github/workflows/pull_request.yml
arrow-libs/suspendapp/suspendapp-test-app/build.gradle.kts
arrow-libs/suspendapp/suspendapp-test-app/src/commonMain/kotlin/app.kt
arrow-libs/suspendapp/suspendapp-test-app/src/jsMain/kotlin/main.kt
arrow-libs/suspendapp/suspendapp-test-app/src/jvmMain/kotlin/main.kt
arrow-libs/suspendapp/suspendapp-test-app/src/nativeMain/kotlin/main.kt
arrow-libs/suspendapp/suspendapp-test-app/src/wasmJsMain/kotlin/main.kt
arrow-libs/suspendapp/suspendapp-test-runner/build.gradle.kts
arrow-libs/suspendapp/suspendapp-test-runner/src/test/kotlin/JsSpec.kt
arrow-libs/suspendapp/suspendapp-test-runner/src/test/kotlin/JvmSpec.kt
arrow-libs/suspendapp/suspendapp-test-runner/src/test/kotlin/NativeSpec.kt
arrow-libs/suspendapp/suspendapp-test-runner/src/test/kotlin/ProcessProvider.kt
arrow-libs/suspendapp/suspendapp-test-runner/src/test/kotlin/SuspendAppTest.kt
arrow-libs/suspendapp/suspendapp-test-runner/src/test/kotlin/WasmJsSpec.kt
build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts

depends on building the release executables for a test application and executing it for various scenarios

test(suspendapp): add test harness for suspendapp

---

arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/await/AwaitAllScope.kt

Mark `AwaitAllScope` as experimental

---

arrow-libs/stack/build.gradle.kts
buildSrc/src/main/kotlin/arrow.kotlin.gradle.kts

- Do not publish `arrow-raise-ktor-server`
- Fix `arrow-stack` to contain all projects

Some tweaks to publication

---

arrow-libs/suspendapp/suspendapp-ktor/api/suspendapp-ktor.api
arrow-libs/suspendapp/suspendapp-ktor/src/commonMain/kotlin/arrow/continuations/ktor/KtorServer.kt
arrow-libs/suspendapp/suspendapp-ktor/src/jvmMain/kotlin/arrow/continuations/ktor/KtorServer.jvm.kt
arrow-libs/suspendapp/suspendapp-ktor/src/nonJvmMain/kotlin/arrow/continuations/ktor/KtorServer.nonJvm.kt
buildSrc/src/main/kotlin/arrow.kotlin.gradle.kts

This is a followup to arrow-kt/suspendapp#115
Related docs update: https://github.com/arrow-kt/arrow-website/pull/390

warn if ktor shutdownhook enabled

---

.github/workflows/pull_request.yml
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/arrow.kotlin.gradle.kts
gradle/libs.versions.toml

This is the new [recommended way](https://developer.android.com/kotlin/multiplatform/plugin#apply) to have a project with KMP with Android as one of the targets.

Migrate to Android KMP plug-in

---

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/domain.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/processor.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/Compilation.kt

Tests with KSP2

---

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/domain.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/dsl.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/iso.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/lenses.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/prism.kt
arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/DSLTests.kt

Respect upper bounds of generics

---

.github/workflows/pull_request.yml
gradle.properties

By caching Native artifacts and dropping tvOS and watchOS as targets

Improve CI times

---

arrow-libs/core/arrow-core/api/android/arrow-core.api
arrow-libs/core/arrow-core/api/arrow-core.klib.api
arrow-libs/core/arrow-core/api/jvm/arrow-core.api
arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Option.kt

`validate` for `Option`
