arrow-kt/arrow

kats/build.gradle
By adding the appended `gradle` configuration, you allow gradle to print on the log the result of each unit test running with the build. This is pretty handy to read CI logs.
The result can be checked on this build CI checks.
=> print verbose log of tests on console

katz/src/main/kotlin/katz/Either.kt, katz/src/main/kotlin/katz/NonEmptyList.kt, katz/src/main/kotlin/katz/Option.kt, katz/src/main/kotlin/katz/Try.kt
Before talk and discuss with @raulraja, we've concluded that this restriction has no sense. We can't more restrict that the language itself and moreover this restriction avoid models that we need like `fromNullable` in `Option`.
=> Remove Any type restriction

katz/src/main/kotlin/katz/data/Either.kt, katz/src/main/kotlin/katz/data/OptionT.kt, katz/src/main/kotlin/katz/instances/EitherMonad.kt, katz/src/main/kotlin/katz/instances/IdMonad.kt, katz/src/main/kotlin/katz/instances/IorMonad.kt, katz/src/main/kotlin/katz/instances/OptionTMonad.kt, katz/src/main/kotlin/katz/typeclasses/HigherKinds.kt, katz/src/test/kotlin/katz/data/EitherTest.kt, katz/src/test/kotlin/katz/data/IorTest.kt
=> Implement OptionT as HK2

katz/src/main/kotlin/katz/arrow/FunctionK.kt, katz/src/main/kotlin/katz/data/Either.kt, katz/src/main/kotlin/katz/data/Id.kt, katz/src/main/kotlin/katz/data/Ior.kt, katz/src/main/kotlin/katz/data/NonEmptyList.kt, katz/src/main/kotlin/katz/data/Option.kt, katz/src/main/kotlin/katz/data/OptionT.kt, katz/src/main/kotlin/katz/data/Reader.kt, katz/src/main/kotlin/katz/instances/CoproductComonad.kt, katz/src/main/kotlin/katz/instances/EitherMonad.kt, katz/src/main/kotlin/katz/instances/IdMonad.kt, katz/src/main/kotlin/katz/instances/IorMonad.kt, katz/src/main/kotlin/katz/instances/NonEmptyListMonad.kt, katz/src/main/kotlin/katz/instances/OptionMonad.kt, katz/src/main/kotlin/katz/instances/OptionTMonad.kt, katz/src/main/kotlin/katz/typeclasses/Applicative.kt
Fix variance on FuntionK.
Suppress unused parameter Aplicative.kt due to dummyparamenter hack
Typealases created:
- EitherKind
- IdKind
- IorKind
- OptionKind
Also return concrete classes instead of HK counterpart on Monads
=> Create and use type alias for HK concrete clases and small fixes

gradle.properties
Fixes #71 
Disabling incremental compilation for the project to check how it behaves without it for CI / Jitpack.
CI seems to compile properly (It has not been compiling in my PR #66) for many inference types failing that are also included on this branch code.
Are you ok if we merge this for now to avoid problems? I think this will also help on getting automatic jitpack snapshot deploys working again.
=> Fix Jitpack snapshots and CI: disable incremental compilation

katz/src/main/kotlin/katz/data/Kleisli.kt, katz/src/main/kotlin/katz/data/Reader.kt
Skipping default parameters only works for the last parameter position. Kleisli didn't follow this convention.
=> Fix position of default argument for monad implicit to align with Kotlin expectation

detekt.yml, katz/src/main/kotlin/katz/data/NonEmptyList.kt, katz/src/main/kotlin/katz/data/WriterT.kt, katz/src/main/kotlin/katz/instances/ByteMonoid.kt, katz/src/main/kotlin/katz/instances/DoubleMonoid.kt, katz/src/main/kotlin/katz/instances/FloatMonoid.kt, katz/src/main/kotlin/katz/instances/IntMonoid.kt, katz/src/main/kotlin/katz/instances/ListMonoid.kt, katz/src/main/kotlin/katz/instances/LongMonoid.kt, katz/src/main/kotlin/katz/instances/NonEmptyListMonad.kt, katz/src/main/kotlin/katz/instances/NonEmptyListSemigroup.kt, katz/src/main/kotlin/katz/instances/NumberSemigroup.kt, katz/src/main/kotlin/katz/instances/OptionMonoid.kt, katz/src/main/kotlin/katz/instances/ShortMonoid.kt, katz/src/main/kotlin/katz/instances/WriterTMonad.kt, katz/src/main/kotlin/katz/typeclasses/Applicative.kt, katz/src/test/kotlin/katz/data/NonEmptyListSemigroupTest.kt, katz/src/test/kotlin/katz/data/NumberMonoidTest.kt, katz/src/test/kotlin/katz/data/NumberSemigroupTest.kt, katz/src/test/kotlin/katz/data/OptionMonoidTest.kt, katz/src/test/kotlin/katz/data/WriterTTest.kt
=> Add implementation of WriterT and WriterTMonad

katz/src/main/kotlin/katz/data/Coproduct.kt, katz/src/main/kotlin/katz/data/Id.kt, katz/src/main/kotlin/katz/data/NonEmptyList.kt, katz/src/main/kotlin/katz/instances/CoproductComonad.kt, katz/src/main/kotlin/katz/instances/IdBimonad.kt, katz/src/main/kotlin/katz/instances/IdComonad.kt, katz/src/main/kotlin/katz/instances/IdMonad.kt, katz/src/main/kotlin/katz/instances/NonEmptyListBimonad.kt, katz/src/main/kotlin/katz/instances/NonEmptyListComonad.kt, katz/src/main/kotlin/katz/instances/NonEmptyListMonad.kt, katz/src/main/kotlin/katz/typeclasses/Applicative.kt, katz/src/main/kotlin/katz/typeclasses/Bimonad.kt, katz/src/main/kotlin/katz/typeclasses/Comonad.kt, katz/src/main/kotlin/katz/typeclasses/Monad.kt, katz/src/test/kotlin/katz/data/CoproductTest.kt, katz/src/test/kotlin/katz/data/IdTest.kt, katz/src/test/kotlin/katz/data/NonEmptyListTest.kt
=> Add comonadic comprehensions 

katz/src/main/kotlin/katz/free/CoYoneda.kt, katz/src/main/kotlin/katz/free/Free.kt, katz/src/main/kotlin/katz/free/Yoneda.kt, katz/src/main/kotlin/katz/instances/CoYonedaFunctor.kt, katz/src/main/kotlin/katz/instances/YonedaFunctor.kt, katz/src/test/kotlin/katz/free/CoYonedaTest.kt, katz/src/test/kotlin/katz/free/FreeTest.kt, katz/src/test/kotlin/katz/free/YonedaTest.kt
Add two central pieces to the Free machinery: Yoneda and CoYoneda. They include a minimal implementation, along with a Functor instance. I've also written a minimal test suite for each.
For consistency purposes I've swapped the parameter order in the Free class.
Closes #80
=> Add Yoneda and CoYoneda, along with their Functor instances

katz/src/main/kotlin/katz/data/Eval.kt, katz/src/main/kotlin/katz/free/Cofree.kt, katz/src/main/kotlin/katz/free/Free.kt, katz/src/main/kotlin/katz/instances/CofreeComonad.kt, katz/src/main/kotlin/katz/instances/EitherTMonad.kt, katz/src/main/kotlin/katz/instances/EvalMonad.kt, katz/src/main/kotlin/katz/instances/FreeMonad.kt, katz/src/main/kotlin/katz/instances/OptionTMonad.kt, katz/src/main/kotlin/katz/instances/OptionTraverse.kt, katz/src/main/kotlin/katz/instances/Traverse.kt, katz/src/main/kotlin/katz/instances/WriterTMonad.kt, katz/src/main/kotlin/katz/typeclasses/Applicative.kt, katz/src/main/kotlin/katz/typeclasses/Foldable.kt, katz/src/main/kotlin/katz/typeclasses/Traverse.kt, katz/src/test/kotlin/katz/UnitSpec.kt, katz/src/test/kotlin/katz/data/OptionTest.kt, katz/src/test/kotlin/katz/data/TryTest.kt, katz/src/test/kotlin/katz/free/CofreeTest.kt, katz/src/test/kotlin/katz/free/FreeTest.kt, katz/src/test/kotlin/katz/free/Interpreters.kt, katz/src/test/kotlin/katz/free/SideEffect.kt, reports/baseline.xml
=> Add Cofree comonad

build.gradle, gradle.properties, gradle/gradle-mvn-push.gradle, kategory/build.gradle, kategory/gradle.properties, settings.gradle
This will add seamless publishing for submodules as different artifacts in the same group ID (ehem, `kategory-rx` 😄  )
Followed style seen in other Open Source projects, and added Chris Bane's `gradle-mvn-push` gist for dealing with it. 
https://github.com/chrisbanes/gradle-mvn-push
Also removed a few license headers encountered since @ffgiraldez mentioned the agreement was to just use the `LICENSE` file.
=> Add Maven publish configurations

kategory/src/main/kotlin/kategory/instances/EitherMonad.kt, kategory/src/main/kotlin/kategory/typeclasses/ApplicativeError.kt, kategory/src/test/kotlin/kategory/data/EitherTest.kt, kategory/src/test/kotlin/kategory/data/TryTest.kt, kategory/src/test/kotlin/kategory/generators/Generators.kt, kategory/src/test/kotlin/kategory/laws/MonadErrorLaws.kt
Includes tests and instances for Try and Either
=> MonadError Laws

kategory/src/main/kotlin/kategory/instances/EvalEq.kt, kategory/src/main/kotlin/kategory/instances/FreeEq.kt, kategory/src/main/kotlin/kategory/instances/Function0Eq.kt, kategory/src/main/kotlin/kategory/instances/IOEq.kt, kategory/src/main/kotlin/kategory/typeclasses/Eq.kt, kategory/src/test/kotlin/kategory/data/EitherTTest.kt, kategory/src/test/kotlin/kategory/data/EitherTest.kt, kategory/src/test/kotlin/kategory/data/EvalTest.kt, kategory/src/test/kotlin/kategory/data/Function0Test.kt, kategory/src/test/kotlin/kategory/data/IdTest.kt, kategory/src/test/kotlin/kategory/data/IorTest.kt, kategory/src/test/kotlin/kategory/data/NonEmptyListTest.kt, kategory/src/test/kotlin/kategory/data/OptionTTest.kt, kategory/src/test/kotlin/kategory/data/OptionTest.kt, kategory/src/test/kotlin/kategory/data/TryTest.kt, kategory/src/test/kotlin/kategory/data/ValidatedTest.kt, kategory/src/test/kotlin/kategory/data/WriterTTest.kt, kategory/src/test/kotlin/kategory/effects/IOTest.kt, kategory/src/test/kotlin/kategory/free/FreeTest.kt, kategory/src/test/kotlin/kategory/laws/FunctorLaws.kt, kategory/src/test/kotlin/kategory/laws/Law.kt
=> Extract common implementations of Eq

kategory/src/main/kotlin/kategory/instances/Traverse.kt, kategory/src/main/kotlin/kategory/typeclasses/Foldable.kt, kategory/src/test/kotlin/kategory/laws/FoldableLaws.kt
This PR converts some methods that require typeclass instances into inline extension functions that allow for implicit lookup using our helpers.
=> Add instance lookup for Foldable and Traverse methods

README.md, gradle.properties
Added:
- StateT type
- Discipline
- IO Monad
- Kelisi instances
- Test laws 
Changed:
Removed:
- Remove remaining katz references
Fixed:
- Fix usage in Android API below 19 
Full list of closed PRs:
#122 MonadError Laws [by @raulraja]
#65 Create discipline [by @JMPergar]
#112 Typeclasses laws [by @raulraja]
#116 Rename test folder from katz to kategory [by @Guardiola31337, @ffgiraldez]
#117 Remove katz directory [by @raulraja, @pakoito]
#119 fix usage on android API <19 [by @ffgiraldez, @pakoito]
#120 Add fixes to Monads found by new Law checks [by @pakoito, @raulraja]
#121 Address PR changes in Eq [by @pakoito]
#109 Add IO Monad [by @pakoito, @ffgiraldez]
#123 Add instances to Kleisli [by @pakoito]
#124 Add tests for StateT
#125 Extract common implementations of Eq [by @pakoito]
#126 Fix …
=> Release 0.3.4

kategory/src/main/kotlin/kategory/arrow/Function0.kt, kategory/src/main/kotlin/kategory/arrow/Function1.kt, kategory/src/main/kotlin/kategory/arrow/FunctionBijections.kt, kategory/src/main/kotlin/kategory/data/Composed.kt, kategory/src/main/kotlin/kategory/instances/Function1Instances.kt, kategory/src/main/kotlin/kategory/instances/TryInstances.kt, kategory/src/test/kotlin/kategory/data/Function1Test.kt
Another breakthrough in language limitations. This PR adds the first kind projection using skolemization!
The PR adds a HK wrapper for Functions with 1 parameter, along with an instance of monad() and monadReader()
For a background on the buzzwords, check these links:
https://github.com/non/kind-projector
https://gist.github.com/jdegoes/97459c0045f373f4eaf126998d8f65dc#skolemization
=> Add Function1

kategory/src/main/kotlin/kategory/typeclasses/Comonad.kt, kategory/src/test/kotlin/kategory/data/CoproductTest.kt, kategory/src/test/kotlin/kategory/data/Function0Test.kt, kategory/src/test/kotlin/kategory/data/IdTest.kt, kategory/src/test/kotlin/kategory/data/NonEmptyListTest.kt, kategory/src/test/kotlin/kategory/free/CofreeTest.kt
Cobinding doesn't need a yields(), which was only a passthrough function to mimic Monad#binding API.
=> Remove yields() from cobinding

kategory/src/main/kotlin/kategory/arrow/Function0.kt, kategory/src/main/kotlin/kategory/arrow/Function1.kt, kategory/src/main/kotlin/kategory/arrow/FunctionBijections.kt, kategory/src/main/kotlin/kategory/instances/Function1Instances.kt, kategory/src/test/kotlin/kategory/data/Function1Test.kt
After a chat with @raulraja I realized I had overblown the implementation of Function1. There was a simpler solution all along using extension functions. Who would have thought.
This PR adds a new function invoke() that's an alias for ev().invoke(). This fixes an existing problem with the inference for ev() because one of the parameters couldn't be decided by the compiler and had to be injected manually.
=> Simplify Function0 and Function1 

kategory/src/main/kotlin/kategory/arrow/Function0.kt, kategory/src/main/kotlin/kategory/arrow/Function1.kt, kategory/src/main/kotlin/kategory/instances/Function1Instances.kt, kategory/src/test/kotlin/kategory/data/Function0Test.kt, kategory/src/test/kotlin/kategory/data/Function1Test.kt
Simple change to add invoke as operator rather than a function, and replacing all instances where it made sense.
=> Replace invoke() extfun with operator invoke() extfun

kategory/src/main/kotlin/kategory/arrow/PartialFunction.kt, kategory/src/main/kotlin/kategory/instances/IterableInstances.kt, kategory/src/test/kotlin/kategory/data/IterableTests.kt, kategory/src/test/kotlin/kategory/data/PartialFunctionTests.kt, kategory/src/test/kotlin/kategory/data/StateTTests.kt, kategory/src/test/kotlin/kategory/data/StateTests.kt
The following PR brings supports to PartialFunctions for Kotlin through Kategory.
It includes syntax for `match` and `case` and extensions for `Iterable.collect` so they work like in Scala.
```kotlin
listOf("1", Option.Some(1), 1).collect(
case(typeOf<String>() then { (it).toInt() }),
case(typeOf<Option.Some<Int>>() then { it.value }),
case(typeOf<Int>() then { it })
) shouldBe listOf(1, 1, 1)
```
```kotlin
listOf(1).collect(
case(typeOf<String>() then { (it).toInt() })
) shouldBe emptyList<Int>()
```
```kotlin
val result: Int = match("1")(
case(typeOf<String>() then { (it).toInt() }),
case(typeOf<Option.Some<Int>>() then { it.value }),
case(typeOf<Int>() then { it }),
default = { it.toInt() }
)
result shouldBe 1
```
=> PartialFunction + match(case ..) statements

kategory/src/main/kotlin/kategory/data/Either.kt, kategory/src/main/kotlin/kategory/data/Option.kt, kategory/src/main/kotlin/kategory/instances/EitherInstances.kt, kategory/src/main/kotlin/kategory/instances/EitherTInstances.kt, kategory/src/main/kotlin/kategory/instances/IdInstances.kt, kategory/src/main/kotlin/kategory/instances/NonEmptyListInstances.kt, kategory/src/main/kotlin/kategory/instances/WriterTInstances.kt
By using a smart constructor, the problem where the IDE couldn't keep up with inference of L or R generic due to the use of None should be fixed.
=> Either generics for Left and Right now include both sides

kategory/src/main/kotlin/kategory/free/CoYoneda.kt, kategory/src/main/kotlin/kategory/free/Yoneda.kt, kategory/src/test/kotlin/kategory/free/CoYonedaTest.kt, kategory/src/test/kotlin/kategory/free/YonedaTest.kt, kategory/src/test/kotlin/kategory/laws/FunctorLaws.kt
This PR introduces the stack-safe implementation of CoYoneda that's also used in cats. Thanks to @edmundnoble for the implementation.
At higher numbers for the test (i.e. 20k), it causes a StackOverflow due to some function checks by JetBrains. See the following issue until it's fixed:  https://youtrack.jetbrains.com/issue/KT-19499
Closes #167
=> Stack-safe CoYoneda

README.md, build.gradle, kategory/build.gradle
Now that all binaries are mirrored in jcenter, that's the only one we need.
Removed as well redundant dependencies in kategory/build.gradle
=> Remove kategory bintray repository in favour of jcenter

kategory/src/main/kotlin/kategory/data/Composed.kt, kategory/src/main/kotlin/kategory/data/Reader.kt, kategory/src/test/kotlin/kategory/laws/TraverseLaws.kt
This PR touches the Composed file to add ComposedApplicative. With ComposedApplicative the Traverse law for sequential composition can be written.
With apologies to @Guardiola31337 for the disruption.
=> Add Traverse law for Sequential Composition: required ComposedFunctor and ComposedApplicative

kategory/src/main/kotlin/kategory/data/Const.kt, kategory/src/main/kotlin/kategory/data/Either.kt, kategory/src/main/kotlin/kategory/instances/ConstInstances.kt, kategory/src/test/kotlin/kategory/data/ConstTest.kt, kategory/src/test/kotlin/kategory/laws/TraverseLaws.kt
Along with #179, these add the last two missing laws for traverse compared to Cats.
It required porting Const, which is a nice HK2 whose bias is towards a non-existing value Tag.
=> Add Traverse law for FoldMap derived: required Const

kategory/src/main/kotlin/kategory/free/FreeApplicative.kt
Now that Const is in the repo via #180, the missing method in FreeApplicative can be added.
Please note that it requires to have merged #179 and #180 beforehand.
Closes #136
=> Add analyze to FreeApplicative

kategory/src/main/kotlin/kategory/data/Eval.kt
Closes #183 
I don't know what I was thinking when I wrote this implementation. It used to work correctly, and it still does, all tests pass etc.
WTF: https://github.com/kategory/kategory/commit/7da55a31ec5d11db9616fbedc9d378b252e10ec8
=> Restore tailrec implementation of Eval#collapse

LICENSE, kategory-effects/src/main/kotlin/kategory/effects/data/IO.kt, kategory-effects/src/main/kotlin/kategory/effects/instances/IOInstances.kt, kategory-effects/src/main/kotlin/kategory/effects/typeclass/Async.kt, kategory-effects/src/test/kotlin/kategory/effects/data/IOTest.kt, kategory-effects/src/test/kotlin/kategory/effects/laws/AsyncLaws.kt, reports/baseline.xml
This PR add AsyncContext based off Freestyle's. It includes a couple of constructor helpers to be used in comprehensions, along with basic laws.
=> Add AsyncContext typeclass

kategory-test/src/main/kotlin/kategory/concurrency/CoroutineDispatchers.kt, kategory-test/src/main/kotlin/kategory/laws/Law.kt, kategory-test/src/main/kotlin/kategory/laws/MonadLaws.kt, kategory-test/src/main/kotlin/kategory/laws/TraverseLaws.kt, kategory/src/main/kotlin/kategory/typeclasses/Monad.kt, reports/baseline.xml
This PR adds support for passing a CoroutineContext to both `binding` and `bindInContext`, which would then execute the block in that specific Context.
I've added a law to test it, along with some helpers to run resources-bound tests.  
Closes #197
=> Add support for CoroutineContext to execute binding in separate threads

kategory/src/main/kotlin/kategory/data/ListKW.kt, kategory/src/main/kotlin/kategory/instances/ListKWInstances.kt
Removes `ListKW` method delegation boilerplate using Kotlin's class delegation machinery.
This technique can be used for other datatypes in the std lib to avoid manually implementing all combinators.
`@higherkind data class ListKW<A> constructor(val list: List<A>) : ListKWKind<A>, List<A> by list { .. }`
This means that `ListKW<A>` is now a `List<A>` and inherits all public methods as well making them visible. Whenever a concrete `ListKW<A>` is required one can just invoke `list.k()` to rewrap the instance.
This technique may be used when implementing `Set` wrappers and others.
=> Remove `ListKW` boilerplate

kategory-test/src/main/kotlin/kategory/generators/Generators.kt, kategory/src/main/kotlin/kategory/data/WriterT.kt, kategory/src/main/kotlin/kategory/instances/WriterTInstances.kt, kategory/src/main/kotlin/kategory/typeclasses/MonadWriter.kt, kategory/src/test/kotlin/kategory/data/WriterTTest.kt, kategory/src/test/kotlin/kategory/laws/MonadWriterLaws.kt
Fixes #163
**Disclaimer:** `MonadWriter` was moved to `FunctorListen` inside `cats-mtl` module. The reason to keep implementing `MonadWriter` here is that I think we should definitely keep "old" constructs (the one valids until cats `pre-1.0.0`) for the time being, until we have a first release. I would iterate towards `kategory-mtl` module with the same renaming / refactor iterations applied to cats probably after release, to avoid more noise.
=> MonadWriter

kategory/src/main/kotlin/kategory/typeclasses/Monad.kt
Adds extra methods for Monad as requested in https://github.com/kategory/kategory/issues/69#issuecomment-303850005
=> Add followedBy, forEffect, mproduct and ifM

kategory-test/src/main/kotlin/kategory/generators/Generators.kt, kategory-test/src/main/kotlin/kategory/laws/FunctorFilterLaws.kt, kategory/src/main/kotlin/kategory/arrow/Function1.kt, kategory/src/main/kotlin/kategory/arrow/PartialFunction.kt, kategory/src/main/kotlin/kategory/data/Composed.kt, kategory/src/main/kotlin/kategory/data/OptionT.kt, kategory/src/main/kotlin/kategory/instances/OptionTInstances.kt, kategory/src/main/kotlin/kategory/typeclasses/FunctorFilter.kt, kategory/src/test/kotlin/kategory/data/OptionTTest.kt
Fixes: #223 
* Added `FunctorFilter`
* Added `FunctorFilterLaws`
* Added `ComposedFunctorFilter` and `OptionTFunctor` `FunctorFilter` instances.
* Tested laws using `OptionTFunctor`.
=> Add FunctorFilter

kategory/src/main/kotlin/kategory/typeclasses/Monad.kt
Change for marginal API improvement:
```
val M = Kleisli.monad()
M.binding {
val result = pure(Id(1)).andThen { pure(Id(it++)) }
yields(result)
}
```
=> Make Continuations implement Monad through delegation

kategory/src/main/kotlin/kategory/data/SequenceKW.kt, kategory/src/main/kotlin/kategory/instances/SequenceKWMonoid.kt, kategory/src/test/kotlin/kategory/data/SequenceKWTest.kt
=> Add wrapper and instances for Sequence

kategory-optics/src/main/kotlin/kategory/optics/Lens.kt, kategory-optics/src/main/kotlin/kategory/optics/Prism.kt, kategory-optics/src/test/kotlin/kategory/optics/LensLaws.kt, kategory-optics/src/test/kotlin/kategory/optics/LensTest.kt, kategory-optics/src/test/kotlin/kategory/optics/PrismLaws.kt, kategory-optics/src/test/kotlin/kategory/optics/PrismTest.kt
Added initial prism impl with laws
Changed Pair -> Tuple2 
Moved to package kategory.optics
=> Initial prism impl

kategory-annotations-processor/build.gradle, kategory-annotations-processor/src/main/java/kategory/common/messager/MessagerExtensions.kt, kategory-annotations-processor/src/main/java/kategory/common/utils/AbstractProcessor.kt, kategory-annotations-processor/src/main/java/kategory/common/utils/ProcessorUtils.kt, kategory-annotations-processor/src/main/java/kategory/implicits/ImplicitsFileGenerator.kt
I'm preparing to finally release the `kotlin-metadata` library so I renamed a few things and moved some utils form kategory to the library, which simplifies the code a bit.
I hope I didn't break anything!
=> Update kotlin-metadata library from 1.1.0 to 1.2.0

kategory-core/src/test/kotlin/kategory/data/ListKWTest.kt
=> Add lacking laws test for monadCombine ListKW instance

README.md, build.gradle, gradle.properties
- `kategory` version `0.3.8` is now available in jcenter 🎉
- Bumps version numbers to `0.3.9-SNAPSHOT`
- Fixes the `archivesBaseName` so it takes the `POM_ARTIFACT_ID` instead of the `project.name` fixing the artifact naming not working properly in `gradle-bintray-plugin` when releasing
- Makes obsolete https://github.com/kategory/kategory/pull/279
- Still remains adding some patchnotes to the release https://github.com/kategory/kategory/releases/tag/0.3.8 👀 https://github.com/kategory/kategory/pull/279
👀 @JorgeCastilloPrz @wiyarmir @pakoito @raulraja
=> Release version 0.3.8

kategory-core/src/main/kotlin/kategory/data/Reader.kt, kategory-core/src/test/kotlin/kategory/data/ReaderTest.kt
The new way we have to pass monads / functors / applicatives etc to HKs is by function call and not as class properties is causing me some issues on trying to call `map` , `flatMap` etc methods over the `Reader`. The problems is that I can't call those methods without passing explicit instances of `functor`, `monad` etc.
[Here you can have a look at the problem](https://github.com/JorgeCastilloPrz/KotlinAndroidFunctional/blob/master/nested-monads/src/main/java/com/github/jorgecastillo/kotlinandroid/presentation/SuperHeroesPresentation.kt#L43)
Since the `Reader` is just an alias for `Kleisli<IdHK, D, A>`, I added some utility methods to the aliased type just when F is `IdHK`.
=> Add ReaderT extension functions to forward to Kleisli using IdHK

kategory-optics/src/main/kotlin/kategory/optics/Iso.kt, kategory-optics/src/main/kotlin/kategory/optics/Lens.kt, kategory-optics/src/main/kotlin/kategory/optics/Optional.kt, kategory-optics/src/main/kotlin/kategory/optics/Prism.kt, kategory-optics/src/test/kotlin/kategory/optics/IsoTest.kt, kategory-optics/src/test/kotlin/kategory/optics/LensTest.kt, kategory-optics/src/test/kotlin/kategory/optics/OptionalTest.kt, kategory-optics/src/test/kotlin/kategory/optics/TestDomain.kt, kategory-test/src/main/kotlin/kategory/laws/IsoLaws.kt, kategory-test/src/main/kotlin/kategory/laws/LensLaws.kt, kategory-test/src/main/kotlin/kategory/laws/OptionalLaws.kt, kategory-test/src/main/kotlin/kategory/laws/PrismLaws.kt
In OptionalLaws I made an non-reusable First tag. This could be replaced with a type tagging in Kategory. You don't get the same nice syntax as in Scala `Option<A> @@  First` but an type alias could always close the gap if required. Thoughts?
```
data class Tagged<A, T>(val value: A) : ReadOnlyProperty<Any?, A> {
/**
* Auto unwrapping by delegation
*/
override fun getValue(thisRef: Any?, property: KProperty<*>): A = value
}
fun <A, T> A.tag(): Tagged<A, T> = Tagged(this)
sealed class UserToken
data class User(val name: String, val token: Tagged<String, UserToken>)
fun main(args: Array<String>) {
val taggedString: Tagged<String, UserToken> = "someUserToken".tag()
println("I was manually unwrapped: ${taggedString.value}")
val string by taggedString
println("I was auto unwrapped: $string") …
```
=> Optional optic

kategory-docs/docs/docs/patterns/errorhandling/README.md
- add target and nuke parameters to launch
- fix field and `.binding` call in attack
- add type parameters to aim, arm, launch calls within attack
- typos
Relates to https://github.com/kategory/kategory/issues/359
=> Fix Error Handling MonadError doc examples

kategory-annotations-processor/src/main/java/kategory/optics/IsosFileGenerator.kt, kategory-annotations-processor/src/main/java/kategory/optics/LensesFileGenerator.kt, kategory-annotations-processor/src/main/java/kategory/optics/PrismsFileGenerator.kt
* Small fix for data classes with back ticked property names.
* Change generated names for Isos, Prisms and lenses to camelcase instead of lowercase.
=> Fix for escaped property names

deploy-scripts/deploy_release.sh, deploy-scripts/deploy_snapshot.sh
They now support multiple numbers…in the version and not any character in between the version numbers
=> Updated regex in the build scripts

kategory-docs/docs/docs/datatypes/validated/README.md
- remove all caps on headers
- change [] to <> for non code generic examples
- consistent spacing of `fun <A> myFunc`
- typos
=> Update Validated docs

kategory-effects/src/main/kotlin/kategory/effects/typeclass/Async.kt
There's already a copy on MonadErrorCancellableContinuations: https://github.com/kategory/kategory/blob/master/kategory-effects/src/main/kotlin/kategory/effects/typeclass/MonadErrorCancellableContinuations.kt#L75-L79. Oopsie.
=> Remove duplicated cancellable binding

kategory-annotations-processor/src/main/java/kategory/instances/InstanceFileGenerator.kt
Closes #375 
```Kotlin
@instance(AsyncResult::class)
interface AsyncResultApplicativeInstance<D: SuperHeroesContext> : AsyncResultFunctorInstance<D>, Applicative<AsyncResultKindPartial<D>>
```
generates
```Kotlin
package kategory.instances
object AsyncResultFunctorInstanceImplicits {
@JvmStatic fun <D> instance(): AsyncResultFunctorInstance<D> where D : kategory.instances.SuperHeroesContext =
object : AsyncResultFunctorInstance<D> {
}
}
fun <D> kategory.instances.AsyncResult.Companion.functor(): AsyncResultFunctorInstance<D> where D : kategory.instances.SuperHeroesContext =
AsyncResultFunctorInstanceImplicits.instance()
```
=> Support type arg bounds in @instance

kategory-annotations-processor/src/main/java/kategory/common/utils/ProcessorUtils.kt, kategory-annotations-processor/src/main/java/kategory/higherkinds/HigherKindsFileGenerator.kt, kategory-annotations-processor/src/main/java/kategory/instances/InstanceFileGenerator.kt
Closes #374
```Kotlin
@higherkind
class AsyncResult<D: SuperHeroesContext, A>(val value: Result<D, A>) : AsyncResultKind<D, A>
```
generates
```Kotlin
class AsyncResultHK private constructor()
typealias AsyncResultKind<D, A> = kategory.HK2<AsyncResultHK, D, A>
typealias AsyncResultKindPartial<D> = kategory.HK<AsyncResultHK, D>
@Suppress("UNCHECKED_CAST")
inline fun <D, A> AsyncResultKind<D, A>.ev(): AsyncResult<D, A> where D : kategory.SuperHeroesContext =
this as AsyncResult<D, A>
```
Uses the same mechanism as #410
=> Support type arg bounds in @higherkind

kategory-annotations-processor/src/main/java/kategory/instances/InstanceFileGenerator.kt
Instancing Eval creates the following code:
```Kotlin
fun <A> kategory.Eval.Companion.typeclass(TC: Typeclass<A>, dummy: Unit = Unit): EvalTypeclassInstance<A> =
EvalTypeclassInstanceImplicits.instance(TC)
```
However, this code is invalid. The problem is in `dummy: Unit = Unit`. While the first Unit gets resolved to kotlin.Unit, the second gets resolved to kategory.Eval.Companion.Unit. This causes compilation to fail.
This solution is to generate this code instead:
```Kotlin
fun <A> kategory.Eval.Companion.typeclass(TC: Typeclass<A>, dummy: kotlin.Unit = kotlin.Unit): EvalTypeclassInstance<A> =
EvalTypeclassInstanceImplicits.instance(TC)
```
Which prevents it from failing if the Companion has a property or local class called Unit (as is the case with Eval).
=> Fix @instance code generation when Companion has members named Unit

kategory-annotations/src/main/java/kategory/Typeclass.kt, kategory-core/src/main/kotlin/kategory/data/Validated.kt, kategory-core/src/main/kotlin/kategory/instances/ValidatedInstances.kt, kategory-core/src/test/kotlin/kategory/data/ValidatedTest.kt, kategory-docs/docs/docs/datatypes/ior/README.md
* Some nits in the Typeclass file
* Added a couple of tests for Validated's `combineK`
* Added `Validated.toIor`
* Added a vanilla `combine` function that performs a slightly different combination than `combineK`, based on [cats' version](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/data/Validated.scala#L266).
@kategory/maintainers Please take a look and let me know if I messed it up 😆
=> Validated fixes

README.md, gradle.properties
* Instances for Eval
* Iso instances
* Improved kategory processor (Iso, higherkind & instance)
* Eq instances
* Validated fixes
* Corrected Semigroup & Monoid API
=> Release 0.3.11

gradle/gradle-mvn-push.gradle
Only snapshots build should be at  oss.jfrog.org, modify default release URL to point to Bintray organization project.
With this change, I was able to upload and publish to Bintray from a local machine, and maybe also work in Travis-CI when detecting a release build.
The only behaviour it's some modules that do not have real artifact appears in Bintray:
* kategory-docs
* kategory-effects-test
* kategory-test
=> Fix release upload archives

kategory-core/src/main/kotlin/kategory/free/Coyoneda.kt, kategory-core/src/main/kotlin/kategory/free/Yoneda.kt, kategory-core/src/test/kotlin/kategory/free/CoYonedaTest.kt, kategory-core/src/test/kotlin/kategory/free/YonedaTest.kt
Renamed `apply` function to `operator invoke` for `Yoneda` and `Coyoneda`. Also updated tests. Build is passing in my machine
There is another `unsafeApply` in `Coyoneda` that I haven't modified.
=> Fix #459 - rename apply to operator invoke

kategory-docs/build.gradle
Currently the classpath is printed in every gradle configuration phase. `<<` or `doLast` would fix that.
=> Print classpath as task not config

README.md
Gradle had problems finding `kategory-effects` and `kategory-optics` artifacts.
=> (fix) Readme: Wrong URL to Maven repository for Kategory.

deploy-scripts/deploy.sh
Release deployment is failing 👀
```
0.01s$ ./deploy-scripts/deploy.sh
Branch 'master'
./deploy-scripts/deploy.sh: line 10: [: ~=: binary operator expected
./deploy-scripts/deploy.sh: line 12: [: =~: binary operator expected
```
- This PR addresses ☝️
👀 @pablisco
=> Fix release deployment script

kategory-core/src/main/kotlin/kategory/data/Try.kt, kategory-effects-rx2/src/main/kotlin/kategory/effects/data/FlowableKW.kt, kategory-effects-rx2/src/main/kotlin/kategory/effects/data/ObservableKW.kt, kategory-effects-rx2/src/test/kotlin/kategory/effects/data/FlowableKWTests.kt, kategory-effects-rx2/src/test/kotlin/kategory/effects/data/ObservableKWTests.kt, kategory-test/src/main/kotlin/kategory/laws/MonadLaws.kt
I realized while working on https://github.com/kategory/kategory/pull/475 that stackSafety and stackSafeComprehensions weren't being checked by the laws. Let's fix that.
=> Add fix to 3 MonadLaws that were not executing their clauses

kategory-core/src/main/kotlin/kategory/data/State.kt, kategory-core/src/main/kotlin/kategory/data/StateT.kt, kategory-docs/docs/docs/datatypes/state/README.md, kategory-docs/docs/docs/datatypes/statet/README.md, kategory-docs/docs/docs/integrations/kotlinxcoroutines/README.md
As discussed in https://github.com/kategory/kategory/pull/457 update to State to improve API.
As you can see to the changes in the docs nothing broke of the existing API (`StateT.monad<IdHK, Stack>().binding` is also still valid).
Now you can specify return types as `State<S, A>` instead of `StateT<IdHK, S, A>` and you can use `State()` to access the methods that are defined on `StateT.Companion` with `F` fixed to `IdHK`.
If this is approved I will do the same for `Reader`
=> State API update

kategory-annotations-processor/src/main/java/kategory/higherkinds/HigherKindsFileGenerator.kt
Currently, the `@higherkind` annotation generates code that creates the following warning: 
```Expected performance impact of inlining ... can be insignificant. Inlining works best for functions with lambda parameters```
This PR fixes this by suppressing that warning in the generated code.
=> Suppress higher kind inline warnings

README.md, deploy-scripts/deploy_release.sh, gradle.properties
=> Release 0.4.0

build.gradle, kategory-docs/build.gradle
- The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the method ConfigurableReport.setDestination(File) instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
=> fix gradle deprecation warnings

deploy-scripts/deploy_common.sh
Currently, the travis ci after success step is failing: 
> Failed release deployment: wrong repository. Expected 'arrow/arrow' but was 'arrow-kt/arrow'.
let's fix the slug in order to be able to release again.
=> fix slug in deploy scripts

arrow-core/src/main/kotlin/arrow/core/Eval.kt
Currently, Eval.Compute.value is implemented using a mutable reference to an immutable list. This PR replaces it with a mutable reference to a mutable list, which greatly increases performance.
Tested using the following factorial implementation:
```kotlin
fun factorial(i: Int): Eval<Int> = when (i) {
0 -> Eval.One
else -> Eval.defer { factorial(i - 1) }.map { it * i }
}
```
With the old implementation, factorial 0..2000 takes ~13 seconds on my laptop. With the new implementation, it takes ~0.5 seconds.
=> Improve Eval.Compute.value performance

arrow-effects/src/main/kotlin/arrow/effects/data/Duration.kt, arrow-effects/src/test/kotlin/arrow/effects/data/DurationTest.kt, arrow-test/src/main/kotlin/arrow/test/generators/Generators.kt
Overloading the * operator to multiply a duration. Not sure it is really relevant to have it in Arrow though.
=> Adding utility method to Duration

arrow-annotations-processor/src/main/java/arrow/optics/LensesFileGenerator.kt
So we can generate lenses for classes with the same name in different packages.
=> Include package name for generated lens .kt files

arrow-effects-rx2/src/test/kotlin/arrow/effects/data/FlowableKWTests.kt, arrow-effects-rx2/src/test/kotlin/arrow/effects/data/ObservableKWTests.kt
=> Use newThread scheduler to avoid flaky tests on single-core CI machines

arrow-core/src/main/kotlin/arrow/core/Either.kt
I removed the private property dummy from Left and Right, I do not really see why they would be required.
=> remove private val dummy from Left and Right

arrow-core/src/main/kotlin/arrow/core/Either.kt, arrow-data/src/test/kotlin/arrow/data/EitherTest.kt, arrow-docs/docs/docs/datatypes/either/README.md
This mimic the [Scala stdlib](https://www.scala-lang.org/api/current/scala/util/Either$.html#cond[A,B](test:Boolean,right:=%3EB,left:=%3EA):scala.util.Either[A,B]). 
Shall we make the t parameter a thunk too ?
=> Adding a cond method on Either companion object

arrow-docs/docs/docs/README.md
According to the info added in the [readme file](https://github.com/arrow-kt/arrow/commit/48d8d762b598ff529bb6ad4114f794ea5b5d1077#diff-04c6e90faac2675aa89e2176d2eec7d8), the docs needed to be updated as well.
=> Added jcenter as repository

arrow-annotations-processor/build.gradle
without this change the build just fails with a NullPointerException.
=> improve error message on incompatible jdk version

arrow-core/build.gradle, arrow-data/build.gradle, arrow-effects-kotlinx-coroutines/build.gradle, arrow-effects-rx2/build.gradle, arrow-effects/build.gradle, arrow-examples/build.gradle, arrow-free/build.gradle, arrow-instances/build.gradle, arrow-kindedj/build.gradle, arrow-mtl/build.gradle, arrow-syntax/build.gradle, arrow-typeclasses/build.gradle, arrow-validation/build.gradle
This is a followup to the missed libraries in ce99db67b595314942d585ef6aec3d27eef2e1c5.
See https://kotlinlang.org/docs/reference/whatsnew12.html#kotlin-standard-library-artifacts-and-split-packages
=> Replace rest of usages of `kotlin-stdlib-jre7` with `kotlin-stdlib-jdk7`

arrow-docs/docs/docs/datatypes/either/README.md, arrow-docs/docs/docs/datatypes/eithert/README.md, arrow-docs/docs/docs/datatypes/ior/README.md, arrow-docs/docs/docs/datatypes/option/README.md, arrow-docs/docs/docs/datatypes/optiont/README.md, arrow-docs/docs/docs/datatypes/sequencekw/README.md, arrow-docs/docs/docs/datatypes/state/README.md, arrow-docs/docs/docs/datatypes/statet/README.md, arrow-docs/docs/docs/datatypes/try/README.md, arrow-docs/docs/docs/effects/async/README.md, arrow-docs/docs/docs/effects/io/README.md, arrow-docs/docs/docs/effects/monadsuspend/README.md, arrow-docs/docs/docs/integrations/kotlinxcoroutines/README.md, arrow-docs/docs/docs/integrations/rx2/README.md, arrow-docs/docs/docs/patterns/errorhandling/README.md, arrow-docs/docs/docs/patterns/monadcomprehensions/README.md, arrow-docs/docs/docs/typeclasses/monadfilter/README.md, arrow-effects/src/main/kotlin/arrow/effects/MonadSuspend.kt, arrow-free/src/main/kotlin/arrow/free/StackSafeMonadContinuations.kt, arrow-mtl/src/main/kotlin/arrow/mtl/MonadFilter.kt, arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Monad.kt, arrow-typeclasses/src/main/kotlin/arrow/typeclasses/MonadContinuations.kt, arrow-typeclasses/src/main/kotlin/arrow/typeclasses/MonadError.kt
This PR removes the need to use `yields()` in comprehensions to form a correct value. Instead we take the return value from the block and lift it using `pure()`.
A deprecation path has been added for yields() that replaces the call with the first parameter, as users were not meant to use the return value anyway.
=> Change monad comprehensions to accept any return value

arrow-annotations-processor/src/main/java/arrow/tc/TypeclassFileGenerator.kt
For a type class such as:
```kotlin
@typeclass
interface Functor<F> : TC {
fun <A, B> map(fa: HK<F, A>, f: (A) -> B): HK<F, B>
fun <A, B> lift(f: (A) -> B): (HK<F, A>) -> HK<F, B> =
{ fa: HK<F, A> ->
map(fa, f)
}
fun <A> void(fa: HK<F, A>): HK<F, Unit> = map(fa, { _ -> Unit })
fun <A, B> fproduct(fa: HK<F, A>, f: (A) -> B): HK<F, Tuple2<A, B>> = map(fa, { a -> Tuple2(a, f(a)) })
fun <A, B> `as`(fa: HK<F, A>, b: B): HK<F, B> = map(fa, { _ -> b })
fun <A, B> tupleLeft(fa: HK<F, A>, b: B): HK<F, Tuple2<B, A>> = map(fa, { a -> Tuple2(b, a) })
fun <A, B> tupleRight(fa: HK<F, A>, b: B): HK<F, Tuple2<A, B>> = map(fa, { a -> Tuple2(a, b) })
}
```
It generates all it's syntax facilities:
```kotlin
interface FunctorSyntax<F> {
fun functor(): Functor<F>
fun <A, B> arrow.HK<F, A>.`as`(b: B): …
```
=> Auto-generate Syntax for Type Classes

arrow-annotations-processor/src/main/java/arrow/tc/TypeclassFileGenerator.kt
This makes the encoding on Tagless classes easier by activating the syntax based on the injected property:
```kotlin
class Service1<F> @Inject constructor(
override val functor: Functor<F> //here functor is provided to `FunctorSyntax` via override
) : FunctorSyntax<F> {
fun s1(a: HK<F, Int>): HK<F, Int> = a.map { it + 1 }
}
```
This PR also solves erasure issues related to classes in cases such as `Functor#map` vs `HK<F, A>.map` generated extension by providing a dummy extra argument where it's definition after erasure is no longer equivalent.
=> Use `val` instead of `fun` in syntax generation for type class syntax

arrow-effects-rx2/src/test/kotlin/arrow/effects/ObservableKWTests.kt
It's still logged, let's see if it pops up again.
=> Fix the Observable tests being flaky on CI

arrow-annotations-processor/src/main/java/arrow/tc/TypeclassFileGenerator.kt, arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Monoid.kt
Auto derived from the Monoid syntax:
```kotlin
interface MonoidSyntax<A> {
val monoid: Monoid<A>
fun kotlin.collections.Collection<A>.`combineAll`(dummy: Unit = Unit): A =
monoid.`combineAll`(this)
fun `empty`(): A =
monoid.`empty`()
}
```
=> Generate all static and extensions methods in Type class Syntax

modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md
I had given a presentation on various data types and type classes at the Brooklyn Kotlin Meetup. As requested by @ffgiraldez, I am opening this PR to add a link to my presentation in the blogs section. Thanks!
=> Add link to Functional Programming in Arrow Presentation

.travis.yml, build.gradle, modules/docs/arrow-docs/build.gradle, modules/docs/arrow-docs/docs/docs/optics/each/README.md, settings.gradle.kts
- Bumps ank version to `0.6.2-SNAPSHOT` after the renamening https://github.com/arrow-kt/arrow/pull/671
👀 @pakoito @raulraja
=> Bump ank version to 0.6.2-SNAPSHOT after the renamening

modules/core/arrow-annotations-processor/src/main/java/arrow/common/utils/ProcessorUtils.kt, modules/core/arrow-annotations-processor/src/main/java/arrow/instances/InstanceProcessor.kt, modules/core/arrow-annotations-processor/src/main/java/arrow/tc/AnnotatedTypeclass.kt, modules/core/arrow-annotations-processor/src/main/java/arrow/tc/TypeclassFileGenerator.kt, modules/core/arrow-annotations-processor/src/main/java/arrow/tc/TypeclassProcessor.kt, modules/core/arrow-annotations/src/main/java/arrow/typeclass.kt, modules/dagger/arrow-dagger-effects/src/main/kotlin/arrow.dagger.effects.instances/syntax.kt, modules/dagger/arrow-dagger/src/main/kotlin/arrow/dagger/instances/syntax.kt, modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md, modules/effects/arrow-effects/src/main/kotlin/arrow/effects/MonadSuspend.kt
`@typeclass` can now derive syntax instances that extend each other to eliminate all implementation boilerplate. This PR also include the relevant Dagger classes that can be directly injected. Docs will come after testing in a real project as I'm still adjusting the flexibility of this technique.
Auto generated from the `Applicative` Type class:
```kotlin
interface ApplicativeSyntax<F> : arrow.typeclasses.FunctorSyntax<F> {
fun applicative(): Applicative<F>
override fun functor() : arrow.typeclasses.Functor <F> = applicative()
fun <A, B> arrow.Kind<F, A>.`ap`(dummy: Unit = Unit, ff: arrow.Kind<F, kotlin.Function1<A, B>>): arrow.Kind<F, B> =
this@ApplicativeSyntax.applicative().`ap`(this, ff)
fun <A, B, Z> arrow.Kind<F, A>.`map2`(dummy: Unit = Unit, fb: arrow.Kind<F, B>, f: …
```
=> Auto gen type class syntax inheritance in typeclass generation

modules/docs/arrow-docs/docs/docs/typeclasses/functor/README.md
I disabled Ank for the failing snippets because I had no clue to why it was failing. The snippets work if you explicitly pass the functor instance but I thought that defeated the purposes a little.
```
Back-end (JVM) Internal error: null
Cause: java.lang.NullPointerException
File being compiled and position: (4,16) in /Line_5.kts
The root cause was thrown at: ClassFileFactory.java:80
```
=> Disabled ank on failing snippets

modules/core/arrow-core/src/main/kotlin/arrow/core/Try.kt, modules/core/arrow-data/src/test/kotlin/arrow/data/StateTTests.kt, modules/core/arrow-data/src/test/kotlin/arrow/data/TryTest.kt, modules/core/arrow-data/src/test/kotlin/arrow/data/ValidatedTest.kt, modules/core/arrow-examples/src/test/kotlin/arrow/DataTypeExamples.kt, modules/core/arrow-instances/src/main/kotlin/arrow/instances/try.kt, modules/core/arrow-syntax/src/main/kotlin/arrow/syntax/try/try.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/MonadSuspendLaws.kt, modules/dagger/arrow-dagger/src/main/kotlin/arrow/dagger/instances/try.kt, modules/dagger/arrow-dagger/src/test/kotlin/arrow/dagger/instances/tests/instances.kt, modules/docs/arrow-docs/docs/docs/datatypes/try/README.md, modules/docs/arrow-docs/src/main/java/arrow/debug/debug.kt, modules/effects/arrow-effects-kotlinx-coroutines/src/main/kotlin/arrow/effects/DeferredKW.kt, modules/optics/arrow-optics/src/main/kotlin/arrow/optics/instances/try.kt, modules/optics/arrow-optics/src/main/kotlin/arrow/optics/std/try.kt, modules/optics/arrow-optics/src/main/kotlin/arrow/optics/std/validated.kt, modules/optics/arrow-optics/src/test/kotlin/arrow/optics/OptionalTest.kt, modules/optics/arrow-optics/src/test/kotlin/arrow/optics/instances/EachInstanceTest.kt, modules/optics/arrow-optics/src/test/kotlin/arrow/optics/std/ValidatedInstancesTest.kt
Since `Try` is a popular used data type along with other core ones like `Option` we are moving it to `arrow-core` with the intent of reducing the need for users to depend on `arrow-data` if they don't plan on using other more advanced data types.
=> Moves `Try` to `arrow-core` 

modules/core/arrow-core/src/main/kotlin/arrow/core/Try.kt, modules/core/arrow-data/src/test/kotlin/arrow/data/TryTest.kt
Handling a failed Success as if it was the same as original Failure is not the way it is done in cats. I would argue this makes for a better fold function.
=> Allow exception to propagate from fold Success function

modules/core/arrow-instances-data/src/main/kotlin/arrow/instances/listk.kt, modules/core/arrow-instances-data/src/main/kotlin/arrow/instances/set.kt, modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Semigroup.kt, modules/docs/arrow-docs/docs/docs/typeclasses/semigroup/README.md
Adds `+` to all `A` for which a `Semigroup` instance exists
```kotlin
operator fun A.plus(b: A): A =
this.combine(b)
```
=> Semigroup `+` syntax

modules/core/arrow-annotations-processor-test/src/main/java/arrow/ap/objects/Optional.kt, modules/core/arrow-annotations-processor-test/src/main/java/arrow/ap/objects/OptionalSealed.kt, modules/core/arrow-annotations-processor-test/src/test/java/arrow/ap/tests/OptionalTest.kt, modules/core/arrow-annotations-processor/src/main/java/arrow/optics/AnnotationInfo.kt, modules/core/arrow-annotations-processor/src/main/java/arrow/optics/IsosFileGenerator.kt, modules/core/arrow-annotations-processor/src/main/java/arrow/optics/LensesFileGenerator.kt, modules/core/arrow-annotations-processor/src/main/java/arrow/optics/OpticsProcessor.kt, modules/core/arrow-annotations-processor/src/main/java/arrow/optics/OptionalFileGenerator.kt, modules/core/arrow-annotations-processor/src/main/java/arrow/optics/PrismsFileGenerator.kt, modules/core/arrow-annotations/src/main/java/arrow/optics.kt
Closes #605 and can solve https://github.com/arrow-kt/arrow/pull/669#discussion_r179627406
Breaks all current annotations and moves them to `@optic` (@optics clashes with arrow.optics package).
Behavior changes
When not using any annotation arguments all optics applicable to the annotated element will be generated.
i.e. `@optic data class Person(val name: String, val age: Int?)
generates Iso<Tuple2<String,Int?>, Person>`, `Lens<Person, String>`, `Lens<Person, Int?>` and `Optional<Person, Int>`.
But when using `@optic([OpticTarget.OPTIONAL]` it only generates `Optional<Person, Int>`.
As a result, however, the processor will not bail anymore. For example, annotating above example with `@optic([OpticTarget.PRISM])` will not generate anything but will not show any warning or error.
Better …
=> Move all optic generation to a single annotation

build.gradle
Not requested but required anyways to avoid version conflicts on client projects / libs.
* Upgraded Kotlin to [last stable release](https://github.com/JetBrains/kotlin/releases/tag/v1.2.31).
* Upgraded kotlinx.coroutines to [last version available](https://bintray.com/kotlin/kotlinx/kotlinx.coroutines/0.22.5).
Tests are passing.
=> Upgrade Kotlin and kotlinx.coroutines

README.md
This way we'll notice if it ever breaks again 😂
=> Moar badges!

modules/core/arrow-annotations-processor/src/main/java/arrow/optics/IsosFileGenerator.kt, modules/core/arrow-annotations-processor/src/main/java/arrow/optics/OpticsProcessor.kt
With arrow-generic we can now support the generation of `Iso` up to Tuple22.
=> Generate isos up to arity 22

modules/docs/arrow-docs/docs/docs/effects/async/README.md, modules/docs/arrow-docs/docs/docs/integrations/rx2/README.md, modules/docs/arrow-docs/docs/docs/patterns/monadcomprehensions/README.md
Leftovers from the last refactor to comprehensions.
=> Remove references to bindAsync

modules/docs/arrow-docs/docs/docs/typeclasses/functor/README.md
and deadlinks to source and laws
=> DocsFix: Functor extension method type

modules/core/arrow-data/src/main/kotlin/arrow/data/EitherT.kt
Adds `.value()` shorthand for `.fix().value`, similar to what Id currently has.
=> EitherT: add .value()

modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Show.kt, modules/docs/arrow-docs/docs/docs/typeclasses/eq/README.md, modules/docs/arrow-docs/docs/docs/typeclasses/show/README.md
Solves: https://github.com/arrow-kt/arrow/issues/830
=> Show constructor to use receiver type to enable object property access

modules/docs/arrow-docs/docs/docs/patterns/monadcomprehensions/README.md
I think 'pass' works better than 'past' here.
=> Minor typo fix

README.md, gradle.properties, modules/docs/arrow-docs/docs/docs/README.md
Tags and change log will follow after this is merged
=> Release 0.7.2

modules/docs/arrow-docs/docs/docs/datatypes/listk/README.md
It's a glaring omission and at this point we just *need* it.
=> ListK docs

modules/core/arrow-core/src/main/kotlin/arrow/core/Either.kt, modules/docs/arrow-docs/docs/docs/datatypes/listk/README.md
A number of Either operations could be optimized I think, this is the low-hanging fruit
=> Prevent Either::map and Either::flatMap creating a new Left

modules/docs/arrow-docs/docs/docs/effects/io/README.md
Requested on gitter, it explains why `runAsync` doesn't start immediately.
=> Add extra tips for running IO

build.gradle, modules/effects/arrow-effects-kotlinx-coroutines/build.gradle, modules/effects/arrow-effects-kotlinx-coroutines/src/main/kotlin/arrow/effects/DeferredK.kt, modules/effects/arrow-effects-kotlinx-coroutines/src/test/kotlin/arrow/effects/DeferredTest.kt
For #884, 
This adds awaitAll to any F<DeferredK<T>> that returns F<T> where F has a traverse instance
=> AwaitAll for Traverse Deferred<T>

modules/docs/arrow-docs/docs/_includes/_doc-wrapper.html, modules/docs/arrow-docs/docs/js/functions.js
* Inject method to restore scroll position after focus into searchbar
It's kind of hacky, but it's probably our best shot until a way to detect feature options in JS engines is available.
More info on:
https://github.com/heycam/webidl/issues/107#issuecomment-399910305
This fixes #906
=> Inject method to restore scroll position after focus into searchbar

modules/core/arrow-data/src/main/kotlin/arrow/data/ListK.kt
Closes #807
Could @JorgeCastilloPrz @jrgonzalezg or @jereksel please check whether this fixes it? Or do we need to merge and use a snapshot to check it.
I'd say this is a blocker for 0.7.3, and we're ready for release afterwards.
=> Fix Android + Java 8 interaction

modules/core/arrow-core/src/main/kotlin/arrow/core/boolean.kt, modules/core/arrow-instances-core/src/main/kotlin/arrow/instances/boolean.kt
* Add @Deprecated annotation on arrow-core BooleanInstances
* Add @Deprecated annotation on arrow-instances-core boolean show and eq
functions
Closes #943
=> Add @Deprecated annotations on boolean instances

modules/core/arrow-data/src/main/kotlin/arrow/data/EitherT.kt, modules/core/arrow-data/src/main/kotlin/arrow/data/OptionT.kt, modules/core/arrow-data/src/main/kotlin/arrow/data/SequenceK.kt, modules/core/arrow-data/src/main/kotlin/arrow/data/StateT.kt, modules/core/arrow-data/src/main/kotlin/arrow/data/WriterT.kt, modules/core/arrow-instances-core/src/main/kotlin/arrow/instances/either.kt, modules/core/arrow-instances-data/src/main/kotlin/arrow/instances/eithert.kt, modules/core/arrow-instances-data/src/main/kotlin/arrow/instances/optiont.kt, modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Foldable.kt, modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Traverse.kt
This is another attempt at palliating #807, which is blocking releases
=> Attempt to fix 0.7.X crashing on Android

modules/core/arrow-free/src/main/kotlin/arrow/free/Free.kt, modules/core/arrow-mtl/src/main/kotlin/arrow/mtl/instances/option.kt, modules/core/arrow-mtl/src/main/kotlin/arrow/mtl/instances/optiont.kt, modules/effects/arrow-effects-reactor/src/main/kotlin/arrow/effects/CoroutineContextReactorScheduler.kt, modules/effects/arrow-effects-reactor/src/main/kotlin/arrow/effects/FluxK.kt, modules/effects/arrow-effects-reactor/src/main/kotlin/arrow/effects/MonoK.kt, modules/effects/arrow-effects-rx2/src/main/kotlin/arrow/effects/CoroutineContextRx2Scheduler.kt, modules/effects/arrow-effects-rx2/src/main/kotlin/arrow/effects/FlowableK.kt, modules/effects/arrow-effects-rx2/src/main/kotlin/arrow/effects/MaybeK.kt, modules/effects/arrow-effects-rx2/src/main/kotlin/arrow/effects/ObservableK.kt, modules/effects/arrow-effects-rx2/src/main/kotlin/arrow/effects/SingleK.kt
=> More fixes for the fix god

modules/effects/arrow-effects/src/main/kotlin/arrow/effects/IO.kt
With this small change we gain a ~30% perf improvement on some stupid benchmarks for tailrecM I made.
I'm sure I could shave more by making it abstract, maybe I'll test it tomorrow.
=> IO flatMap perf tweak

modules/effects/arrow-effects/src/main/kotlin/arrow/effects/IO.kt
Optimize `continueOn().continueOn()` to only start the coroutine of the second one.
Make `map` and `flatMap` overriden open methods without runtime costs.
flatMapping a `RaiseError` yields itself
=> More IO perf improvements

modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md
Putting it at the top for being the easiest and most up to date. Pushing the Kotlinconf talk down.
Ignore the diff, it's all fugged up. Check the file instead.
=> Add `Kotlin for the Pragmatic Functionalist` intro talk

modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md
Added my talk at DroidJam India, on Arrow and Functional Programming for Kotlin developers. a beginner level talk to get started with Functional Programming and Arrow.
https://www.youtube.com/watch?v=qYgilPqMOp0&t=1313s
Added it above Functional Programming in Kotlin - An ongoing blog series introducing Functional Programming architectures, as suggested by @pakoito
=> Add my talk at DroidJam

modules/effects/arrow-effects/src/main/kotlin/arrow/effects/IO.kt, modules/effects/arrow-effects/src/main/kotlin/arrow/effects/IORunLoop.kt, modules/effects/arrow-effects/src/main/kotlin/arrow/effects/data/internal/BindingCancellationException.kt, modules/effects/arrow-effects/src/main/kotlin/arrow/effects/data/internal/IOCancellationException.kt, modules/effects/arrow-effects/src/main/kotlin/arrow/effects/internal/Utils.kt, modules/effects/arrow-effects/src/test/kotlin/arrow/effects/IOTest.kt, reports/baseline.xml
Make `IO` have a new cancellable runAsync operator that ties into the run loop for cancellation. It improves over the old way of doing it at coroutine (flatMap) boundaries because now we can cancel after every operator call instead.
I'm tempted to make the cancellable asyncRun the default, as it has the same overhead with and without it cc @raulraja for opinion.
With cancellation and parallelism we can build races, which means we can finally have a proper concurrency framework and libraries for Android!
=> Add cancellation capabilities to IO

modules/core/arrow-core/src/main/kotlin/arrow/core/Try.kt, modules/core/arrow-data/src/test/kotlin/arrow/data/TryTest.kt
Added `success` and `failure` extfuns to `Try` datatype.
Added tests for `success` and `failure` to `TryTest`
It fixes #1009 
Let me know if there's something to change
=> Try's success/failure extfuns 

modules/core/arrow-validation/build.gradle
=> Publish arrow-validation to Maven

modules/core/arrow-test/src/main/kotlin/arrow/test/laws/AsyncLaws.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/MonadDeferLaws.kt, modules/effects/arrow-effects-rx2/src/test/kotlin/arrow/effects/MaybeKTests.kt, modules/effects/arrow-effects-rx2/src/test/kotlin/arrow/effects/SingleKTests.kt
Rename MonadSuspendLaws to MonadDeferLaws (including file name)
Fixes #993
=> Rename MonadSuspendLaws to MonadDeferLaws

modules/effects/arrow-effects-kotlinx-coroutines/build.gradle, modules/effects/arrow-effects-reactor/build.gradle, modules/effects/arrow-effects-rx2/build.gradle, modules/effects/arrow-effects/build.gradle
I realized `effects` doesn't need 400k extra of unused dependencies.
=> Slim down effects

modules/core/arrow-test/src/main/kotlin/arrow/test/laws/OrderLaws.kt, modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Order.kt, modules/docs/arrow-docs/docs/docs/typeclasses/order/README.md
This pull-request provides `compareTo` operators for all `Order` instances as described in #729.
There are two more operators mentioned in #729:
* Equality operator (`==`, `!=`) for `Eq` instances  - _it is impossible to implement that as extension function, because member functions always shadow extensions and equals is defined for every object in Kotlin (because of Java legacy)_
* Plus operator (`+`) for `Semigroup` instances - _already added in #768 _
It seems that all three items of issue would resolved after this PR is merged, so it will close #729
=> Add `compareTo` overload for `Order`

modules/docs/arrow-docs/docs/_sass/components/_code.scss, modules/docs/arrow-docs/docs/css/arrow.css
* Specify z-index for code snippets to avoid them clashing with sidebar.
We spotted a problem on the snippets conflicting with the open sidebar on mobile layouts.
This change fixes it.
=> Specify z-index for code snippets to avoid them clashing with sidebar

modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Foldable.kt
We were applying the Monad and Monoid restrictions to the same type `TC`.
This PR and the monoid parameter separately solving that.
=> Fix Foldable foldMapM restrictions

modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt, modules/docs/arrow-docs/docs/docs/typeclasses/applicativeerror/README.md
It makes sense with our right-bias policy, and the lambda sugar makes more sense in the operation rather than the transformation.
=> Make ApplicativeError#catch have bias to the right

modules/core/arrow-core/src/main/kotlin/arrow/core/Option.kt, modules/docs/arrow-docs/docs/docs/datatypes/option/README.md
Adding `firstOrNone`, `singleOrNone`, `lastOrNone`, `elementAtOrNone` as Iterable extensions methods.
This methods allows us to maintain a friendly API syntax when operating on lists while avoiding null handling.
The motivation behind this appeared when we had to iterate over entries of a Map using `firstOrNull`. We are beginning with FP and trying do build a 100% pure Domain. Our domain is very permissive, and almost all of the inputs are Option, so the `firstOrNull` like methods goes against our principles, and `firstOrNone` like methods appears to be a solution to this problem.
Example:
```
fun main() {
val foxMap = mapOf(1 to "The", 2 to "Quick", 3 to "Brown", 4 to "Fox")
val ugly = foxMap.entries.firstOrNull { it.key == 5 }?.value.let { it?.toCharArray() }.toOption()
val pretty = …
```
=> Adding Iterable Extensions that returns Option

modules/core/arrow-data/src/main/kotlin/arrow/data/SetK.kt
This is just a simple performance fix that I caught while taking a look at the code for another PR. 
It avoids the creation of a intermediate collection after the `drop(1)` method. So it goes easier with the Garbage Collector.
=> avoiding the creation of intermediate collection

README.md, gradle.properties, modules/docs/arrow-docs/docs/docs/README.md
[Full Changelog](https://github.com/arrow-kt/arrow/compare/0.7.3...0.8.0)
**Noteworthy in 0.8.0:**
- `@extension` Toward KEEP-87 [\#1040](https://github.com/arrow-kt/arrow/pull/1040) ([raulraja](https://github.com/raulraja))
- Add ApplicativeError constructors from the Core types [\#988](https://github.com/arrow-kt/arrow/pull/988) ([pakoito](https://github.com/pakoito))
- Add CancellableEffect typeclass. Use it to give races to IO [\#984](https://github.com/arrow-kt/arrow/pull/984) ([pakoito](https://github.com/pakoito))
- Optics state API [\#1047](https://github.com/arrow-kt/arrow/pull/1047) ([nomisRev](https://github.com/nomisRev))
- Optics reader syntax [\#1041](https://github.com/arrow-kt/arrow/pull/1041) ([nomisRev](https://github.com/nomisRev))
- Arrow playground …
=> Release 0.8.0

README.md
Adds `jitpack` as a gradle repository in order to fetch MnemoniK
=> Add jitpack to README

README.md, modules/docs/arrow-docs/docs/docs/README.md
The POM for retrofit adapter is:
```
POM_ARTIFACT_ID=arrow-integration-retrofit-adapter
```
So there's a small typo in the docs: 
compile "io.arrow-kt:arrow-integrations-retrofit-adapter:$arrow_version" //optional
That should be correct. Or the POM should be changed to it gets equal to the documentation
=> fixing docs

modules/docs/arrow-docs/docs/docs/README.md
Added related section at the bottom of the file.
It includes the basic maven setup, and instructions on how to enable kapt using kotlin plugin.
=> Add a section regarding Maven Support on Quick Start

codecov.yml
Some problems raised with PRs that update docs and pass the CI but fails on coverage report without any code change. This PR create a configuration file for codecov following it [docs](https://docs.codecov.io/docs/codecov-yaml) 
As the current project is in heavy development and an early stage (current version < 1.0.0)in order to not block changes and be more agile, the initial configuration will post coverage reports as comments only on coverage change and remove the status check to pass the PR.
=> configure codecov via yaml file

modules/docs/arrow-docs/docs/docs/patterns/glossary/README.md
- Fix misleading and out-of-date code snippet (`@instance(User::class)` -> `@extension`)
- Clarify how to define instances for specific types, and the requirements for those types
- Fix minor grammatical errors
=> Improve "Instances" section of the glossary

modules/core/arrow-test/src/main/kotlin/arrow/test/laws/MonadDeferLaws.kt, modules/docs/arrow-examples/src/test/kotlin/arrow/FpToTheMax.kt, modules/effects/arrow-effects-instances/src/main/kotlin/arrow/effects/instances/io.kt, modules/effects/arrow-effects-kotlinx-coroutines-instances/src/main/kotlin/arrow/effects/DeferredKInstances.kt, modules/effects/arrow-effects/src/main/kotlin/arrow/effects/Ref.kt, modules/effects/arrow-effects/src/main/kotlin/arrow/effects/internal/ParallelUtils.kt, modules/effects/arrow-effects/src/main/kotlin/arrow/effects/typeclasses/Async.kt, modules/effects/arrow-effects/src/main/kotlin/arrow/effects/typeclasses/MonadDefer.kt, modules/effects/arrow-effects/src/main/kotlin/arrow/effects/typeclasses/MonadSuspendCancellableContinuations.kt, modules/integrations/arrow-integrations-retrofit-adapter/src/main/kotlin/arrow/integrations/retrofit/adapter/syntax.kt
Fixes #1135
the `delay` has the same implementation as the `invoke` operator.
I added `@Deprecated` with `@ReplaceWith` to the `invoke` operator. 
I replaced all usages of `invoke` with `delay` (that I could find).
Is that all? Or am I missing something?
Note:
When I run the tests with `./gradlew test` (both before and after this change) a test inside `IOTests` fails. If I run trough IntelliJ only for that class, everything works fine. Is this a know issue? Should I report a bug?
=> Deprecate `invoke`, add a `delay` function that does the same thing

modules/ank/README.md
=> Add Λnk README

modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/MonoidK.kt, modules/core/arrow-typeclasses/src/test/kotlin/arrow/typeclasses/MonoidKTest.kt
This pull request fixes the `StackOverflowError` exception that is thrown when running the following code:
```
listOf(Option(1)).fold(Option.monoidK().algebra())
```
It closes #1126
=> Fixes StackOverFlow issue in MonoidK typeclass

modules/ank/arrow-ank/build.gradle, modules/ank/arrow-ank/src/main/kotlin/arrow/ank/algebra.kt, modules/ank/arrow-ank/src/main/kotlin/arrow/ank/ank.kt, modules/ank/arrow-ank/src/main/kotlin/arrow/ank/interpreter.kt, modules/ank/arrow-ank/src/main/kotlin/arrow/ank/main.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/MonadDeferLaws.kt, modules/docs/arrow-docs/docs/docs/integrations/kotlinxcoroutines/README.md, modules/docs/arrow-docs/src/main/kotlin/EffectsHelper.kt, modules/effects/arrow-effects-kotlinx-coroutines-instances/src/main/kotlin/arrow/effects/DeferredKInstances.kt, modules/effects/arrow-effects-kotlinx-coroutines/src/main/kotlin/arrow/effects/DeferredK.kt
Solves #1156 and maybe #1131 
Re-enable no-memoization law and fix deferredK to follow it (if used correctly)
Changes practically nothing from the public api.
I'll add some info to the docs later because if used wrong it might produce unexpected results.
Should the methods in DeferredK (well the public ones) have api docs (runnable ones) as well?
@pakoito I have skipped the invoke constructor for Wrapped because its syntax conflicts with the other one too much (the compiler was only able to infer which one to choose after passing more and more arguments which defeats the point of default argumens there), one should just use the other one or `.k()` instead. (And going from `() -> Deferred<A>` to `suspend () -> A` is trivial)
=> Attempt to make DeferredK rerunnable

.travis.yml, modules/core/arrow-data/src/main/kotlin/arrow/data/Kleisli.kt
* Fix a problem that may occur when building and deploying docs where the Travis job would fail when no output is received after 10 minutes. `jekyll build` is north of 9 minutes on my machine so there's a potential risk of the Travis job eventually failing due to this.
=> Fix Travis timeouts because no output was received

build.gradle
`./gradlew clean build test dokka runAnk` should produce a correct result after branch switch. Currently, when there're API docs for new classes the build will fail because they cannot be compiled with Ank.
=> Delete api docs on clean

modules/docs/arrow-docs/README.md
Follow up to #1139 which was a very good start for the `Ank` docs. 
Fixes #1195
=> Docs for the docs

modules/docs/arrow-docs/docs/docs/quickstart/projects/README.md
As suggested by @pakoito I've added a new repository where we can find some common katas solved using purely functional programming in Kotlin powered by Arrow to the projects section.
=> Add KotlinKatas example to the related projects page

README.md
arrow-query-language was missing from the list of dependencies. Added it in the readme.
=> Added arrow-query-language in the dependencies

build.gradle, modules/core/arrow-data/src/test/kotlin/arrow/data/OptionTTest.kt, modules/core/arrow-instances-core/src/main/kotlin/arrow/instances/function0.kt, modules/core/arrow-instances-core/src/main/kotlin/arrow/instances/function1.kt, modules/core/arrow-instances-core/src/main/kotlin/arrow/instances/id.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/AsyncLaws.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/Law.kt, modules/effects/arrow-effects-instances/src/test/kotlin/arrow/effects/IOTest.kt, modules/effects/arrow-effects-kotlinx-coroutines-instances/src/main/kotlin/arrow/effects/DeferredKInstances.kt, modules/effects/arrow-effects-kotlinx-coroutines-instances/src/test/kotlin/arrow/effects/DeferredTest.kt, modules/effects/arrow-effects-kotlinx-coroutines/src/main/kotlin/arrow/effects/DeferredK.kt, modules/effects/arrow-effects-kotlinx-coroutines/src/main/kotlin/arrow/effects/DeferredKConnection.kt, modules/effects/arrow-effects-reactor-instances/src/test/kotlin/arrow/effects/FluxKTests.kt, modules/effects/arrow-effects-rx2-instances/src/test/kotlin/arrow/effects/MaybeKTests.kt, modules/effects/arrow-effects-rx2-instances/src/test/kotlin/arrow/effects/ObservableKTests.kt, modules/effects/arrow-effects-rx2-instances/src/test/kotlin/arrow/effects/SingleKTests.kt
Address Code review of #1189 
Fixes build issues master
Fixes scoping issues:
`GlobalScope` should be avoided at all costs because it infers with cancellation and thus I removed it as the default value. This also wires the scopes correctly for nested hierarchies build using typeclasses.
=> Small fix Deferred

modules/docs/arrow-docs/docs/docs/quickstart/blogs/README.md
This PR adds _Manual documentation is dead. Long live automated documentation! Automated documentation with ΛNK_ [video](https://www.youtube.com/watch?v=CvNoX2gGd9c) to the docs.
=> Add video from .droidconSF 2018

modules/docs/arrow-docs/README.md
Fixes #1239
* Update metadocs steps to better reflect what is needed to be completed in order to get the docs properly running locally.
=> Update metadocs steps

modules/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/core/Try.kt
Fix bad format due to markdown list on table style
Fixes #1228
=> fix apidoc bad format

modules/core/arrow-extras-extensions/src/main/kotlin/arrow/data/extensions/andthen.kt, modules/core/arrow-extras/src/main/kotlin/arrow/data/AndThen.kt, modules/core/arrow-extras/src/main/kotlin/arrow/data/StateT.kt, modules/core/arrow-extras/src/test/kotlin/arrow/data/AndThenTest.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/MonadDeferLaws.kt
This also fixes `StateT` stack safety issues using `AndThen`.
=> AndThen data type

modules/core/arrow-test/src/main/kotlin/arrow/test/generators/Generators.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/AsyncLaws.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/BracketLaws.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/IOFrame.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/internal/IOBracket.kt, modules/effects/arrow-effects-data/src/test/kotlin/arrow/effects/IOTest.kt
`IOFrame` was not correctly called unless manually wrapped in `IO.Bind`. It did not run using `flatMap` like Cats-effect's `IO` because `IO.RaiseError` is overridden to short-circuit `flatMap` like this `override fun <B> flatMap(f: (Nothing) -> IOOf<B>): IO<B> = this`
To leave the overridden function as explicit as it currently is I opted to elaborate in the `IOFrame` docs how to properly use it. Also, I added a test for this and changed the usage in `IOBracket`.
Do we want to keep it like this or shall we override `IO.RaiseError#flatMap` as follows to prevent similar bugs by miss-use in the future?
```
override fun <B> flatMap(f: (Nothing) -> IOOf<B>): IO<B> =
if (f is IOFrame) Bind(this, f as (Nothing) -> IO<B>) else this
```
=> Fix IOFrame usage in IOBracket

modules/docs/arrow-docs/docs/docs/arrow/core/try/README.md, modules/docs/arrow-docs/docs/docs/arrow/core/try/README_RU.md
Fixed link to Russian translation (and from Russian to English) — it hasn't been visible the first time.
My bad, my fix.
=> fixed links to Try translation

modules/docs/arrow-docs/docs/docs/arrow/core/try/README_RU.md
* Fix permalink for Try Russian translation
The way permalinks work on our deploy system, they need to be set as trailing slash URLs for them to really point you to a non trailing slash URL. Sorry about that @dobrowins, I didn't noticed on your previews PRs
=> Fix permalink for Try Russian translation

modules/meta/arrow-meta/src/main/java/arrow/common/utils/AbstractProcessor.kt
Windows is not very good with having `?` characters as part of a path. This, hopefully, fixes the issue for people trying to use the Annotation processor with Windows.
=> Ensure paths are compatible with windows

modules/docs/arrow-docs/docs/_posts/2019-02-03-arrow-webflux.md
Wrote an article on how to use Arrow and Webflux together to create a Spring Webflux application where the nice binding approach provided by Arrow is used for sequencing reactive function calls.
=> Add link to blogpost on Arrow and Webflux

README.md, modules/docs/arrow-docs/docs/docs/README.md
Optional dependency  'arrow-effects-io-extensions' was missing from the README.MD Basic Setup section.
=> Add 'arrow-effects-io-extensions' to Basic Setup

modules/docs/arrow-docs/docs/docs/effects/fx/README.md, modules/docs/arrow-docs/docs/docs/effects/fx/async/README.md, modules/docs/arrow-docs/docs/docs/effects/fx/polymorphism/README.md
Small edits for the Arrow Fx, async, and polymorphism readmes
=> Mre doc edits

modules/core/arrow-core-data/src/main/kotlin/arrow/core/NonFatal.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/core/Try.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/NonFatalTest.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/generators/Generators.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/MonadErrorLaws.kt, modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt, modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/MonadError.kt, modules/docs/arrow-docs/docs/docs/integrations/reactor/README.md, modules/docs/arrow-docs/docs/docs/integrations/rx2/README.md, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/IO.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/IORunLoop.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/internal/ForwardCancelable.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/internal/IOBracket.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/Async.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/MonadDefer.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/MonadDeferCancellableContinuations.kt, modules/effects/arrow-effects-reactor-data/src/main/kotlin/arrow/effects/reactor/FluxK.kt, modules/effects/arrow-effects-reactor-data/src/main/kotlin/arrow/effects/reactor/MonoK.kt, modules/effects/arrow-effects-rx2-data/src/main/kotlin/arrow/effects/rx2/FlowableK.kt, modules/effects/arrow-effects-rx2-data/src/main/kotlin/arrow/effects/rx2/MaybeK.kt, modules/effects/arrow-effects-rx2-data/src/main/kotlin/arrow/effects/rx2/ObservableK.kt, modules/effects/arrow-effects-rx2-data/src/main/kotlin/arrow/effects/rx2/SingleK.kt, modules/streams/arrow-streams/src/main/kotlin/arrow/streams/internal/FreeC.kt
As discussed in https://kotlinlang.slack.com/archives/C5UPMM0A0/p1550319070097800
Port of the Scala NonFatal.
I've hopefully found all places where it should be applied. I've searched with `catch \(.*:\s+Throwable\)` in all Production Files using IntelliJ.
Closes #153
=> [#153] Control NonFatal Throwables

modules/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/EitherTest.kt
fix for the task: #1324
-[ ] documentation does not contain example code to handling error ( `[Left]` ). Could be some example added.
=> handleErrorWith for Either

modules/docs/arrow-docs/README.md
Accessing the documentation with https://127.0.0.1:4000 returns a bad URI error. 
According to [Stack Overflow](https://stackoverflow.com/a/47057601/2050159) and [GitHub](https://github.com/jekyll/jekyll/issues/6507#issuecomment-340816350) the error occurs when accessing the URL via https.
=> Fix Jekyll deployment url

modules/core/arrow-core-data/src/main/kotlin/arrow/core/Function0.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/core/Id.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/core/Option.kt, modules/core/arrow-extras-data/src/test/kotlin/arrow/data/ValidatedTest.kt, modules/core/arrow-extras-extensions/src/main/kotlin/arrow/data/extensions/validated.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/SelectiveLaws.kt, modules/docs/arrow-docs/docs/docs/arrow/typeclasses/selective/README.md
- docs fix for selective hierarchy diagram
- remove redundant identity calls 
- added selective instance for validated (all other instances so far also have monad instances)
- distributivity and accociativity laws from Selective paper added
=> selective functor extras

build.gradle, modules/core/arrow-core-data/src/test/kotlin/arrow/extensions/NumberMonoidTest.kt, modules/core/arrow-extras-data/src/main/kotlin/arrow/data/Moore.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/generators/Generators.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/Law.kt, modules/integrations/arrow-integrations-retrofit-adapter/src/test/kotlin/arrow/integrations/retrofit/adapter/CallKindAdapterFactoryTest.kt
Law updated because the function has to be suspended.
NumberMonoid updated because nesting is not supported and I had to create some generators.
Moore updated because the default `toString` implementation breaks kotlin-reflect.
Fixes #1330
thanks @pakoito for the help :smile:
=> Update kotlintest to version 3.3.1

build.gradle, modules/meta/arrow-meta/src/main/java/arrow/common/utils/AbstractProcessor.kt, modules/meta/arrow-meta/src/main/java/arrow/extensions/ExtensionProcessor.kt, modules/meta/arrow-meta/src/main/java/arrow/generic/CoproductFileGenerator.kt, modules/meta/arrow-meta/src/main/java/arrow/meta/decoder/Decoder.kt, modules/meta/arrow-meta/src/main/java/arrow/meta/encoder/jvm/KotlinPoetEncoder.kt
* This tries to migrate to latest KotlinPoet 1.1.0.
* Code changes seem equivalent to previous code (please comment if you see any issue), but it seems KotlinPoet is adding some extra new lines that break compilation.
* Example generated code for `ConstFunctor` before with KotlinPoet 1.0.0-RC1:
```
fun <A> Kind<Kind<ForConst, A>, A>.unit(): Const<A, Unit> = arrow.typeclasses.Const.functor<A>().run {
this@unit.unit() as arrow.typeclasses.Const<A, kotlin.Unit>
}
```
* Example generated code for `ConstFunctor` now with KotlinPoet 1.1.0:
```
fun <A> Kind<Kind<ForConst, A>, A>.unit(): Const<A, Unit> = arrow.typeclasses.Const.functor<A>().run
{
this@unit.unit() as arrow.typeclasses.Const<A, kotlin.Unit>
}
```
The new line before the brace causes the following compilation errors: …
=> Migrated to latest KotlinPoet stable 1.1.0

modules/docs/arrow-docs/README.md
The bundle installation fails during installation of the Ruby gem http_parser, if the path to the arrow directory contains spaces. This commit adds a note about this problem to the README.
=> Add info about a possible error

modules/core/arrow-extras-data/src/main/kotlin/arrow/data/NonEmptyList.kt
Fixes #1312
Call toList() on List constructor arguments to ensure that the new
object is unaffected by any mutations on its inputs.
Without this, a mutable list can be stored as either the `all` or `tail`
property of the NonEmptyList, which is affected by all changes, but is
then out of sync with the other properties.
=> ensure NonEmptyList properties are immutable

modules/docs/arrow-docs/docs/docs/effects/ref/README.md, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/MVar.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/Ref.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/Semaphore.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/Concurrent.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/MonadDefer.kt, modules/effects/arrow-effects-data/src/test/kotlin/arrow/effects/MVarTest.kt, modules/effects/arrow-effects-data/src/test/kotlin/arrow/effects/PromiseTest.kt, modules/effects/arrow-effects-data/src/test/kotlin/arrow/effects/RefTest.kt, modules/effects/arrow-effects-extensions/src/main/kotlin/arrow/effects/extensions/eithert.kt, modules/effects/arrow-effects-extensions/src/main/kotlin/arrow/effects/extensions/optiont.kt, modules/effects/arrow-effects-extensions/src/main/kotlin/arrow/effects/extensions/statet.kt, modules/effects/arrow-effects-extensions/src/main/kotlin/arrow/effects/extensions/writert.kt
Making the allocation lazy so every call to `IO` generates a new one, and we prevent eager expensive operations unless needed.
=> Add new recommended constructor for Ref

README.md, modules/docs/arrow-docs/docs/docs/README.md
Adds the following badge to the readme of the project for support and Q+A
[![StackOverflow](https://img.shields.io/badge/arrow--kt-black.svg?logo=stackoverflow)]( http://stackoverflow.com/questions/tagged/arrow-kt )
=> Add badge with stackoverflow link for support

modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/IO.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/IORunLoop.kt
This PR rewrites the current `ContinueOn` impl.
I've added `Effect` already because I rely on it to implement `ContinueOn`.
The reason for this rewrite is so we can keep track of `CoroutineContext` when adding the `Effect` impl, so following test passes [source](https://github.com/arrow-kt/arrow/blob/693c2d2861b6fab0474130b7c7266855d4c8e41f/modules/effects/arrow-effects-data/src/test/kotlin/arrow/effects/IOTest.kt#L144)
```
"fx can pass context state across not/bind" {
fx {
val ctx = !effect { kotlin.coroutines.coroutineContext }
!effect { ctx shouldBe EmptyCoroutineContext }
continueOn(CoroutineName("Simon")) // this is immediately lost and useless.
val ctx2 = !effect { kotlin.coroutines.coroutineContext }
!effect { ctx2 shouldBe CoroutineName("Simon") }
}.unsafeRunSync()
}
```
=> IO rewrite ContinueOn impl

modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/IORunLoop.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/internal/Utils.kt, modules/effects/arrow-effects-data/src/test/kotlin/arrow/effects/IOTest.kt
Currently `IO.just(1).uncancelable().unsafeRunSync()` hangs, because `step` is a partial function. This adds the missing step.
* Is there a way to enforce exhaustiveness without capturing the value? And/or would the additional bytecode of capturing the value slow down the loop/step?
=> IO incomplete `IORunLoop#step`

modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/IO.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/IORunLoop.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/internal/Utils.kt, modules/effects/arrow-effects-data/src/test/kotlin/arrow/effects/IOTest.kt
Adds trampoline capabilities to `Async`.
This can be used to build in fairness #1429 (w/o involving coroutines).
=> IO trampoline async

modules/core/arrow-core-data/src/main/kotlin/arrow/core/TupleN.kt
Add the ability to change between `Triple` and `Tuple3`
=> Add triple tuple3 interoperability

modules/core/arrow-test/src/main/kotlin/arrow/test/laws/ConcurrentLaws.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/IORacePair.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/IORaceTriple.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/RaceModels.kt, modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/Concurrent.kt, modules/effects/arrow-effects-extensions/src/main/kotlin/arrow/effects/extensions/io.kt
Currently the race results are modeled as nested `Either`s, which means that if you try to call `fold` it'll use the instance method instead of the `fold` extension function.
The only solution AFAIK is defining actual models with a `fold` method.
One quirk is that you cannot ignore multi-param lambdas and it become mandatory to do
`_, _, _  -> raiseError(..)` but only affects `racePair` and `raceTriple`.
=> Improve racing APIs

.travis.yml, modules/benchmarks/arrow-benchmarks-effects/src/jmh/kotlin/arrow/benchmarks/RacePair.kt
This PR fixes the currently broken code in Benchmarks introduced by #1459, and introduces a CI step to compile the `jmh` classes to prevent this in the future.
=> Fix benchmarks

modules/core/arrow-syntax/src/main/kotlin/arrow/syntax/collections/array.kt, modules/core/arrow-syntax/src/main/kotlin/arrow/syntax/collections/iterable.kt, modules/core/arrow-syntax/src/main/kotlin/arrow/syntax/collections/list.kt, modules/core/arrow-syntax/src/main/kotlin/arrow/syntax/collections/sequence.kt, modules/core/arrow-syntax/src/main/kotlin/arrow/syntax/collections/string.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/FoldableLaws.kt, modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Foldable.kt, modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Reducible.kt, modules/docs/arrow-docs/docs/docs/arrow/typeclasses/foldable/README.md
=> Generalizes `firstOption` and promotes it to `Foldable`.

modules/core/arrow-core-data/src/main/kotlin/arrow/core/Id.kt, modules/docs/arrow-docs/docs/_data/sidebar.yml, modules/docs/arrow-docs/docs/docs/arrow/core/id/ru/README.md, modules/docs/arrow-docs/docs/docs/integrations/kindedj/README.md, modules/docs/arrow-docs/docs/docs/quickstart/libraries/README.md
The Playground has been fixed. And also the existing links to id from other pages.
=> Move the Documentation for `Id` from README.md to the Id.kt

modules/core/arrow-core-data/src/main/kotlin/arrow/core/Option.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/OptionTest.kt
As discussed in https://github.com/arrow-kt/arrow/issues/1475 this is a proposed fix to the issue.
A convenience method was added `mapNotNull` with KDoc and a corresponding UnitTest.
=> fixes ["Request"] convenient Option.mapNotNull #1475

modules/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/core/Try.kt
This diff stabilizes a proposal that's been floating for a while. `Try` is a defective `Either` with a nice constructor. Let's promote using `Either` or `IO` instead.
=> Favor Either and IO instead of Try

modules/ank/arrow-ank/src/main/kotlin/arrow/ank/ank.kt, modules/ank/arrow-ank/src/main/kotlin/arrow/ank/interpreter.kt
Given that we have quite some docs already, and we're doing some refactorings it's becoming increasingly hard to maintain docs. Luckily Ank is there to save us!
To make the task of updating the docs less annoying I thought it'd be better if we collected all incorrect docs instead of failing fast on the first one. Saves a bunch of build time.
Given that there is not feature roadmap for Ank I just did the simplest thing possible.
=> Ank not fail fast

build.gradle, modules/effects/arrow-effects-data/src/test/kotlin/arrow/effects/EffectsSuspendDSLTests.kt
#1482 caused a failed build and needs to revert to the previous commit. 
https://app.bitrise.io/build/c302b0457b8867cd#?tab=log
The Author @ogolberg from #1482 may reopen his PR.
A rebuild did not fix the changes. 
Plausible reasons:
Due to the change to the kotlin version, it may have affected the way regex is processed in Kotlin. Maybe a fix in the [Ank interpreter](https://github.com/arrow-kt/arrow/blob/557b8c06d46d63145f43101cca0b4427bb9bd26e/modules/ank/arrow-ank/src/main/kotlin/arrow/ank/interpreter.kt#L219-L240) is needed. 
[Hence, this line is generated wrongly](https://github.com/arrow-kt/arrow/blob/62f692397ef44e6acde12af817d94a19d2ce9621/modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Functor.kt#L49)
Resulting in a string like this:
```
fun main(args: …
```
=> Revert "Bump to Kotlin 1.3.31 (#1482)"

modules/docs/arrow-docs/docs/docs/effects/io/README.md
This PR fixes the `IO.suspend` docs so they are up to date with the latest version (`0.9.0`). I think `suspend` was renamed to `defer` (my artifacts don't have a `suspend`) so the docs should be updated.
=> Replace IO suspend with defer

modules/core/arrow-test/src/main/kotlin/arrow/test/laws/AsyncLaws.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/EffectsSuspendDSLTests.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt
Tests were resulting in OOM a lot because we were creating `newSingleThreadContext` in property based tests which resulted in 1001 threads being created for every call to `newSingleThreadContext` within `forAll`.
Fixes #1499.
=> Fix OOM'ing tests

modules/optics/arrow-optics-mtl/gradle.properties, modules/optics/arrow-optics/gradle.properties
tries to fix this issue: https://github.com/arrow-kt/arrow/issues/1510
The problem before was that both modules were deployed under the same artifact name. Thus creating binary issues when deploying.
=> deploys optics artifacts

modules/docs/arrow-docs/docs/_posts/2019-06-07-kotliners-arrow-fx.md, modules/docs/arrow-docs/docs/docs/quickstart/projects/README.md
Add Kotliners ArrowFx talk to the blog page in the media category, plus fix the `ArrowAndroidSamples` repo link since it was outdated.
=> Add Kotliners ArrowFx talk and fix android sample project link

modules/docs/arrow-docs/docs/docs/quickstart/linting/README.md
* Fixes https://github.com/arrow-kt/arrow/issues/1502
[ktlint-v0.34.0](https://github.com/pinterest/ktlint/releases/tag/0.34.0) has been released and includes the new feature to globally disable rules from the `.editconfig` file. 
This PR includes a small guide to disable ktlint errors when `Unit` is used as an explicit return type in the existing section that explains why this is considered desireable when working with Arrow and FP
=> Add documentation to disable explicit unit return error in ktlint

modules/core/arrow-core-data/src/main/kotlin/arrow/core/AndThen.kt
`AndThen#contramap` seems not `andThen` alias. Correctly it is `compose` alias.
=> Fix AndThen#contramap doc

README.md, modules/docs/arrow-docs/docs/docs/README.md
fixes some webpage problems users have and deletes references to SnapShot builds.
=> cleanUp on "stable" webpage

modules/fx/arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Async.kt, modules/meta/arrow-meta/src/main/java/arrow/meta/encoder/jvm/TypeElementEncoder.kt
See #1485 
Fixes #1554
@FireZenk @nomisRev @pakoito meta generates now for functions like effectMap:
```kotlin
fun <A, B> Kind<ForIO, A>.effectMap(f: suspend (A) -> B): IO<B> = arrow.fx.IO.async().run {
this@effectMap.effectMap<A, B>(f) as arrow.fx.IO<B>
}
```
=> Fix extension processor suspend fun args

modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IOParMap3.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/internal/ConcurrentParMap2.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/internal/ConcurrentParMap3.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt
Fixes a null related bug in IOParMap3 that makes a param of `IO.just(null)` makes the code hang.
=> Fix IOParMap3 null bug

.travis.yml, README.md, build.gradle, codecov.yml
Talking with @JorgeCastilloPrz and @i-walker we don't see the needs of coverage reports until a stable version is released, codecov was disabled on #1108 but still executed as CI stage. 
This PR remove that stage on CI, badge on README.MD and codecov configuration file
I still keep the codecov integration for the Arrow-kt organization, but without any repo access
=> remove codevoc

.editorconfig, build.gradle, modules/ank/arrow-ank/src/main/kotlin/arrow/ank/interpreter.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Bifunctor.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Contravariant.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Foldable.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Functor.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/function0.kt, modules/meta/arrow-meta/src/main/java/arrow/meta/ast/ast.kt
#1525
Upgrade ktlint to the latest version where rules can be globally disabled via `.editorconfig` and include `no-unit-return` so functions can declare `Unit` return type explicitly
Bump ktlint gradle plugin to latest version, from 7.3.0 to 8.2.0. This would set ktlint to use version 0.34.0. This version shipped with some bugs, so have forced ktlint to latest minor where they are fixed by setting the library version through KtlintExtension in `build.gradle`. 
This effectively bumps ktlint from 0.31.0 to 0.34.2, allowing `no-unit-return` to be disabled. Apart from it, the following rules have required attention in the codebase
Added on version `0.34.0` to the [standard rule set](https://github.com/pinterest/ktlint/commit/adb4d4d20a63ad0ab5c67e426429c273bbdec2ad#diff-ccd5a7f365eb13a0c3aea7 …
=> Upgrade ktlint and disable no-unit-return rule

modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/FlowableKTests.kt, modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/MaybeKTests.kt, modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/ObservableKTests.kt, modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/RxJavaSpec.kt, modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/SingleKTests.kt
Temporarily solution to keep RxJavaPlugins from flooding the CI logs and failing the build.
This should not result in any false positives since RxJava always calls `RxJavaPlugins` seperately from `observer.onError` so this just disables the logging done by `RxJavaPlugins`.
=> Supress Rx onError logging

modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/FlowableK.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/MaybeK.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/ObservableK.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/SingleK.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/flowablek.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/maybek.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/observablek.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/singlek.kt, modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/ObservableKTests.kt, modules/integrations/arrow-integrations-retrofit-adapter/src/test/kotlin/arrow/integrations/retrofit/adapter/ProcCallBackTest.kt
Here is my first try to fix #1609.
I only made `ObservableK` covariant this time, after making sure everything fine with `ObservableK` I'll continue to work on other types of Rx family.
P/S: I had to remove `ObservableKKindedJ<A>` from inherited list because `io.kindedj.Hk<ForObservableK, A>` is invariant.
=> Make Rx family covariant

modules/validation/arrow-validation/src/main/kotlin/arrow/validation/refinedTypes/numeric/NonZero.kt, modules/validation/arrow-validation/src/test/kotlin/arrow/validation/refinedTypes/numeric/NonZeroTest.kt
Some people are getting this compilation error in the validation module when building the arrow project:
```
e: ~/arrow/modules/validation/arrow-validation/build/generated/source/kaptKotlin/main/extension/arrow/validation/refinedTypes/numeric/either/nonZero/EitherNonZero.kt: (18, 47): Type argument is not within its bounds: should be subtype of 'Number'
e: ~/arrow/modules/validation/arrow-validation/build/generated/source/kaptKotlin/main/extension/arrow/validation/refinedTypes/numeric/either/nonZero/EitherNonZero.kt: (18, 55): Type mismatch: inferred type is <no name provided> but EitherNonZero<Any?> was expected
```
It seems the issue is caused by the `isNonZero` function that compares a value of the generic type `A` with the literal int `0`.
This pull request proposes using the …
=> Using Eq typeclass NonZero class within validation module

modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Alternative.kt, modules/docs/arrow-docs/docs/docs/arrow/typeclasses/alternative/README.md
Docs taken from [here](https://en.wikibooks.org/wiki/Haskell/Alternative_and_MonadPlus) and [here](https://wiki.haskell.org/Typeclassopedia#Failure_and_choice:_Alternative.2C_MonadPlus.2C_ArrowPlus).
Two things that are weird for me.
One is we don't offer `Option.alternative()` and I have to use `Option.monadCombine()` which is subclass of Alternative but it can confuse readers.
The second thing is that one of the sources I've used for writing these docs says that `<|>` combines computations but the other says it is a choice between alternatives. And it seems depending on the instance it is both of those things. Maybe `orElse` is not a good name enough or we should try to explain it better in the docs 🤔.
=> Adding some docs for Alternative

modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/extensions/fluxk.kt, modules/fx/arrow-fx-reactor/src/test/kotlin/arrow/fx/FluxKTest.kt
This one will actually close #1501 :P
=> Implement MonadFilter for FluxK

modules/meta/arrow-meta-prototype/compiler-plugin/src/main/kotlin/arrow/meta/plugins/higherkind/HigherKindPlugin.kt
Pretty small change to detect `higherkind` annotation like:
```
@higherkind
```
or:
```
@arrow.higherkind
```
=> Add regex to detect higherkind annotation

modules/meta/arrow-meta-prototype/compiler-plugin/build.gradle, modules/meta/arrow-meta-prototype/compiler-plugin/src/main/kotlin/arrow/meta/plugins/comprehensions/ComprehensionsPlugin.kt, modules/meta/arrow-meta-prototype/compiler-plugin/src/test/kotlin/arrow/meta/plugins/comprehensions/ComprehensionsTest.kt, modules/meta/arrow-meta-prototype/compiler-plugin/src/test/kotlin/arrow/meta/plugins/higherkind/HigherkindTest.kt, modules/meta/arrow-meta-prototype/compiler-plugin/src/test/resources/arrow/meta/plugins/comprehensions/Example.kt.meta, modules/meta/arrow-meta-prototype/testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/Compilation.kt, modules/meta/arrow-meta-prototype/testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/CompilationData.kt, modules/meta/arrow-meta-prototype/testing-plugin/src/test/kotlin/arrow/meta/plugin/testing/CompilationTest.kt
:warning: The base branch of this pull request isn't `master`.
* New tests about comprehensions
* Improvements:
* Remove _nullable_ types 
* Remove the need of writing assertions by the user.
```
assertThis(CompilationData(
sourceFilename = "...",
sourceCode = "...",
checks = listOf(
CompilationError()
GeneratedSourceCode(...)
GeneratedClasses(...)
),
compilationStatus = CompilationStatus.OK
))
```
=> [META] Comprehensions

.github/workflows/build.yml, .travis.yml, README.md, bitrise.yml
Add GitHub Actions to build the project.
The final list of checks would be:
* **Build**: GitHub Actions
* **Release**: Travis CI to Bintray
* **Documentation**: Bitrise
There aren't notifications about failures with CI tasks.
Issue  #1678
This pull request doesn't change Travis CI because there is not an easy option to work with Oracle JDK from GitHub Actions (not convinced by the alternative of using a PPA).
=> Add GitHub Actions to build the project and to get notifications

modules/aql/arrow-aql/src/main/kotlin/arrow/aql/Max.kt, modules/aql/arrow-aql/src/main/kotlin/arrow/aql/Min.kt, modules/aql/arrow-aql/src/test/kotlin/arrow/aql/tests/AQLTests.kt
We need to use a value to define which row is max or min, but not necessarily this value has to be returned.
=> Max and Min Shouldn't modify the Query value

modules/meta/arrow-meta-prototype/README.md, modules/meta/arrow-meta-prototype/idea-plugin/build.gradle, modules/meta/arrow-meta-prototype/idea-plugin/src/main/kotlin/arrow/meta/plugin/idea/MetaPluginRegistrarComponent.kt, modules/meta/arrow-meta-prototype/idea-plugin/src/main/kotlin/arrow/meta/plugin/idea/phases/resolve/DiagnosticSuppressor.kt, modules/meta/arrow-meta-prototype/idea-plugin/src/main/kotlin/arrow/meta/plugin/idea/phases/resolve/FragmentProviderComponent.kt, modules/meta/arrow-meta-prototype/idea-plugin/src/main/kotlin/arrow/meta/plugin/idea/phases/resolve/MetaSyntheticPackageFragmentProvider.kt, modules/meta/arrow-meta-prototype/idea-plugin/src/main/kotlin/arrow/meta/plugin/idea/phases/resolve/package.kt, modules/meta/arrow-meta-prototype/idea-plugin/src/main/resources/META-INF/plugin.xml
CI isn't passing, but that's already the case with `rr-meta-prototype-integration`.
- register MetaPlugin's plugins for each project when project is opened. Before this change it was done when the fragment provider was called for the first time. Now this work is done when the project is loaded (by using a `ProjectComponent`)
- scope cache per project. Before a global cache was shared between projects. Changes in one project clear the cache which then releases cached data needed for another project. The other project refreshes, too, and the cache could end up with incomplete content
- init cache once when project is opened and not when the fragment provider was called for the first time
- cache refresh is now handling dumb mode correctly, i.e.  `IndexNotReadyException` shouldn't be thrown …
=> Clean up and improve fragment provider update handling

modules/core/arrow-core-data/src/test/kotlin/arrow/core/EitherTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/Function0Test.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/Function1Test.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/IdTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/ListKTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/MapKTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/NonEmptyListTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/SequenceKTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/SetKTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/SortedMapKTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/TryTest.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/setk.kt, modules/core/arrow-generic/src/test/kotlin/arrow/generic/ProductTest.kt, modules/optics/arrow-optics/src/test/kotlin/arrow/optics/AndMonoidTest.kt, modules/optics/arrow-optics/src/test/kotlin/arrow/optics/std/StringTest.kt, modules/optics/arrow-optics/src/test/kotlin/arrow/optics/std/TupleTest.kt
This PR addresses https://github.com/arrow-kt/arrow/issues/460
The following tests have been updated to use semigroup or monoid laws:
=> Test with semigroup and monoid laws

modules/core/arrow-test/build.gradle
...as the transitive arrow dependencies from kotlintest is older and have different artifact names, which would pollute the client's classpath
=> excluded arrow dependencies from kotlintest in arrow-test.

modules/core/arrow-core/src/main/kotlin/arrow/core/internal/atomic.kt
* Removed Atomic toString functions crashing on Android API 21 [as discussed here](https://github.com/arrow-kt/arrow/issues/1715#issuecomment-546730951)
* Added couple of utility functions for AtomicInt
=> Slight tweaks to atomics

README.md
Avoid the current misunderstanding between `build` with GitHub Actions and `release` with Travis CI.
Replace:
by:
Instead of:
* `GitHub Actions`
* `build` (Travis CI)
it includes:
* `build status` (GitHub Actions)
* `release status` (Travis CI)
It also includes a badge for **latest snapshot**.
=> Documentation: update badges

modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Alternative.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/ListKTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/OptionTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/SequenceKTest.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/listk.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/option.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/sequenceK.kt, modules/mtl/arrow-mtl-data/src/main/kotlin/arrow/mtl/typeclasses/Composed.kt, modules/mtl/arrow-mtl-data/src/test/kotlin/arrow/mtl/EitherTTest.kt, modules/mtl/arrow-mtl-data/src/test/kotlin/arrow/mtl/KleisliTest.kt, modules/mtl/arrow-mtl-data/src/test/kotlin/arrow/mtl/WriterTTest.kt, modules/mtl/arrow-mtl/src/main/kotlin/arrow/mtl/extensions/eithert.kt, modules/mtl/arrow-mtl/src/main/kotlin/arrow/mtl/extensions/kleisli.kt, modules/mtl/arrow-mtl/src/main/kotlin/arrow/mtl/extensions/optiont.kt, modules/mtl/arrow-mtl/src/main/kotlin/arrow/mtl/extensions/statet.kt, modules/mtl/arrow-mtl/src/main/kotlin/arrow/mtl/extensions/writert.kt
Most of these were missing alternative instances, and those that had one via MonadCombine had either no tests or no explicit alternative instance.
I also made combineK default to orElse in alternatives since that is exactly the monoidal behaviour it is supposed to represent.
Btw is there any reason for Alternative laws to be that strict? Looks like a mix of MonadPlus and Alternative laws to me.
=> Add alternative instances to datatypes

modules/core/arrow-test/src/main/kotlin/arrow/test/generators/Generators.kt, modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/MonoK.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/MaybeK.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/SingleK.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/dispatchers.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/flowablek.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/maybek.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/observablek.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/singlek.kt, modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/SingleKTests.kt
I was investigating #1776  but could not reproduce.
This PR enables `ConcurrentSyntax` syntax for `fx` instead of `AsyncSyntax`.
To do so it adds `Dispatchers` instances for all RxJava types and exposes a `(Scheduler) -> CoroutineContext` function.
=> RxJava ConcurrentSyntax & Dispatchers

gradle.properties, modules/docs/arrow-docs/docs/_data/doc-versions.yml, modules/docs/arrow-docs/docs/docs/quickstart/setup/README.md
0.10.3 (2019-11-13)
-------------------
- Release 0.10.3 (#1792) [Francisco Diaz]
- Move `Const.kt` to `core` package (#1789) (#1791) [Stanislav Zemlyakov]
- CI: move from Bitrise to GitHub Actions (#1779) [Rachel M. Carmena]
- Fix broken link to Bracket.kt (#1790) [Sven Tennie]
- Implement Endo Monoid (#1781) [Flavio Corpa]
- Remove unused Fx (#1788) [Simon Vergauwen]
- Add io pool to dispatchers (#1787) [Simon Vergauwen]
- Add Fiber instances (#1783) [Simon Vergauwen]
- Add unsafeCancellableRun (#1784) [Paco]
- Add deprecation notice for unsafe catch (#1785) [Paco]
- RxJava ConcurrentSyntax & Dispatchers (#1782) [Simon Vergauwen]
- Fix the return type of flatMap (#1780) [tatsuyafujisaki]
- #1777: add extension function that converts an Either to an IO (#1778) [Alphonse Bendt]
- CI: move …
=> Release 0.10.3

modules/docs/arrow-docs/docs/docs/arrow/typeclasses/eqk/README.md
this adds the missing _data types_ section to the EqK doc
=> add missing data types section

modules/core/arrow-core-data/src/main/kotlin/arrow/core/Ior.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Semialign.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Unalign.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/ListKTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/MapKTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/OptionTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/SequenceKTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/SortedMapKTest.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/id.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/listk.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/mapk.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/option.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/sequenceK.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/sortedmap.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/SemialignLaws.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/UnalignLaws.kt, modules/docs/arrow-docs/docs/_data/sidebar.yml, modules/docs/arrow-docs/docs/docs/arrow/typeclasses/semialign/README.md, modules/docs/arrow-docs/docs/docs/arrow/typeclasses/unalign/README.md
this adds the Unalign typeclass with instances for common arrow types.
as some instances required the functionality, i have added an extra function to Ior: `toLeftOption`. i hope this is acceptable.
=> Unalign typeclass with instances

modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IOParMap2.kt, modules/mtl/arrow-mtl-data/src/main/kotlin/arrow/mtl/State.kt, modules/mtl/arrow-mtl-data/src/main/kotlin/arrow/mtl/StateT.kt
Fixes typos in `State`, `StateT` and `IOParMap2` documentation.
=> fix docs typos

.gitignore, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/Promise.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/Queue.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/internal/IQueue.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/QueueTest.kt
Work for issue #1438
Lightweight, asynchronous queue for values of A in a Concurrent context F
Offering to a bounded queue at capacity will cause the fiber making the call to be suspended until the queue has space to receive the offer value.
Taking from an empty queue will cause the fiber making the call to be suspended until a value is available to be taken from the queue.
Shutdown: Calling shutdown on a queue will cause all suspend fibers to complete in a QueueShutdownError. Offering or Taking from a queue that has been shutdown will also complete as a QueueShutdownError 
Example gist of multiple producers and consumers using a Queue instance here
https://gist.github.com/richard-gibson/4bb12fac9fcd8179bf4e485fa006b16d
Also added a port of Scala Immutable Queue to be used in internal …
=> Effects Queue

modules/core/arrow-test/src/main/kotlin/arrow/test/laws/ConcurrentLaws.kt, modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/FluxK.kt, modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/FluxKConnection.kt, modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/MonoK.kt, modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/MonoKConnection.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/CoroutineContextRx2Scheduler.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/FlowableK.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/FlowableKConnection.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/MaybeK.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/MaybeKConnection.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/ObservableK.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/ObservableKConnection.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/SingleK.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/SingleKConnection.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/flowablek.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/maybek.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/observablek.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/singlek.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IO.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IORunLoop.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/KindConnection.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/extensions/io.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/internal/CancelableMVar.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/internal/ForwardCancelable.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/internal/IOBracket.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/internal/Utils.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Concurrent.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Fiber.kt
This PR deprecates `KindConnection` from the public API so it can be completely removed in the next major release.
Exposing manual cancellation mechanism likes this has proofed to be error prone.
=> Deprecate KindConnection from public API

modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IO.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IOConnection.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IORunLoop.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt
This PR fixes the issue were IO loses its connection across `suspended` boundaries.
- Currently if you transform an `IO` to `suspended` and then wrap it into another `IO` using `effect` or the default constructor it becomes uncancelable.
- This PR makes the CoroutineContext `IOContext` aware, so it can carry its `IOConnection` within the `CoroutineContext` and share it across multiple `IORunLoop` for the same `IO`.
This makes `suspendCoroutine` the equivalent of `RestartCallback` on the language level, where we can move between callbacks and direct values. This allows us to bridge the connection across the `IO` program since the `Continuation` instance is shared across the whole IO program just like `RestartCallback`.
This also allows for working with `IO` in a style more similar to …
=> Make suspended IO cancelation aware

modules/core/arrow-test/src/main/kotlin/arrow/test/laws/BimonadLaws.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/ComonadLaws.kt, modules/free/arrow-free-data/src/main/kotlin/arrow/free/Cofree.kt, modules/free/arrow-free-data/src/test/kotlin/arrow/free/CofreeTest.kt, modules/ui/arrow-ui-data/src/test/kotlin/arrow/ui/DayTest.kt, modules/ui/arrow-ui-data/src/test/kotlin/arrow/ui/MooreTest.kt, modules/ui/arrow-ui-data/src/test/kotlin/arrow/ui/StoreTest.kt, modules/ui/arrow-ui-data/src/test/kotlin/arrow/ui/SumTest.kt
this PR changes ComonadLaws to use GenK for test data generation (#1858)
i tried to come up with a better GenK for Cofree as suggested here (https://github.com/arrow-kt/arrow/pull/1844/files#r358260447) 
However the tests fail if the Nel has a size > 1. Not sure if this is related to a wrong GenK or is actually a bug uncovered ...
=> ComonadLaws uses GenK for testdata generation

modules/core/arrow-core-data/src/main/kotlin/arrow/core/Validated.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Apply.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/TraverseLaws.kt
I discovered as part of #1832 that the recent changes to introduce `lazyAp` has resulted in the effects of `NonEmptyList.traverse` to no longer maintain their order, causing some of the `Queue` tests to fail.
My assumption was that it was desirable to maintain the effect order with the order of the elements being traversed, so I have included a new law to `Traversable` to compare effect order using a mutable `Ref` with evaluation order of the resulting values.
Upon introducing the new law, `FluxK`, ObservableK`, `FlowableK` were also failing to preserve the ordering of the effects, so I have included changes for those too. I'm not too familiar with these specific types, so it would be worth double checking that the intended semantics have been maintained.
=> Ensure effect order is preserved with Traversable

modules/docs/arrow-docs/docs/_includes/_head-docs.html, modules/docs/arrow-docs/docs/_includes/_head.html, modules/docs/arrow-docs/docs/_layouts/error.html
It tries to fix the missing image:
I tried it with [Twitter Card Validator](https://cards-dev.twitter.com/validator) and it works for https://arrow-kt.io/error.html:
However, it doesn't work for the rest of the pages:
This pull request tries to fix the missing images.
=> DOC: add card image

modules/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/core/Ior.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/core/ListK.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/core/NonEmptyList.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/core/SequenceK.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/core/Try.kt, modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Monad.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/ConstTest.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/ValidatedTest.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/validated.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/ApplicativeLaws.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/MonadLaws.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/SelectiveLaws.kt, modules/free/arrow-free-data/src/test/kotlin/arrow/free/FreeTest.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/FiberTest.kt, modules/mtl/arrow-mtl-data/src/main/kotlin/arrow/mtl/StateT.kt, modules/mtl/arrow-mtl-data/src/test/kotlin/arrow/mtl/StateTTests.kt, modules/mtl/arrow-mtl/src/main/kotlin/arrow/mtl/extensions/statet.kt, modules/streams/arrow-streams/src/main/kotlin/arrow/streams/internal/FreeC.kt, modules/streams/arrow-streams/src/test/kotlin/arrow/streams/internal/FreeCTest.kt, modules/ui/arrow-ui-data/src/test/kotlin/arrow/ui/DayTest.kt
After #1877 I did a quick pass over the laws to go in and use as much of the new generators as possible. This uncovered a few bugs, which were all monad-applicative-consistency bugs where `ap` was defined with a different evaluation order than what most code assumed. (It is now left to right everywhere).
I also quickly converted the nel traverse to use list traverse to benefit from `lazyAp` with no duplicate code. The unsafe-call is safe if `traverse` for lists follows it's laws. (That should now be all collections using `lazyAp`, only ones missing are `Flowable`/`Observable` etc but those are not lawful anyway, so might need to be removed.
=> Monad hierarchy tests genk + lots of small test fixes

README.md, modules/docs/arrow-docs/docs/docs/arrow-core/datatypes/sequencek/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/datatypes/setk/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/datatypes/sum/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/integrations/reactor/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/integrations/retrofit/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/integrations/rx2/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/patterns/glossary/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/quickstart/libraries/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/quickstart/setup/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/typeclasses/align/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/typeclasses/divisible/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/typeclasses/order/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/typeclasses/semialign/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/typeclasses/semigroup/README.md, modules/docs/arrow-docs/docs/docs/arrow-core/typeclasses/unalign/README.md, modules/docs/arrow-docs/docs/docs/arrow-fx/fx/async/README.md, modules/docs/arrow-docs/docs/docs/arrow-fx/monaddefer/README.md, modules/docs/arrow-docs/docs/docs/arrow-incubator/aql/custom/README.md, modules/docs/arrow-docs/docs/docs/arrow-incubator/datatypes/eithert/README.md, modules/docs/arrow-docs/docs/docs/arrow-incubator/datatypes/optiont/README.md, modules/docs/arrow-docs/docs/docs/arrow-incubator/free/recursion/intro/README.md, modules/docs/arrow-docs/docs/docs/arrow-optics/iso/README.md, modules/docs/arrow-docs/docs/docs/arrow-optics/prism/README.md
I noticed a couple of typos as I was reading through the documentation. So I took a few minutes to find any others.
They are all simple spelling typos, except perhaps my change of `unitested` to `unit tested`. At a minimum, `unitested` is missing a `t` in the middle, and needs to be `unittested`. That said, I have always seen it as two words, and could not find any examples of `unittested` as a single word via an internet search. But I did find numerous examples of it as separate words. So I would argue the convention is for it to be two words.
=> Fixed some typos in documentation.

modules/mtl/arrow-mtl-data/src/main/kotlin/arrow/mtl/OptionT.kt, modules/mtl/arrow-mtl-data/src/test/kotlin/arrow/mtl/OptionTTest.kt, modules/mtl/arrow-mtl/src/main/kotlin/arrow/mtl/extensions/optiont.kt
Currently `OptionT.ap` always evaluated both arguments before checking the `Option` in the first one. This leads to fun things like `listOf(1,2,3,4).traverse(OptionT.monad(IO.monad())) { OptionT(IO { println(it); None }) }` printing 1,2,3,4 instead of just 1.
=> Fix OptionT applicative to short-circuit properly

modules/meta/arrow-annotations/src/main/java/arrow/product.kt, modules/meta/arrow-meta/models/src/main/java/arrow/ap/objects/generic/Applicative.kt, modules/meta/arrow-meta/models/src/main/java/arrow/ap/objects/generic/Eq.kt, modules/meta/arrow-meta/models/src/main/java/arrow/ap/objects/generic/HList.kt, modules/meta/arrow-meta/models/src/main/java/arrow/ap/objects/generic/Monoid.kt, modules/meta/arrow-meta/models/src/main/java/arrow/ap/objects/generic/ProductWithoutCompanion.kt, modules/meta/arrow-meta/models/src/main/java/arrow/ap/objects/generic/ProductXXL.kt, modules/meta/arrow-meta/models/src/main/java/arrow/ap/objects/generic/Semigroup.kt, modules/meta/arrow-meta/models/src/main/java/arrow/ap/objects/generic/Show.kt, modules/meta/arrow-meta/models/src/main/java/arrow/ap/objects/generic/Tupled.kt, modules/meta/arrow-meta/src/main/java/arrow/generic/AnnotatedDomain.kt, modules/meta/arrow-meta/src/main/java/arrow/generic/ProductFileGenerator.kt, modules/meta/arrow-meta/src/main/java/arrow/generic/ProductProcessor.kt, modules/meta/arrow-meta/src/test/java/arrow/ap/tests/ProductTest.kt, modules/meta/arrow-meta/src/test/resources/arrow/ap/objects/generic/Applicative.kt, modules/meta/arrow-meta/src/test/resources/arrow/ap/objects/generic/Eq.kt, modules/meta/arrow-meta/src/test/resources/arrow/ap/objects/generic/HList.kt, modules/meta/arrow-meta/src/test/resources/arrow/ap/objects/generic/Monoid.kt, modules/meta/arrow-meta/src/test/resources/arrow/ap/objects/generic/Semigroup.kt, modules/meta/arrow-meta/src/test/resources/arrow/ap/objects/generic/Show.kt, modules/meta/arrow-meta/src/test/resources/arrow/ap/objects/generic/Tupled.kt
This PR can be a partial fix for #909. 
For it I've added option for customising of type class deriving with `@product` annotation as suggested by @raulraja [here](https://github.com/arrow-kt/arrow/issues/909#issuecomment-399795215).   
For correct test running PR #1906 need to be merged.
=> Add deriving option for `@product` annotation

modules/docs/arrow-docs/docs/_data/sidebar-fx.yml, modules/docs/arrow-docs/docs/docs/arrow-fx/queue/README.md, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/Queue.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/QueueTest.kt
This change adds Sliding, Dropping and Unbounded strategies to the `arrow.fx.Queue` implementation.
**Sliding** - *acts as a sliding window when at capacity, dropping oldest queue values to make room for newly offered values*
**Dropping** - *simply drops offered values if the queue is already at capacity*
**Unbounded** - *has no notion of capacity and will happily exhaust all memory of the runtime if given the opportunity*
Please be mindful that I am somewhat new to both Arrow and Kotlin, so I would welcome any feedback, especially regarding conventions :)
=> Adds Sliding, Dropping and Unbounded strategies to arrow.fx.Queue

modules/mtl/arrow-mtl-data/src/main/kotlin/arrow/mtl/WriterT.kt, modules/mtl/arrow-mtl-data/src/test/kotlin/arrow/mtl/WriterTTest.kt
WriterT currently produces the accumulated value backwards. This failed a law in `MonadWriterLaws`. 
The reason this was not caught in tests is because we used a commutative monoid (Int addition) which does not care about order. I changed the tests to run with `ListK` to produce the failed tests.
The first problem was in `flatMap` where the writer returned by `f` was the first argument to combine and the original writer was second.
For reference the semantics in this pr now match the ones from haskell mtl: https://hackage.haskell.org/package/transformers-0.5.6.2/docs/src/Control.Monad.Trans.Writer.Strict.html#line-200
The second problem was that this change broke monad-applicative-consistency, which revealed that `WriterT` also applied the underlying effects in reverse order. Changed that …
=> WriterT inconsistencies

modules/docs/arrow-docs/docs/_data/features.yml
This PR adds the MTL link in the incubator list of the home page.
This closes #1885
=> Missing MTL link

README.md, modules/docs/arrow-docs/docs/docs/arrow-core/quickstart/README.md
The badge of latest snapshot version shows `0.11.0-SNAPSHOT` and we have 2 versions in progress right now.
- Add a new badge to show that we have 2 WIP versions.
- Fix a badge in documentation because it pointed to Travis.
From:
to:
=> Doc: update badges to show both WIP versions

.github/workflows/sync-release-branch.yml
Add an automatic sync for `release/0.11.0` to keep it updated with `master` branch.
It will be executed every day:
- If there are conflicts when merging `master` on `release/0.11.0`, it'll create an issue to solve it.
- If there aren't conflicts, it will create a pull request like: https://github.com/arrow-kt/arrow/pull/1966
=> Add an automatic sync for release/0.11.0

modules/docs/arrow-docs/docs/_data/sidebar-fx.yml
I totally did not mess them up the first time :see_no_evil: 
@calvellido are the links correct now?
Also is there a tool to check broken links at build time for docs? I've been using Hugo for the docs on my prettyprinter and it complains when I add broken links ^^
=> Fix recently added doc links

modules/core/arrow-core-data/src/test/kotlin/arrow/core/ListKTest.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/listk.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/MonadLaws.kt
The problem here was that the autogenerated version of `flatten` for List wraps the outer list in ListK:
```
fun <A> List<List<A>>.flatten(): List<A> = arrow.core.extensions.list.monad.List.monad().run {
arrow.core.ListK(this@flatten).flatten<A>() as kotlin.collections.List<A>
}
```
which causes resolution to fail since ListK flatten would be defined as `Kind<ForListK, Kind<ForListK, A>>` (note the inner Kind) from Monad and also because ListK extends List, therefore the function resolution enters into a recursive loop.
One option is to create a special flatten function in ListKMonad to work with `Kind<ForListK, List<A>>` specifically, so the type resolution finds that one before the other.
Fixes #1726.
=> Fix recursive flatten for stdlib List

.github/workflows/sync-release-branch.yml
GitHub App cannot be added in **Restrict who can push to matching branches** so its provided token cannot be used to sync protected branches.
This PR changes that token by another one who has grants to do that sync.
=> Fix: change token to sync branches

modules/free/arrow-free-data/src/test/kotlin/arrow/free/FreeTest.kt, modules/free/arrow-free-data/src/test/kotlin/arrow/free/TrampolineTest.kt, modules/free/arrow-free/src/main/kotlin/arrow/free/extensions/free.kt
This PR proposes to add the syntax fx to the Free monads.
=> Free should support fx syntax

modules/core/arrow-core-data/src/main/kotlin/arrow/core/AndThen.kt, modules/core/arrow-core-data/src/test/kotlin/arrow/core/AndThenTest.kt
This allows fully a stacksafe version of `Kleisli.flatMap` and similar datatypes.
Currently even using a stacksafe monad for `Kleisli.flatMap` will cause a stackoverflow because it first builds up lots of `Kleisli { d -> run(d)... } ` functions which all collapse once evaluated (and overflow). Note that `Kleisli` will still be stackunsafe if used with a stackunsafe monad, that cannot ever be prevented.
Using `AndThen.flatMap` instead builds up a tower of `Join`'s which will all be collapsed later in the loop.
=> Add a stacksafe variant of Join to AndThen

modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/MonadError.kt, modules/core/arrow-core/src/main/kotlin/arrow/core/extensions/try.kt, modules/core/arrow-test/src/main/kotlin/arrow/test/laws/AsyncLaws.kt, modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/extensions/fluxk.kt, modules/fx/arrow-fx-reactor/src/main/kotlin/arrow/fx/reactor/extensions/monok.kt, modules/fx/arrow-fx-reactor/src/test/kotlin/arrow/fx/FluxKTest.kt, modules/fx/arrow-fx-reactor/src/test/kotlin/arrow/fx/MonoKTest.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/flowablek.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/maybek.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/observablek.kt, modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/singlek.kt, modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/FlowableKTests.kt, modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/MaybeKTests.kt, modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/ObservableKTests.kt, modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/SingleKTests.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/extensions/io.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Async.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Concurrent.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt
=> Fix Async and Concurrent fx block's lazyness

modules/core/arrow-test/src/main/kotlin/arrow/test/laws/BracketLaws.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/internal/IOBracket.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Bracket.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt
Fixes two bugs within Bracket implementation:
* `IOBracket.guaranteeCase` was wrongly doing a flatMap between an IO and a recovery frame, which caused the frame not to be called -> Fixed by calling IO.Bind directly
* `Bracket.guaranteeCase` was calling the bracket function over itself and then again on the use function -> Fixed by executing the bracket over a unit IO for the acquire.
TODO:
* Discuss if we should update the Bracket docs and possibly some docs examples explaining the difference between `bracket(Case)` and `guarantee(Case)`.
Attempt to fix #1996
=> Fix guarantee/guaranteeCase not calling finalizer for error

modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IORace.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/RaceModels.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt
Parallel operations should be scheduled in the order they appear in the parameter list.
Without having an arity-2 & arity-3 operator you cannot create N-arty operators that schedule the tasks in the same order as the parameter list.
=> Add race 3 to guarantee order of scheduling

modules/fx/arrow-fx/src/main/kotlin/arrow/fx/extensions/io.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt
1) do we want to leave `toIO(f: (E) -> Throwable)` and deprecate it in favour of `toIOException`
2) will this be whole? Or add / change any other method?
=> More meaningful mapping Either to 0.11.0 IO #2002

modules/core/arrow-test/src/main/kotlin/arrow/test/laws/ConcurrentLaws.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IO.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Bracket.kt
This PR adds onCancel to `Bracket` which is a specialization over `guaranteeCase`.
It's used frequently in tests, and it can be useful for testing and building inter-op with other effect libraries. See #1939
=> Add onCancel to Bracket

modules/docs/arrow-docs/docs/docs/arrow-core/patterns/errorhandling/README.md
Corrected the compilation problems for code-snippets in [Patterns #Error Handling #MonadError](https://arrow-kt.io/docs/patterns/error_handling/) section.
=> Docs: Corrected code-snippet compilation problems in Error-Handling page

modules/core/arrow-test/src/main/kotlin/arrow/test/laws/ConcurrentLaws.kt, modules/fx/arrow-fx-kotlinx-coroutines/src/test/kotlin/arrow/integrations/kotlinx/CoroutinesIntegrationTest.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/IO.kt, modules/fx/arrow-fx/src/main/kotlin/arrow/fx/typeclasses/Bracket.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt
Because "code is worth a thousand words", following [this comment](https://github.com/arrow-kt/arrow/issues/2018#issuecomment-582947509):
* Add the error instance to Bracket's `onError`
* Remove redeclaration of `onCancel` and `onError` in IO
=> Nits oncancel onerror

modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/FlowableKTests.kt, modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/MaybeKTests.kt, modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/ObservableKTests.kt, modules/fx/arrow-fx-rx2/src/test/kotlin/arrow/fx/SingleKTests.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/IOTest.kt, modules/fx/arrow-fx/src/test/kotlin/arrow/fx/RefTest.kt
As part of the #2029 issue, I would also like to include the concurrency primitive tests into the `Arrow Fx` typeclass laws.
I.e. for any `MonadDefer` instance the `Ref` suite should also pass, this can also be parameterized like `testStackSafety` in case you want a leaner suite.
I'm not sure what the strategy is for `arrow-test` tho, are we planning to keep it a common module that depends on the whole Arrow ecosystem to provide laws for the whole ecosystem? If so shall I move these polymorphic tests there? Or we create a leaner `arrow-test` package, so each library can expose it's own laws in an `arrow-fx-test` module?
I just wanted to start the discussion here since @rachelcarmena is working on the repo organization, I am fine leaving it in Arrow Fx for now. We can also verify the other …
=> Polymorphic Ref Test

modules/fx/arrow-fx/src/test/kotlin/arrow/fx/MVarTest.kt
Re-enabled MVar test _concurrent take and put_
This test was timing out because the number of iterations. Since it's not a stackoverflow test, 5K iterations for a stress test seems sufficient.
=> Re-enabled MVar test

generic-conf.gradle
It's necessary to remove the plugin from the Arrow libraries.
=> Remove buildtimetracker configuration

.github/workflows/check_doc_integration.yml, scripts/project-build.sh
`check` is already included when running `build`
=> Remove duplicated task

docs/move-to-multi-repo/how-to-manage-several-repositories.md, generic-conf.gradle
**Reason**: it's used by other Gradle tasks. However, it's confusing for the users.
=> Configuration: remove installAllWithLocalDeps task from Arrow group

gradle/android-module.gradle, gradle/publication.gradle
Something I came across: `classifier` seems to have been deprecated since Gradle 5.0 and has been replaced with `archiveClassifier` which ironically also produces a warning because the member is private (unless you use `set` o_O). 
See https://github.com/gradle/gradle/issues/8257
@rachelcarmena
=> Fix archive classifier deprecation

docs/how-to-release-arrow.md, docs/libraries/how-to-run-the-website-in-your-local-server.md, scripts/check-doc-integration.sh, scripts/project-locate-doc.sh, scripts/repository-run-website.sh, scripts/site-build.sh, scripts/site-publish.sh, scripts/site-run-ank.sh, scripts/site-run.sh
Reason: `arrow-site` repository will be moved to a just Jekyll content repository without documentation validation because landscape code snippets have been located into their corresponding repositories. In this way they will be updated according to Arrow libraries changes without waiting to the release time.
Changes:
* Remove documentation validation for `arrow-site`
* Adapt configuration.
* Remove unnecessary steps.
=> Configuration: re-locate landscape code snippets

arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/MonoidInvariant.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/andthen.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/either.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/hashed.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/listk.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/mapk.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/nonemptylist.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/sortedmap.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/tuple.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/validated.kt
Some of the old `@extensions` interfaces were still missing `@Deprecated` notice.
=> Add missing extension deprecations

arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ParTraverseValidated.kt, arrow-libs/fx/arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ParTraverseValidatedTest.kt
Use Arrow Core's `traverseValidated` instead of a custom one.
=> CU-ev1h79 Replace poc code in Arrow Fx Coroutines

arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/ior.kt
Deprecates `component1` and `component2` for `Ior`.
=> CU-ev11vr Deprecate component1 and component2

arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/SuspendConnection.kt
`CancelToken` will be removed together with `cancelable` and `cancelableF` in favor of KotlinX's `suspendCoroutineCancellable` builder.
=> CU-et6dqh Deprecate CancelToken and Disposable

arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ConcurrentVar.kt
`ConcurrentVar` has the same semantics as `Channel(1)`, which is a `Channel` with the size for a single element. So it can also be `empty` or `filled` and it provides suspending semantics upon `send` and `receive`, it covers more use-cases as `ConcurrentVar` does.
=> CU-et6b7a Deprecate ConcurrentVar

arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Sequence.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/set.kt, arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/SequenceKTest.kt, arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/SetKTest.kt, arrow-libs/core/arrow-core-test/src/main/kotlin/arrow/core/test/generators/Generators.kt
The `Monoid` instance for `Sequence` and `Set` were resulting in `StackOverflow` since they were delegating to their `Monoid#plus` function instead of the `plus` function from the standard library.
=> CU-ev1jrd Fix Monoid for Sequence and Set

arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Option.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Sequence.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/TupleN.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Validated.kt, arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/typeclasses/TraverseTest.kt
This PR fixes two issues for traversing an `Sequence`.
- Sequence#traverse was implemented using `foldRight` without `Eval` which first materialises the whole list in memory. This _always_ results in an `OOM` even if the transformation of `traverse` results in a _short-circuit_.
- 
- Fix `apEval` for `Either` and `Option` to properly _short-circuit_.
=> CU-ev2g8f Fix Sequence#travserse, Option#apEval & Either#apEval

arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/RacePair.kt, arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/RaceTriple.kt
This PR deprecates all code in `RacePair.kt` and `RaceTriple.kt` since they break guarantees provided with KotlinX Coroutines structured coroutines and KotlinX offers other/safer mechanisms to cover this use-case.
=> CU-et6c7a Deprecates racePair and raceTriple

arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Option.kt
The `Option` datatype was deprecated in favor of `Nullable` types because the latter is faster than boxed types like `Option`. However,  it will be supported by Arrow again to interop with Java-based libraries that use `null` as signal or interruption value like [ReactiveX RxJava](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#nulls).
=> Undeprecate Option data type

arrow-site/docs/docs/io/README.md
as in: the resulting user _has been processed_ by this function
=> receiver-constrained example function should be renamed

arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt
These constructors duplicate the behavior of the actual constructors except they're imported with `import arrow.core.Left` instead of `arrow.core.Either.Left` so they're redundant.
=> CU-f31wbh Deprecate top-level Left & Right Either constructors

arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/TupleN.kt, arrow-libs/fx/arrow-fx-stm/src/main/kotlin/arrow/fx/stm/STM.kt
2 APIs were not deprecated when I removed them in https://github.com/arrow-kt/arrow/pull/2293.
This PR deprecates these two APIs for 0.12.0 before removal in 0.13.0
=> CU-f540fg Deprecate remaining tuple2 APIs

arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/ListK.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/SequenceK.kt
Review in https://github.com/arrow-kt/arrow/pull/2292 revealed a perf issue in mapN for `Iterable`. This PR fixes it for `0.12.0` so it can be merged into `0.13.0` as well.
The issue being that `flatMap` creates intermediate `ArrayList`, and we're thus creating a lot of `ArrayList` whilst we can get away with creating a single `ArrayList`.
=> Remove creation of intermediate lists in mapN

arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/EitherTest.kt
I ran in an unlikely scenario where `a == b` which made this test fail with a false negative, and as a result it also failed the build.
This small PR removes the assumption that both generated values are never the same/
=> EitherTest#contains - check that arbitrary values aren't the same

arrow-docs/docs/arrow/typeclasses/monoid/README.md, arrow-docs/docs/arrow/typeclasses/semigroup/README.md, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Semigroup.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Semiring.kt
Adapt Monoid, Semigroup and Semiring docs to the new typeclass syntax
=> Update typeclasses docs

arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Iterable.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/NonEmptyList.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Sequence.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/map.kt, arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/IterableTest.kt, arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/MapKTest.kt, arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/NonEmptyListTest.kt, arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/SequenceKTest.kt, arrow-libs/core/arrow-core-test/src/main/kotlin/arrow/core/test/UnitSpec.kt, arrow-libs/core/arrow-core-test/src/main/kotlin/arrow/core/test/generators/Generators.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/list/apply/ListKApply.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/listk/apply/ListKApply.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/nonemptylist/apply/NonEmptyListApply.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/sequence/apply/SequenceKApply.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/sequencek/apply/SequenceKApply.kt, arrow-site/docs/docs/datatypes/nonemptylist/README.md
This PR updates/fixes some `zip` implementations and adds tests for it.
It also deprecates `mapN` for collections, which were cartesian builders. For collections, this easily results in really big lists that make the JVM OOM.
Example of dangerous usage:
```kotlin
val x: List<Int> = listOf(1, 2, 3, 4, 5, 6)
// OOMs
val result = mapN(x, x, x, x, x, x, x, x, x, x, ::Tuple10)
```
This tries to create a list with 6^10 (60466176) elements and as a result OOMs. As you can see this easily results in bad code since here we're only using a list with 6 elements and it already results in problematic code.
Since this pattern isn't so common and is only safe with low arities we will recommend to simply use `flatMap/map` chains instead.
=> CU-fh2vcf - Deprecate mapN and fix zip for collections

arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/const/apply/ConstApply.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/either/apply/EitherApply.kt
Fixes missing import for Either#mapN deprcation and removes unneeded import for Const.
=> Fix Const & Either mapN deprecation

arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/Resource.kt, arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/UnsafePromise.kt, arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/startCoroutineCancellable.kt, arrow-libs/fx/arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ResourceTest.kt
This PR cleans up the API for Arrow Syntax for Arrow 0.13.0 (1.0.0). The API review can be found [here](https://github.com/nomisRev/arrow-api-review/pull/2/files?file-filters%5B%5D=.api)
- Revert CancellableContinuation changes
- Remove Resource.unit
- Clean-up Resource traverse API
- Add deprecation UnsafePromise
=> CU-fv6x6d Clean up Arrow Fx based on API Review

arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/core/partials.kt, arrow-libs/core/arrow-syntax/src/main/kotlin/arrow/syntax/function/partials.kt
In https://github.com/arrow-kt/arrow/pull/2328, we renamed `partiallyN` to `partially` but this conflicts for functions that have the same type. This needs to be reverted, so the user an explicitly choose which parameter that needs to be partially applied.
Such as the following test:
```kotlin
"partially" {
val sum5ints = { a: Int, b: Int, c: Int, d: Int, e: Int -> a + b + c + d + e }
val sum4intsTo10 = sum5ints.partially5(10)
val sum3intsTo15 = sum4intsTo10.partially4(5)
val sum2intsTo17 = sum3intsTo15.partially3(2)
sum2intsTo17(1, 2) shouldBe 20
val prefixAndPostfix = { prefix: String, x: String, postfix: String -> "$prefix$x$postfix" }
val helloX = prefixAndPostfix.partially1("Hello, ").partially2("!")
helloX("Arrow") shouldBe "Hello, Arrow!"
}
```
=> Revert partially without explicit arity

arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Ior.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/NonEmptyList.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Sequence.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Tuple3.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Validated.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Applicative.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/extensions/nonemptylist/monad/NonEmptyListMonad.kt
This PR fixes breaking changes between 0.11.0 & 0.12.0 in `Tuple3#reverse` which was abruptly removed.
It also removes some newly added code that is not desired and got deprecated immediately, the reason these were added along the way was that they were used in some APIs like `traverseXXX`.
- Either#apEval
- Ior#apEval
- Validated#apEval
- NonEmptyList#selectM
- Monoid<A>#lift
This was observed on the API review repo: https://github.com/nomisRev/arrow-api-review/pull/2
After updating it with merged PRs:
- https://github.com/arrow-kt/arrow/pull/2330
- https://github.com/arrow-kt/arrow/pull/2329
- https://github.com/arrow-kt/arrow/pull/2328
=> Clean-up new code & breaking changes since 0.12.0

arrow-libs/fx/arrow-fx-coroutines-test/src/test/kotlin/arrow/fx/coroutines/PredefTest.kt, arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/ConcurrentVar.kt, arrow-libs/fx/arrow-fx-coroutines/src/main/kotlin/arrow/fx/coroutines/UnsafePromise.kt, arrow-libs/fx/arrow-fx-coroutines/src/test/kotlin/arrow/fx/coroutines/ConcurrentVarTest.kt, arrow-libs/fx/arrow-fx-stm/src/main/kotlin/arrow/fx/stm/STM.kt, arrow-libs/fx/arrow-fx-stm/src/main/kotlin/arrow/fx/stm/TMap.kt
It also removes some newly added code that is not desired and got deprecated immediately.
- ConcurrentVar#modify
- ConcurrentVar#modify_
- ConcurrentVar#withConcurrentVar
- TMap<K, V>#plusAssign
Also, this PR reverts making `UnsafePromise` public in `0.12.0`
=> Arrow Fx: Clean-up new code & breaking changes since 0.12.0

arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Ior.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/Validated.kt, arrow-libs/core/arrow-core-data/src/main/kotlin/arrow/core/predef.kt, arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/IorTest.kt, arrow-libs/core/arrow-core-data/src/test/kotlin/arrow/core/ValidatedTest.kt
This PR adds tests for custom implementation of Validated#zip and Ior#zip and fixes 2 exposed bugs.
=> Fix null bug in Validated#zip & Ior#zip

arrow-libs/optics/arrow-optics/src/main/kotlin/arrow/optics/Traversal.kt, arrow-libs/optics/arrow-optics/src/main/kotlin/arrow/optics/std/tuple.kt
Small follow up for https://github.com/arrow-kt/arrow/pull/2336
=> Fix redundant tuple naming

.github/workflows/publish_arrow-stack.yml
All the steps for Arrow Stack are using a working directory so the setup should appear after the checkout.
=> Configuration: fix steps order

arrow-site/docs/_data/doc-versions.yml, arrow-site/docs/_includes/_sidebar-doc-versions.html
Remove 0.9.0 from the list and add its entry explicitly because it doesn't follow the same URLs from 0.10.x
=> Documentation: fix versions menu

arrow-libs/core/arrow-meta/src/main/java/arrow/optics/IsosFileGenerator.kt
`Iso` generation is still using `a`, `b`, `c`, etc instead of `first`, `second` and so on.
I think the meta tests are currently disabled, but this is okay since we're moving to Arrow Meta as soon as Koltin 1.5 is released which has much better testing facilities.
Reported on Kotlin Slack: https://kotlinlang.slack.com/archives/C5UPMM0A0/p1617199987116700
=> Fix Iso generation using letters instead of named params

.github/workflows/publish.yml, .github/workflows/publish_arrow-stack.yml, CONTRIBUTING.md, README.md, RELEASE.md, arrow-libs/gradle.properties, arrow-libs/gradle/publication.gradle, arrow-libs/settings.gradle, arrow-site/docs/docs/quickstart/README.md, arrow-stack/build.gradle
- Get credentials for Sonatype.
- Create signing resources:
```
gpg2 --gen-key
gpg2 --keyserver hkp://pool.sks-keyservers.net:80 --send-keys [KEY-ID]
gpg -a --export-secret-key [KEY-ID] > [KEY-ID].asc
```
- Create new secrets:
* `SONATYPE_USER`
* `SONATYPE_PWD`
* `ORG_GRADLE_PROJECT_signingKey`
* `ORG_GRADLE_PROJECT_signingPassword`
- Replace OSS JFrog snapshots repository by Sonatype OSSRH snapshots repository.
- Replace Bintray repository by Sonatype OSSRH releases repository (a staging repository is created before).
- Check signing resources to be able to publishToMavenLocal without failures.
- Update badges.
- Update documentation.
- Remove Bintray secrets.
- Notify the new SNAPSHOTS repository.
- Remove `1.0.0-SNAPSHOT` from OSS JFrog to avoid misunderstandings.
- Update `arrow-meta` …
=> Configuration: remove Bintray et al. (step 3)

arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Ior.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Iterable.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/NonEmptyList.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Option.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Sequence.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/SortedMapK.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Validated.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/map.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/predef.kt
FoldRight and similar are useless in most cases in arrow atm.
- No kinds, without kinds we know that all implementations of foldRight atm are on non-lazy types that call the fold in place
- A consequence of the above is that all of these folds are `inline` and can thus short circuit using non-local returns.
A quick overview of all the types of folds present in arrow atm:
- `foldLeft = fold` This iterates over the elements in order left to right and accumulates along the way
- `foldRight` (without `Eval`) This iterates over the elements in order right to left. I'd argue that this is hardly ever what anyone wants or needs and writing `reverse().fold` isn't that annoying or common to warrant a shortcut (especially not one named `foldRight`)
- `foldRight` (with `Eval`): This returns a lazy …
=> Deprecate foldRight and all lazy folds

arrow-site/docs/docs/fold/README.md
Regarding https://github.com/arrow-kt/arrow/issues/2379
=> Fix #2379 - Formatting of link in fold docs page

README.md, arrow-site/docs/docs/quickstart/README.md
The current badge for SNAPSHOT is not showing the `latest` version from [maven-metadata.xml](https://oss.sonatype.org/service/local/repositories/snapshots/content/io/arrow-kt/arrow-core/maven-metadata.xml).
The new badge is based on a custom query.
=> Documentation: fix latest snapshot badge

.github/scripts/set-env.sh, .github/workflows/build.yml, .github/workflows/publish.yml
It's the reason why multiple staging repositories are created when publishing.
It also reverts #2385.
=> Configuration: disable parallel execution when publishing

arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Ior.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Iterable.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/NonEmptyList.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Option.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Sequence.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/Validated.kt, arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/map.kt, arrow-libs/core/arrow-core/src/test/kotlin/arrow/core/EitherTest.kt, arrow-libs/core/arrow-core/src/test/kotlin/arrow/core/IorTest.kt, arrow-libs/core/arrow-core/src/test/kotlin/arrow/core/IterableTest.kt, arrow-libs/core/arrow-core/src/test/kotlin/arrow/core/MapKTest.kt, arrow-libs/core/arrow-core/src/test/kotlin/arrow/core/NonEmptyListTest.kt, arrow-libs/core/arrow-core/src/test/kotlin/arrow/core/OptionTest.kt, arrow-libs/core/arrow-core/src/test/kotlin/arrow/core/SequenceKTest.kt, arrow-libs/core/arrow-core/src/test/kotlin/arrow/core/ValidatedTest.kt
- added strong `Option<A>.pairLeft(l: L): Option<Pair<L, A>>` and `Option<A>.pairRight(r: R): Option<Pair<A, R>>`
- added `List<Option<A>>.flattenOption(): List<A>`
- added `Map<K, Option<V>>.filterOption(): Map<K, V>` 
- added `Sequence<Option<A>>.filterOption(): Sequence<A>` 
- added `F<A>.traverseOption(f: (A) -> Option<B>): Option<F<B>>` and `F<Option<T>>.sequence(): Option<F<T>>` for either, option, validated, ior, lists, nonemptylists, sequence, and maps.
- added some missing tests for Traverse
fixes #2374
=> add common extensions for option

arrow-libs/core/arrow-core/src/test/kotlin/arrow/core/EitherTest.kt
Hi everyone!
My first PR. Improving Either test coverage.
=> More Either tests

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/partials.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/FunctionSyntaxTest.kt
Added missing `partiallyX` for arity over 5 and suspending functions.
It is hard to define a limit for partial application as a use case may require several parameters -> I decided to add all possibilities.
=> Add partiallyX for arity over 5 and suspend functions

arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Every.kt, arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Fold.kt, arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Getter.kt, arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Iso.kt, arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Lens.kt, arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Optional.kt, arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Prism.kt, arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Setter.kt, arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Traversal.kt
These all must be specified, otherwise the compiler is unable to determine which function to call when there are multiple (e.g. when using `Getter compose Getter` to create a `Getter` instead of a `Fold`).
Closes #2414
=> Specify type variance for `compose` and `plus` methods across the lenses

.github/workflows/publish.yml, .github/workflows/publish_arrow-stack.yml, .github/workflows/publish_doc.yml
This feature wasn't included when joining the repositories.
Added for failures when publishing (to avoid `red` flag into `main` branch).
=> Configuration: recover issues creation

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Comparison.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/ComparisonKtTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/extensions/NumberInstancesTest.kt
Due to the way that floating numbers work in Kotlin MPP, we cannot support comparison operators for them (`Float`, `Double`).
https://kotlinlang.org/docs/equality.html#floating-point-numbers-equality
=> Deprecate Float & Double comparison operators

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Option.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/OptionTest.kt, arrow-libs/core/arrow-core/src/jvmTest/java/arrow/core/OptionUsage.java
The current version of `catch` that has `(Throwable) -> Unit` as recover action does not allow to handle the exception in any usable way. The only possible action is a side effect (ie. to log the exception).
I think that we should have the possibility to recover from `Throwable` to `Opton<A>` -> recover type should be `(Throwable) -> Option<A>`.  This is much more useful than executing some side effect.
I have changed the current function. Maybe it should be deprecated and a new one added?
=> Allow to recover to Option<A> in Option.catch

arrow-libs/core/arrow-continuations/src/commonTest/kotlin/generic/SuspendingComputationTest.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/computations/either.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/computations/nullable.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/computations/option.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/OptionTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/computations/NullableTest.kt
This PR adds some convenient syntax for mixing the `nullable` effect/monad with other effect/monads such as `either`, `option` and `nullable` itself.
It also deprecates the currently gotcha behavior of nullable `bind` syntax in `option { }`.
Example of gotcha behavior:
```kotlin
either<Int, String> {
option<Int> {
Either.Left(1).bind() // Expected to short-circuit but uses `fun <A> A?.bind(): A` instead and *doesnt* short-circuit,
}.fold({ "0" }, Int::toString)
}
```
This was originally proposed in #2311.
The proposed `require`/`requireNotNull` syntax conflicts with with `kotlin.require` and `kotlin.requireNotNull` which is auto-imported and it can be easily confused. If it's mistake it leads to an exception instead of participating in the computation block.
=> Add ensure, and ensureNotNull in computation DSL

arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Resource.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/ResourceTest.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmMain/kotlin/arrow/fx/coroutines/ResourceExtensions.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/ResourceTestJvm.kt
This PR adds:
- First parallel operator for `Resource` `parZip`. This will allows for encoding `parZip` to `arity-9, add `parTraverseResource` etc.
- a new constructor for Java's `AutoCloseable`, which was missing next to `Closeable`.
- It updates the `map` operator to support `suspend` and adds `tap` combinator.
=> Resource parZip & fromAutoCloseable

arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/AtomicTest.kt
There was a failing test on JS for values `x, y, z => 1f, 1f, 0f`.
It does a reference check in `compareAndSet` underneath, and on JS this made the test fail for `x` and `y` of the same value.
=> Fix test impl atomic on JS

.github/workflows/build_doc.yml, .github/workflows/build_js.yml, .github/workflows/build_jvm.yml
This PR changes a couple things to make deduplicate some tasks we run more than once on CI.
- Remove `jvm` from `build` step and turn it into `build_js`.
- Rename build/verify steps to running tests, since we removed ktlint and splits running the different platforms in different actions.
- Run KtLint only once in documentation step
=> Optimise Github Actions

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Option.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Validated.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/EitherTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/OptionTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/ValidatedTest.kt
Addresses https://github.com/arrow-kt/arrow/issues/2416 and https://github.com/arrow-kt/arrow/issues/2410
In the second case in https://github.com/arrow-kt/arrow/issues/2410 `tap` is the same as `foreach` and there is also `tapNone`
=> CU-m3dyef Either, Option and Validated tap effect

arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/ParTraverse.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/ParTraverseEither.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/ParTraverseValidated.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Platform.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Race2.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Race3.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/ParTraverseValidatedTest.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/RaceNTest.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/RaceNJvmTest.kt, arrow-site/docs/_code/fx-home-code.md
This an binary breaking change, and this is a "semi" API breaking change.
Semi-breaking in that it only breaks for method references since the Kotlin compiler doesn't automatically ignore the unused receiver scope. Only `parSequence` can be overloaded without causing type ambuigity.
```kotlin
suspend fun add(i: Int): Int = i + 1
listOf(1, 2, 3).parTraverse(::add) // expected CoroutineScope.() -> Int
```
=> Expose CoroutineScope in Fx

arrow-site/docs/_data/sidebar-core.yml, arrow-site/docs/docs/core/README.md, arrow-site/docs/docs/dsl/README.md, arrow-site/docs/docs/optics/README.md
In preparation for the release adds the same overview box that was on Fx in Core and Optics.
Meta still needs a full menu overhaul and the content that would appear there needs more tinkering.
@israelperezglez I noticed we need to recompile CSS with new ids for each page, currently, I'm using `quickstart-coroutines-item` so it renders properly. The optics one does not render properly because the content seems to have a fixed height.
I also noticed the go-to `Maven` setup button does not work when clicked from the content menu.
@nomisRev Made some changes to the optics docs to clarify regarding companions. Not sure if you want the overview featured differently or with fewer data types.
=> Overview boxes in Core and Optics CU-m560pn CU-u3qa4p

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Ior.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Iterable.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Validated.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/EitherTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/IorTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/IterableTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/ValidatedTest.kt
=> introduce traverse and sequence for nullable types

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Validated.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/ValidatedTest.kt
As discussed on slack [https://kotlinlang.slack.com/archives/C5UPMM0A0/p1632399994123800] proposing a andThen method for `Validated` to easier chain Validations without going through `withEither`
=> Adds a andThen extension method to Validated to chain Validated

.github/scripts/set-env.sh, .github/workflows/publish.yml, arrow-libs/ank/build.gradle, arrow-libs/build.gradle.kts, arrow-libs/core/arrow-core-test/build.gradle.kts, arrow-libs/core/arrow-meta/build.gradle.kts, arrow-libs/fx/arrow-fx-coroutines-test/build.gradle.kts, arrow-libs/optics/arrow-optics-test/build.gradle.kts, arrow-site/gradle.properties, gradle/libs.versions.toml
- Bump `arrow-gradle-config` plugins to 0.3.2
- Set `group` and `version` in `arrow-libs`
- Disable Dokka in some projects
- Improve publish workflow
=> Improve Gradle config

.github/workflows/publish.yml, .github/workflows/pull_request.yml, build.gradle.kts
Now that the build is green again, we should attempt to run `build` for all platforms again.
=> [Github Action] Run build on all platforms

arrow-libs/core/arrow-core-retrofit/src/test/kotlin/arrow/retrofit/adapter/either/ArrowEitherCallAdapterTest.kt, arrow-libs/core/arrow-core-retrofit/src/test/kotlin/arrow/retrofit/adapter/either/ArrowResponseEAdapterTest.kt, arrow-libs/core/arrow-core-retrofit/src/test/kotlin/arrow/retrofit/adapter/retrofit/SuspendApiTestClient.kt, arrow-libs/core/arrow-core-retrofit/src/test/kotlin/arrow/retrofit/adapter/retrofit/TestSuspendApiClient.kt
Current test configuration reuses one `MockWebServer` instance across all tests. This is incorrect, as any changes to the mock server configuration influence subsequent tests.
To experience the problem on the current `main` branch, change the test order in that you move any test asserting a successful response, e.g. `should return ResponseMock for 200 with valid JSON`, after the last test `should throw when server disconnects`. The test for a successful response will now start failing.
This PR fixes that in that the `server` and `service` variables have been made `lateinit var`s and are initialized before any test.
To test if this fixes the problem, just change the test order in the way described above on this PR's branch and see that the tests all still pass regardless of their order.
I …
=> Fix Retrofit adapter test configuration

.github/workflows/publish.yml
The `publish_doc` can't access the Arrow version defined as an output for the `build` job because it doesn't depend on that job directly. So we need to propagate that value from the `publish` job to be able to read the version of the library.
=> Propagate Arrow version to publish_doc job

CONTRIBUTING.md
Some small updates to the contributing guide:
* Mention in code snippets policy that code snippets have to be annotated with Knit
* Update code snippet link and example (the link pointed to an old snippet using `ank`)
* Define more precisely that the `apiDump` task can be called only for changed subproject (no need to run it for the whole project when only suproject has changed).
=> Update contributing guide with Knit

arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/CircuitBreaker.kt
=> fix typo comment of circuitbreaker

arrow-libs/optics/arrow-optics-ksp-plugin/build.gradle.kts
Since #2636 alpha releases are broken, as there are no mpp dependencies for ios or other native targets
e.g.: :arrow-optics-ksp-plugin:generateMetadataFileForIosArm32Publication  fails
=> revert ksp plugin to jvm only

arrow-site/docs/docs/optics/README.md
This is the final step in fixing #2646: adding docs explaning how to make IntelliJ aware of the generated code.
=> [Optics KSP] Update docs to talk about IDEs

arrow-site/docs/_data/sidebar-core.yml, arrow-site/docs/docs/arrow/core/continuations/README.md
On some devices the long names aren't displayed properly (or only partially) in the widget
=> fix sitemap titles

arrow-libs/fx/arrow-fx-coroutines/api/arrow-fx-coroutines.api, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Resource.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/ResourceTest.kt
=> Resource.asFlow

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/OpticsProcessor.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/domain.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/dsl.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/isos.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/lenses.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/optional.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/prism.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/processor.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/LensTests.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/Utils.kt
resolves #2618 
Status:
**In progres**
=> fix imports for ksp plugin

arrow-site/docs/docs/core/README.md, arrow-site/docs/docs/fx/README.md, arrow-site/docs/docs/optics/README.md, arrow-site/docs/docs/quickstart/README.md
remove kapt docs 
set up for ksp plugin with Maven is still under investigation https://github.com/google/ksp/issues/47
=> Update Set up Documentation

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Sequence.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/SequenceKTest.kt
Rename to either `sequence` or `traverse`: 
- sequenceEither
- sequenceValidated
- sequenceOption
- traverseEither
- traverseOption
- traverseValidated
Deprecate:
- some
=> rename Sequence sequenceX, traverseX and deprecate Sequence.some

arrow-libs/fx/arrow-fx-coroutines/api/arrow-fx-coroutines.api, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Resource.kt
fixes when expression with Resource:
currently
```kotlin
when(val x: Resource<Int> = myResource()) {
is Bind<*,*> -> ...
is Allocate -> ...
is Defer -> ...
is Dsl -> ... // error bc this is internal
else -> ... // only work around
}
```
after this PR, the when expression is exhaustive and there is no need to use else: 
```kotlin
when(val x: Resource<Int> = myResource()) {
is Bind<*,*> -> ...
is Allocate -> ...
is Defer -> ...
is Dsl -> 
}
```
=> define Dsl as public

.github/workflows/publish-landing-page.yaml, .github/workflows/publish.yml
The landing page for the Arrow site should only be updated when there are changes in the `arrow-site` folder and shouldn't be related to any other GitHub Action workflow for generating and publishing artifacts.
Having a dedicated workflow for the landing page will help us to simplify the rest of the workflows by removing unrelated steps.
=> Add new workflow for publishing the landing page

.github/workflows/publish.yml
To avoid picking incorrect tags, we need to do only a checkout merging all jobs into one in the 	 `publish` workflow.
=> Fix publish sync

arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Resource.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/ResourceTest.kt
Solves an issue with the new `resource { }` DSL not releasing resources in the reverse order in which they were acquired.
=> invert resource release order

.github/workflows/publish-landing-page.yaml
The workflow for publishing the landing page runs on Ubuntu which doesn't have Bundler installed by default, so we need to add the install command to access the tool.
=> Add command to install bundler

gradle/libs.versions.toml
there was an error introduced in 0.10.2, which is still under development, to maintain compatibility to Arrow 1.1.2 this PR reverts it back to 0.10.1, 
For context, Kotlin slack discussion:
https://kotlinlang.slack.com/archives/C8UK6RTHU/p1653734285366849
=> revert arrow-gradle-config to 0.10.1

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/continuations/NullableSpec.kt
This tiny change will remove a warning printed by `./gradlew test`:
```
WARN: Duplicated test name short circuit null. To disable this message, set DuplicateTestNameMode to None.
WARN: Duplicated test name short circuit null. To disable this message, set DuplicateTestNameMode to None.
```
=> Rename duplicated test

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/EitherTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/EvalTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/IterableTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/OptionTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/ValidatedTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/continuations/OptionSpec.kt
This PR removes following compilation/test warnings (https://github.com/arrow-kt/arrow/issues/219):
* EitherTest.kt: (313, 24): 'negativeInts(Int = ...): Arb<Int>' is deprecated. use negativeInt. Deprecated in 5.0.
* EvalTest.kt: (3, 32): 'EvalEffect<A>' is deprecated. Deprecated in favor of Effect DSL: EffectScope
* EvalTest.kt: (4, 32): 'RestrictedEvalEffect<A>' is deprecated. Deprecated in favor of Eager Effect DSL: EagerEffectScope
* EvalTest.kt: (5, 32): 'eval' is deprecated. Deprecated in favor of the Effect or EagerEffect Runtime
* IterableTest.kt: (168, 13): Variable 'expected' is never used
* ValidatedTest.kt: (207, 69): 'combineAll(Monoid<A>): A' is deprecated. use fold instead
* WARN: Duplicated test name catch should return Some(result) when f does not throw
=> Fix some compilation and test warnings

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Validated.kt
Adds a merge function to Validated, like the one found in Either
=> add merge to validated

arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Schedule.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/CircuitBreakerTest.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-schedule-02.kt
Replace:
* `Duration.inNanoseconds` with `Duration.toDouble(NANOSECONDS)`
* `kotlin.time.nanoseconds` with `kotlin.time.Duration.Companion.nanoseconds`
* `kotlin.time.milliseconds` with `kotlin.time.Duration.Companion.milliseconds`
* `kotlin.time.secodns` with `kotlin.time.Duration.Companion.seconds`
https://github.com/arrow-kt/arrow/issues/219
=> Fix compilation warnings by replacing usages of deprecated methods

.github/workflows/generate-alpha-tag.yaml, .github/workflows/generate-tag.yaml, .github/workflows/publish.yml, .github/workflows/pull_request.yml, arrow-libs/core/arrow-continuations/build.gradle.kts, arrow-libs/core/arrow-core-retrofit/build.gradle.kts, arrow-libs/core/arrow-core/build.gradle.kts, arrow-libs/fx/arrow-fx-coroutines/build.gradle.kts, arrow-libs/fx/arrow-fx-stm/build.gradle.kts, arrow-libs/optics/arrow-optics-ksp-plugin/build.gradle.kts, arrow-libs/optics/arrow-optics-reflect/build.gradle.kts, arrow-libs/optics/arrow-optics/build.gradle.kts, gradle.properties
The [1.1.3-alpha.23](https://github.com/arrow-kt/arrow/tree/1.1.3-alpha.23) release on the Arrow Fx Coroutines Utils project, and confirmed that the `kotlin.mpp.enableCompatibilityMetadataVariant` flag fixes the issue.
To still run tests on CI, and to still publish Arrow with the `kotlin.mpp.enableCompatibilityMetadataVariant` I made it `false` by default and inject it during the `publish.yml`.
This way CI can still run with the same guarantees as before.
=> Fix build, inject kotlin.mpp.enableCompatibilityMetadataVariant in CI

arrow-libs/core/arrow-core-test/api/arrow-core-test.api, arrow-libs/core/arrow-core-test/src/commonMain/kotlin/arrow/core/test/Platform.kt, arrow-libs/core/arrow-core-test/src/commonMain/kotlin/arrow/core/test/UnitSpec.kt, arrow-libs/core/arrow-core-test/src/commonMain/kotlin/arrow/core/test/concurrency/SideEffect.kt, arrow-libs/core/arrow-core-test/src/commonMain/kotlin/arrow/core/test/generators/Generators.kt, arrow-libs/core/arrow-core-test/src/commonMain/kotlin/arrow/core/test/generators/utils.kt, arrow-libs/core/arrow-core-test/src/commonMain/kotlin/arrow/core/test/laws/FxLaws.kt, arrow-libs/core/arrow-core-test/src/commonMain/kotlin/arrow/core/test/laws/Law.kt, arrow-libs/core/arrow-core-test/src/commonMain/kotlin/arrow/core/test/laws/MonoidLaws.kt, arrow-libs/core/arrow-core-test/src/commonMain/kotlin/arrow/core/test/laws/SemigroupLaws.kt, arrow-libs/core/arrow-core-test/src/commonMain/kotlin/arrow/core/test/laws/SemiringLaws.kt, arrow-libs/core/arrow-core-test/src/jsMain/kotlin/arrow.core/test/Platform-js.kt, arrow-libs/core/arrow-core-test/src/jvmMain/kotlin/arrow/core/test/Platform-jvm.kt, arrow-libs/core/arrow-core-test/src/jvmMain/kotlin/arrow/core/test/generators/GeneratorsJvm.kt, arrow-libs/core/arrow-core-test/src/nativeMain/kotlin/arrow/core/test/Platform-native.kt, arrow-libs/fx/arrow-fx-coroutines-test/src/commonMain/kotlin/arrow/fx/coroutines/ArrowFxSpec.kt, arrow-libs/fx/arrow-fx-coroutines-test/src/commonMain/kotlin/arrow/fx/coroutines/predef-test.kt, arrow-libs/fx/arrow-fx-coroutines-test/src/jvmMain/kotlin/arrow/fx/coroutines/predef-test-jvm.kt, arrow-libs/optics/arrow-optics-test/src/commonMain/kotlin/arrow/optics/test/laws/IsoLaws.kt, arrow-libs/optics/arrow-optics-test/src/commonMain/kotlin/arrow/optics/test/laws/LensLaws.kt, arrow-libs/optics/arrow-optics-test/src/commonMain/kotlin/arrow/optics/test/laws/OptionalLaws.kt, arrow-libs/optics/arrow-optics-test/src/commonMain/kotlin/arrow/optics/test/laws/PrismLaws.kt, arrow-libs/optics/arrow-optics-test/src/commonMain/kotlin/arrow/optics/test/laws/SetterLaws.kt, arrow-libs/optics/arrow-optics-test/src/commonMain/kotlin/arrow/optics/test/laws/TraversalLaws.kt
We're deprecating them in favour of https://github.com/kotest/kotest-extensions-arrow
=> Deprecate arrow test modules

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/domain.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/dsl.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/isos.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/lenses.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/optional.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/prism.kt
Fixes #2761
- Determines the visibility modifier based on Companion object visibility modifier (internal or public otherwise)
- Prefixed all the generated optics with determined visibility modifier
This fix prefixes optics with `internal` modifier if companion object is `internal`. Otherwise optics are prefixed with `public` modifier.
=> [2761] Add explicit visibility modifier for all the generated optics

arrow-site/docs/_data/doc-versions.yml, arrow-site/docs/_includes/_sidebar-doc-versions.html, arrow-site/docs/_sass/components/docs/_sidebar-menu.scss
The current Arrow version selector is not fully up-to-date. It's showing old versions for which there are no longer documentation and pointing out version `1.0.1` as the latest stable version.
This pull request proposes a few changes:
- Remove the old versions
- Update the latest stable version to `1.1.x`
- Remove the previous version item, which is a bit confusing
This is a screenshot of how the Arrow version selector would look like after applying these changes:
=> Refine the Arrow version selector

.github/workflows/pull_request.yml, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt
=> deprecate orNull Either extension function

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/OpticsProcessor.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/domain.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/dsl.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/isos.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/lenses.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/optional.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/prism.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/processor.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/IsoTests.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/LensTests.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/OptionalTests.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/PrismTests.kt
Fices #2718 and #2552
The optics generated for classes with generics are (inline) functions instead of `val`s, due to the way companion objects work in Kotlin (only one instance per class, not per generic instantiation).
Most of the code is straightforward, except for prisms. The hard part there is that if you have:
```kotlin
@optics
sealed class PrismSealed<A,B>(val field: A, val nullable: B?) {
data class PrismSealed1(private val a: String?) : PrismSealed<String, String>("", a)
data class PrismSealed2<C>(private val b: C?) : PrismSealed<String, C>("", b)
companion object
}
```
you need to take the type parameters **of the subclass** into account.
=> Support generics and inner classes in `@optics`

arrow-libs/optics/arrow-optics/api/arrow-optics.api, arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Copy.kt
This brings a small DSL which looks pretty much like Kotlin's built-in `copy`, but uses optics under the hood.
```kotlin
val p = Person("Alejandro", Address("Ergens", "Utrecht", "NL"))
val p2 = p.copy {
Person.name transform { it.uppercase() }
Person.address.street set "Nergens"
inside(Person.address) {
Address.city set "Madrid"
Address.country set "ES"
}
}
```
=> Generalized copy for optics

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/continuations/Effect.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/continuations/EffectSpec.kt
In #2783 we replaced `startCoroutineUninterceptedOrReturn` to `createCoroutineUnintercepted` + `resume(Unit)` but this [creates an additional `Continuation` state-machine](https://github.com/JetBrains/kotlin/blob/85800b4f9f078859b3919d34e2108bfba32ebf4c/libraries/stdlib/jvm/src/kotlin/coroutines/intrinsics/IntrinsicsJvm.kt#L186) nested inside the existing state-machine and thus causing a lot of overhead. This overhead is occurring potentially on every `fold`, so not ideal.
While investigating if the issue of `startCoroutineUninterceptedOrReturn` was in our code, or in the compiler I discovered that it was indeed a mistake in our code.
The problem happens in following sequencing where we run the `Effect<R, A>`.
```kotlin
suspendCoroutineUninterceptedOrReturn { cont ->
val token = Token() …
```
=> Fix usage of startCoroutineUninterceptedOrReturn

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/continuations/Effect.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/continuations/EffectSpec.kt
In exploration of Effect for Arrow 2.0 I discovered that we can flatten the `Token`, `Continuation` and `EffectScope` types into a single type, and thus reduce `fold` from 3 allocations to 1.
This improvement is back-portable to `1.1.x` in a binary compatible way.
It increases the public API binary of `internal Fold` a bit but entirety of `Effect` will be binary breaking in 2.0 anyway.
=> Backport flattening token/shift into Cont

arrow-libs/optics/arrow-optics/api/arrow-optics.api, arrow-libs/optics/arrow-optics/build.gradle.kts, arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Copy.kt
This should help type inference and show nicer in the IDE
=> Enable builder inference for optics `copy`

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Iterable.kt
related to #2812
A single pass is now made over the original `Iterable` instead of 2. I am not sure if using mutable lists and a single pair would offer any significant advantages but I am open to changing it if that is considered better.
I ran the tests introduced in #2814 at my local setup and they seem to pass.
=> Refactor - #2812 iterable separate performance

arrow-libs/fx/arrow-fx-coroutines/api/arrow-fx-coroutines.api, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/CircuitBreaker.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/CircuitBreakerTest.kt
Fixes #2743 
* Changes internal usage of `Double` to `Duration`.
* No changes made to public factory methods (`CircuitBreaker::of`). Questionable to accept a `Duration`, convert it to `Double` and then covert it back to a `Duration` again to pass to the internal constructor. Would appreciate some guidance here on how to manage the `@ExperimentalTime` annotation here.
=> [2743] Migrate internal use of CircuitBreaker double to duration

arrow-libs/core/arrow-core-retrofit/src/test/kotlin/arrow/retrofit/adapter/either/networkhandling/NetworkEitherCallAdapterTest.kt
In the `NetworkEitherCallAdapterTest`, it turns out on some host OS/JVM combinations a more general exception (SocketException) is thrown when the server disconnects.
Original problem report: https://kotlinlang.slack.com/archives/C5UPMM0A0/p1663048397387609
As the SocketException is parent of ConnectException, it should be enough to make the test a bit more general. Anyway the main point of the test is that the error is wrapped into a `Left<IoError>`.
=> Make the server disconnect test more general

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/NonEmptyList.kt
Suggest .toOption() instead of Option.fromNullable(). Coming from a discussion in StackOverFlow here https://stackoverflow.com/a/73893138/9440211. Thought I'd contribute it myself since it seemed quite straightforward and Simon seemed positive to this change.
Feel free to edit or discuss if you want me to edit something else too.
=> Update NonEmptyList.fromList deprecation to suggest `toOption()` instead

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/continuations/Fold.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/continuations/EagerEffectSpec.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/continuations/EffectSpec.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/continuations/StructuredConcurrencySpec.kt, arrow-libs/fx/arrow-fx-coroutines-test/src/jvmTest/kotlin/arrow/fx/coroutines/PredefTest.kt
@franciscodr review feedback on #2827.
There were some lingering _shift_ references in the code, and default lambda argument names.
For consistency, and easier understanding the internals, we want to remove all references to `shift` and only have the new `raise` name remain.
=> Remove all references to shift from new Arrow 2.0 code

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Iterable.kt
This fixes the `getOrHandle()` doc - there was incorrect information that the function somehow returns `Right`, whereas it always unwraps the value.
=> Improve Either.getOrHandle() docs

arrow-site/docs/docs/lens/README.md
Corrects the value of `Lens<Address, Street>` from `addressStrees` to `addressStreet` as probably intended, in the optics documentation.
=> Correct `addressStrees` -> `addressStreet` in optics documentation

arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Platform.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Race3.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Resource.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/builders.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/predef.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/BracketCaseTest.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/ParTraverseTest.kt
Arrow Fx exposes a couple APIs that are unnecessary low-level, and don't really have a use in mainstream code.
All operators in Arrow Fx properly compose errors under the hood, and thus there should never be a need to use these APIs.
Historically we've had this need because there was no MPP solution for composing errors in Kotlin, but since then they've added it to the Kotlin Std. So the recommendation is to use that instead.
I've added `ReplaceWith` deprecations in case anyone was relying on these APIs, and this should help them transition to the Kotlin Std API.
This PR also deprecates `never` which overlaps with KotlinX `awaitCancellation` which is also much more descriptive and better understood. And `suspend fun unit()` which was the old equivalent of `IO.unit` but is not useful in …
=> Arrow Fx: deprecate Platform#composeError, never and unit()

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/processor.kt
Should fix the error from #2725.
Backported from https://github.com/arrow-kt/arrow/commit/62044120c483b01304819900a5e4cd8b4f1e8ece
=> Backport Optics KSP plugin NPE on multiplatform fix

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Sequence.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/SequenceKTest.kt
related to #2812 similar to #2815 and #2814
=> Refactor - #2812 sequence separate performance

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/NonEmptyList.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/NonEmptyListTest.kt
Fixes https://github.com/arrow-kt/arrow/issues/2807 by removing the overrides of `equals` and `hashCode` in `NonEmptyList`, so that we use the implementations in `AbstractList`.
One thing to note is that Kotest's `shouldBe` doesn't use the `equals` function for `Iterable`, so I've tested the result of `==` explicitly (and left a comment to that effect).
(This is my first PR here 👋 so let me know if I've missed anything)
=> Use `super` equals and hashCode overrides for NonEmptyList

.github/workflows/pull_request.yml, arrow-libs/fx/arrow-fx-coroutines/api/arrow-fx-coroutines.api, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Resource.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/continuations/resource.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resource-01.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resource-02.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resource-03.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resource-04.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resource-05.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resource-06.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resource-07.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resource-08.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resource-09.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resource-10.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resource-11.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resource-13.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/examples/example-resource-14.kt
Propose the deprecate almost the entirety of the Resource API, as discussed in the [2.x.x PR](https://github.com/arrow-kt/arrow/pull/2786).
- zip: composing resource using resource { f(bind(), bind()) } supports arity-n
- parZip: can be inherited from Arrow Fx Coroutines methods, and naturally compose inside the DSL.
For `Either` we've decided to keep these methods, should we keep them for `Resource` as well?
- map/tap/flatMap: this methods can be replaced entirely by the DSL, should we keep
```kotlin
resA.flatMap {
resB
}
resource {
resA.bind()
resB.bind()
}
resA.map(f)
resource { f(resA.bind()) }
resA.tap(f)
resource { resA.bind().also(f) }
```
=> Resource API deprecation, and preparation for 2.x.x. & back port improvements

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/NonEmptyList.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/NonEmptyListTest.kt
- introduce iterable.toNonEmptyListOrNone() (fixes #2842)
=> introduce iterable.toNonEmptyListOrNone()

.github/workflows/generate-alpha-tag.yaml, .github/workflows/generate-tag.yaml, .github/workflows/publish.yml, .github/workflows/pull_request.yml
This removes the minor versions from the workflow files, which according to the [documentation](https://github.com/actions/toolkit/blob/main/docs/action-versioning.md) means the Actions use the latest minor in that major series.
=> Use major versions in GitHub Actions

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/OpticsProcessor.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/Compilation.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/DSLTests.kt
Fixes #2803
The problem is that we were re-using the name of the file. However, if you also define extension functions, or any other tp-level element, two classes with the same JVM name are generated. The solution is to create a weirder name so it doesn't conflict, I chose to add `__Optics` to the current name.
=> Do not reuse the name of the file in Optics KSP

arrow-libs/fx/arrow-fx-coroutines/api/arrow-fx-coroutines.api, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/CountDownLatch.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/CyclicBarrier.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/CyclicBarrierSpec.kt
Similar to CountDownLatch added in #2854 this PR introduces [CyclicBarrier ](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CyclicBarrier.html).
Originally written [here](https://github.com/nomisRev/arrow-fx-coroutines-utils/blob/main/src/commonMain/kotlin/io/github/nomisrev/CyclicBarrier.kt), but I removed the interface to simplify the code a bit.
The goal for 2.x.x of Arrow Fx Coroutines is to offer a _core_ module of concurrent data types, and operations in Kotlin.
=> Add CyclicBarrier

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/typeclasses/Monoid.kt
Re-adds an older method for binary compatible reasons. The new method is source compatible.
=> Fix Monad.either binary combat

.github/workflows/publish.yml, build.gradle.kts, gradle.properties
=> Publish Arrow 2.0.0-SNAPSHOT

arrow-libs/optics/arrow-optics/api/arrow-optics.api, arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/Prism.kt, arrow-libs/optics/arrow-optics/src/commonMain/kotlin/arrow/optics/dsl/either.kt
=> Prisms for Either

.github/workflows/pull_request.yml, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/continuations/Effect.kt
@serras in [2874](https://github.com/arrow-kt/arrow/pull/2874/files#diff-a0fe23534b616d51ce686d2a1bcd1a78bc75074aef1a2f6ee96c9469991e1a4c) you removed `check` and split into `jvmTest` and `jsTest`.
Was this because you were experiencing flakiness on CI again? This has resulted in a couple of false negatives on main since only `check` guarantees that all tasks to verify the project are ran.
=> Fix knitCheck & re-add check

arrow-site/docs/_data/menu.yml, arrow-site/docs/_includes/_nav.html
@franciscodr could you review this PR please? Thanks buddy ;)
- _We need to update the training link on the arrow site to go to our fp in kotlin course on the academy site, not just our home page
=> Updated training link main menu 

arrow-libs/fx/arrow-fx-resilience/src/commonMain/kotlin/arrow/fx/resilience/Schedule.kt, arrow-libs/fx/arrow-fx-resilience/src/commonTest/kotlin/arrow/fx/resilience/ScheduleTest.kt
Fixes #2846
It seems that this was a semantic problem. Here's the diff between the previous and the proposed version:
```diff kotlin
public fun untilOutput(f: suspend (Output) -> Boolean): Schedule<Input, Output> =
-    !whileOutput(f)
+    whileOutput { !f(it) }
```
The former version applies `whileOutput(f)` and then negates, which applies to the *entire* `Schedule`. However, this is not right if you have several conditions, the right thing to do is to negate *only* the given `f`.
=> Fix semantics of `untilOutput` and `untilInput`

.github/workflows/publish-landing-page.yaml
This pull request updates the GitHub Actions workflow that builds the landing page to use `macos-latest` runner instead of `ubuntu-latest` becuase homebrew has been removed from $PATH on Ubuntu images.
=> Use of macos-latest runner for building the landing page

arrow-libs/fx/arrow-fx-resilience/api/arrow-fx-resilience.api, arrow-libs/fx/arrow-fx-resilience/src/commonMain/kotlin/arrow/fx/resilience/Schedule.kt, arrow-libs/fx/arrow-fx-resilience/src/commonMain/kotlin/arrow/fx/resilience/flow.kt, arrow-libs/fx/arrow-fx-resilience/src/commonTest/kotlin/arrow/fx/resilience/ScheduleTest.kt
Fixes #2744 
I've only made the changes in the `arrow-fx-resilience` module, but they could be copied to `arrow-fx-coroutines` if desired.
=> Use Duration in Schedule

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/NonEmptySet.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/NonEmptySetTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/test/Generators.kt
This is a super basic implementation for #2565. After review, if this is fine, I can add any other functionality may be required.
=> Implement basic NonEmptySet

arrow-libs/core/arrow-annotations/build.gradle.kts, arrow-libs/core/arrow-atomic/build.gradle.kts, arrow-libs/core/arrow-continuations/build.gradle.kts, arrow-libs/core/arrow-core-retrofit/build.gradle.kts, arrow-libs/core/arrow-core/build.gradle.kts, arrow-libs/fx/arrow-fx-coroutines/build.gradle.kts, arrow-libs/fx/arrow-fx-resilience/build.gradle.kts, arrow-libs/fx/arrow-fx-stm/build.gradle.kts, arrow-libs/optics/arrow-optics-ksp-plugin/build.gradle.kts, arrow-libs/optics/arrow-optics-reflect/build.gradle.kts, arrow-libs/optics/arrow-optics/build.gradle.kts, arrow-libs/stack/build.gradle.kts, arrow-site/build.gradle.kts, build.gradle.kts
This PR is mostly for those developing Arrow within IntelliJ. If you open any build file, you get quite some errors, which can be easily suppressed. This PR does exactly so.
In addition, calls to `forUseAtConfigurationTime` are removed. This method is [deprecated](https://docs.gradle.org/current/userguide/upgrading_version_7.html), and should just be dropped.
With this, one can open the project in IntelliJ without spurious errors.
=> Fix annoying warnings in IntelliJ

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Raise.kt
Supersedes #2880, targeting `main` instead of `arrow-2`.
This PR adds *both* `zipOrAccumulate` and `mapOrAccumulate` to `Raise`, since the latter was not available in the 1.x branch.
=> `zipOrAccumulate` for `Raise`

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Raise.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/RaiseAccumulate.kt
This PR applies the suggestions by @nomisRev in #2919, which I merged too quickly 😅
=> Apply suggestions for `zipOrAccumulate`

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Const.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Eval.kt
In 2.x.x we want to remove `Const` & `Eval`.
This PR adds the deprecations for those data types into 1.x.x series.
=> Deprecate Const & Eval towards 2.x.x

.github/workflows/pull_request.yml, gradle/libs.versions.toml
The list of [supported targets](https://kotlinlang.org/docs/native-target-support.html) has been updated, some new ones have been added, and some others are marked as deprecation. Since they won't be removed until 1.9.20, nothing has been removed.
This PR complements https://github.com/arrow-kt/arrow-gradle-config/pull/65 and updated our GitHub actions to test in all available platforms. Note that we are limited by [GitHub runner specs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), which only has x86_64 hosts.
=> Update Kotlin/Native targets

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/build.gradle.kts, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Builders.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Effect.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/ErrorHandlers.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Fold.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Mappers.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Raise.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/EagerEffectSpec.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/EffectSpec.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/IorSpec.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/MappersSpec.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/NullableSpec.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/OptionSpec.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/ResultSpec.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/StructuredConcurrencySpec.kt, arrow-libs/core/arrow-core/src/jsMain/kotlin/arrow/core/raise/CancellationExceptionNoTrace.kt, arrow-libs/core/arrow-core/src/jvmMain/kotlin/arrow/core/raise/CancellationExceptionNoTrace.kt, arrow-libs/core/arrow-core/src/nativeMain/kotlin/arrow/core/raise/CancellationExceptionNoTrace.kt
- In #2884 we added `ShiftLeakedException` to improve the debug experience, this PR applies it to https://github.com/arrow-kt/arrow/pull/2912.
- In #2869 we removed stack traces to improve performance of `shift`, this PR applies it to https://github.com/arrow-kt/arrow/pull/2912.
- Aligns `result` behavior from `arrow.core.continuations` where unexpected `Throwable` is also mapped to `Result.failure`.
=> [Backport] MPP No Trace & Improve debugging experience of leaked raise calls

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-34.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-35.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-36.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-37.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-38.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-39.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-40.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-41.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-42.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-43.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-44.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-45.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-46.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-47.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-48.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-49.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-50.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-51.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-52.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-53.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-54.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-55.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-56.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-57.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-58.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-59.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/test/EitherKnitTest.kt
In an interesting https://github.com/arrow-kt/arrow/pull/2913#discussion_r1097879312 between myself, @myuwono and @franciscodr in [Option API deprecation](https://github.com/arrow-kt/arrow/pull/2913) we came up with a set of new operators to replace `exists` in a new meaningful API that we thought was very Kotlin idiomatic.
This PR adds the relevant APIs for `Either`.
=> Introduce isLeft & isRight predicate API for Either

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/domain.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/processor.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/utils.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/DSLTests.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/IsoTests.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/LensTests.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/OptionalTests.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/PrismTests.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/Utils.kt
Kotlin keyword sanitization added to class path fields used during Lens code generation. 
Only keywords matching potential TLDs are observed.
=> Keyword sanitization for Lens code generation (#2924)

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt
=> Fix filterOrElse to handle null values correctly.

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Option.kt
Fixes #2936 reported by @Zordid for both `Either` and `Option`.
=> Fix Either.isLeft, Either.isRight & Option.isSome contract

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Raise.kt
Found that all bind() funs in Raise.kt where missing the corresponding DslMarker annotation. They did not get colored in IntelliJ and that is extremely visible when combining resource scopes and effect scopes.
=> Add DSL markers to all bind funs in Raise

build.gradle.kts
Tried to set it up `arrow-fx-coroutines/build.gradle.kts` but couldn't get that to work.
Tested locally, and now types like `CoroutineScope` automatically get linked to the official API docs of KotlinX Coroutines.
=> Link KotlinX Coroutines to Arrow Fx Coroutines docs

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Option.kt
I propose to deprecate `or`, `orElse` since they overlap with `recover` and `Either` doesn't have this API.
Similarly I propose to deprecate `unzip` since I find it a rather obscure API that is unmatched in `Either`, or does this API make sense for `Option` but not for `Either`?
Additionally, in https://github.com/arrow-kt/arrow/pull/2935/files#r1117382480 I also proposed to deprecate `combine` for removal which overlaps with `option { combine(a.bind(), b.bind()) }`.
=> Option: deprecate or, orElse and unzip

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt
Fixes #2938 by introducing a deprecated new `exist` fun for `Either`, just to allow migration coming from `Validated` which had this method instead of the `exists` in `Option` and `Either`.
=> Add exist fun to Either, for migration from Validated

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Option.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Builders.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Effect.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/ErrorHandlers.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Fold.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Mappers.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Raise.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/MappersSpec.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-01.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-03.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-05.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-06.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-07.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-08.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-09.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/test/RaiseKnitTest.kt
Draft changes related to #2948 to facilitate the discussion. Also closes #2953 
cc\\ @freynder
The lambda `Raise<R>.() -> A` allows to _bind_, or _unwrap_, `Option` and in the case `None` is encountered it will invoke the lambda. The lambda allows to _raise_ a value of `R` into the outer `interface Raise<R>`, or _fallback_ to a value of _A_.
1. The `Raise<R>` lambda receiver is redundant because we're already inside the context of `interface Raise<R>`, so even without the lambda receiver we can call `raise(r)`.
2. Without `Raise<R>`, we have `() -> A` which matches the already existing `Option` API of `getOrElse`.
3. Since this function is defined inside of an `interface`, it cannot be `inline` so it's inferior to the already existing `getOrElse` which is _inline_ and thus allows for …
=> Simplify recover, and catch APIs. Add getOrElse

arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/ParMap.kt
One of the 4 signatures in `parMap` has param name `ctx` instead of `context`. This PR fixes the inconsistency.
This code is not released yet, so there is no source compatibility issues.
=> Fix ctx inconsistency

.github/workflows/generate-alpha-tag.yaml, .github/workflows/generate-tag.yaml, .github/workflows/githubpages.yaml, .github/workflows/publish.yml, .github/workflows/pull_request.yml
We're regularly seeing Gradle timeout due to https://github.com/gradle/gradle/issues/19446, and it's been released in Gradle 7.6. Now we can leverage the _internal_ Gradle flag to bump the timeout, and hopefully get rid of this flakiness on CI.
=> Bump org.gradle.kotlin.dsl.internal.io.timeout on CI to 2 minutes

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt
This PR fixes some of the deprecation `ReplaceWith` suggestions for `Either` listed in https://github.com/arrow-kt/arrow/issues/2964. I'll update the issue table once this is merged.
=> Fix `Either` deprecation replacement expressions

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Validated.kt
Due to the deprecation of `Validated` and `ValidatedNel` it seems reasonable to symmetrically also deprecate the functions `Either.toValidated()` and `Either.toValidatedNel()`.
This way, users see that they should avoid creating `Validated` objects.
Symmetrically, `Validated.fromEither(...)` had already been deprecated before.
=> Deprecate Either.toValidated() and Either.toValidatedNel() functions

arrow-libs/core/arrow-core-retrofit/src/test/kotlin/arrow/retrofit/adapter/either/networkhandling/NetworkEitherCallAdapterTest.kt
This is a part of changes related to https://github.com/arrow-kt/arrow/issues/2908 issue.
Current PR raised to fix next long running tests connected with [retrofit](https://github.com/square/retrofit) http client:
```
should return IOError when no responsearrow.retrofit.adapter.either.networkhandling.NetworkEitherCallAdapterTestSuite:arrow-core-retrofit:test | PASSED | 10.889s
(2) should return IOError when no responsearrow.retrofit.adapter.either.networkhandling.NetworkEitherCallAdapterTestSuite:arrow-core-retrofit:test | PASSED | 10.041s
(1) should return IOError when no responsearrow.retrofit.adapter.either.networkhandling.NetworkEitherCallAdapterTestSuite:arrow-core-retrofit:test | PASSED | 9.448s
```
After changes I see next timings on my local machine:
```
should return IOError when …
```
=> Speed up retrofit related long running tests (arrow-kt#2908)

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/map.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/MapKTest.kt
This pull request fixes a bug in the `zip` and `flatMap` implementation for `Map` caused by the nested nullable problem. For example, given the following code:
```
val mapA: Map<Int, String> = mapOf(1 to "a", 2 to "b", 3 to "c")
val mapB: Map<Int, String?> = mapOf(1 to "d", 2 to null, 3 to "f")
mapA.zip(mapB) { _, a, b -> Pair(a, b) }
```
It should return:
```
{1=(a, d), 2=(b, null), 3=(c, f)}
```
However, the current `zip` implementation was filtering out the key with a `null` value:
```
{1=(a, d), 3=(c, f)}
```
=> Fix nested nullable problem for map zip and flatMap implementations

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/NonEmptyList.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/CircuitBreaker.kt
This pull request deprecates NonEmptyList.traverse methods in favor of the `Raise` DSL + `map`.
We might want to add the `padZip` function
```
public inline fun <A, B, C> NonEmptyList<A>.padZip(other: NonEmptyList<B>, left: (A) -> C, right: (B) -> C, both: (A, B) -> C): NonEmptyList<C>
```
But it could be implemented based on the [proposed implementation](https://github.com/arrow-kt/arrow/pull/2963/files#diff-47d18db48a86e0ca0b3da1ea9d184df8534c1dccfaf4736121e9ccaf6bf7f4cdR686) for `Iterable.kt`
=> Deprecate NonEmptyList.kt traverse & niche APIs

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Builders.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Raise.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/RaiseAccumulate.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/NonEmptyListTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/test/Platform.kt
This pull request adds the `bindAll` function to `NonEmptyList` for both `Raise` and `RaiseAccumulate` implementations. Additionally, it adds missing unit tests for the NonEmptyList API.
=> NonEmptyList: Add bindAll and more unit tests

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Option.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/EitherTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/OptionTest.kt
@nomisRev realized that our current implementations of `traverse` do not respect the expected laws. Let's compare with Haskell (where `Just` is the equivalent of `Some`, and `[x]` means `listOf(x)`).
```haskell
> mapM (\x -> Just 3) (Left 2)
Just (Left 2)
> mapM (\x -> [3]) (Left 2)
[Left 2]
```
However, our current implementation would return `None` and an empty list in those cases. This PR implements the law-abiding implementations, which return `Left` wrapped in the corresponding type instead of the "error path" of those.
One important question here is whether we should consider this a bug, and thus just release the modifier implementation as part of 1.2.0, or whether this is a breaking change, and thus we should wait until 2.0 and release this fixed implementation under a different …
=> Fix `traverse` for `Either` and `Option`

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Iterable.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/IterableTest.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-iterable-20.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/test/IterableKnitTest.kt
=> Add partitionMap to Iterable (#3001)

.gitignore, arrow-site/docs/CNAME, build.gradle.kts, static/CNAME
After deploying the documentation files in the GitHub Pages branch, we are facing the same issue as in the arrow-website repo. The previous documentation is deleted every time a new release is published, so we lose the custom domain configuration (the CNAME file is removed). That means we need to set up the domain again, causing some downtime for the API docs site. 
To avoid that, this pull request copies the CNAME into the Dokka output folder every time we run the Dokka command.
=> Add CNAME file to Dokka output

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/DeclarationUtils.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/OpticsProcessor.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/processor.kt
This fixes incorrect behavior with the newly added "data object".
=> Ensure optics type with "data" modifier is a class

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/processor.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/utils.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/DSLTests.kt
Added support for generic variance to optics that solves #3057
=> optics ksp plugin: fixed handling of variance (#3057)

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/NonEmptySet.kt
This pull request is related to the issue https://github.com/arrow-kt/arrow/issues/3041 reported by @mikeat in mid-April.
After publishing version `1.1.6-alpha.74`, Arrow started to break any Kapt task when using Raise/Effect with the following error:
```
ExampleImpl.java:12: error: cannot access Raise
public final kotlin.jvm.functions.Function2<arrow.core.raise.Raise<? super MyError>, kotlin.coroutines.Continuation<? super java.lang.String>, java.lang.Object> example() {
^
bad class file: /Users/kaiser/.gradle/caches/modules-2/files-2.1/io.arrow-kt/arrow-core-jvm/1.2.0-RC/815591a96f11786ae0ff746a4931fee9c0e46ac4/arrow-core-jvm-1.2.0-RC.jar(/arrow/core/raise/Raise.class)
undeclared type variable: T
Please remove or make sure it appears in the correct subdirectory of the classpath.
``` …
=> Change NonEmptySet type parameter name from T to A

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/ErrorHandlers.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Raise.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/EagerEffectSpec.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/EffectSpec.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-effect-error-04.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-effect-error-05.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-raise-dsl-11.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/test/RaiseKnitTest.kt
Fixes #3053 
I'm not sure if `mapError` is the best name for it, but `withError` felt weird as an extension on `Effect`. Also, mapError's transform parameter seems too "busy" with `suspend` and `Raise`. At least the `Raise<OtherError>` could be removed, but then someone wanted to call a function inside that raises `OtherError`, they'd need to wrap in `either{ ... }.merge()` or something along those lines, and so I figured exposing the `Raise<OtherError>` might help in that case. Maybe there should be a `Raise` builder that merges the error and result automatically? This could be helpful especially if they're subclasses of each other.
@CLOVIS-AI
=> Add withError and (Eager)Effect.mapError

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/OpticsProcessor.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/OpticsProcessorOptions.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/OpticsProcessorProvider.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/isos.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/lenses.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/optional.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/prism.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/snippets.kt
=> Add option to disable `inline` when using `@optics`

arrow-libs/core/arrow-annotations/build.gradle.kts, arrow-libs/core/arrow-atomic/build.gradle.kts, arrow-libs/core/arrow-continuations/build.gradle.kts, arrow-libs/core/arrow-core/build.gradle.kts, arrow-libs/fx/arrow-fx-coroutines/build.gradle.kts, arrow-libs/fx/arrow-fx-stm/build.gradle.kts, arrow-libs/optics/arrow-optics/build.gradle.kts, arrow-libs/resilience/arrow-resilience/build.gradle.kts
According to [this blog post](https://michaelbfullan.com/the-state-of-the-jpms-in-2022/), by adding `Automatic-Module-Name` to the JAR we're one step forward in supporting Java Modules, as requested in #2800.
@durganmcbroom could you help us figuring out whether this is a step in the right direction? Does including this remove the need to "monkey-patching" the module system in Java 9+?
=> Enable Automatic Modules for JVM

arrow-libs/core/arrow-core-serialization/api/arrow-core-serialization.api, arrow-libs/core/arrow-core-serialization/build.gradle.kts, arrow-libs/core/arrow-core-serialization/src/commonMain/kotlin/arrow/core/serialization/EitherSerializer.kt, arrow-libs/core/arrow-core-serialization/src/commonMain/kotlin/arrow/core/serialization/IorSerializer.kt, arrow-libs/core/arrow-core-serialization/src/commonMain/kotlin/arrow/core/serialization/NonEmptyCollectionSerializers.kt, arrow-libs/core/arrow-core-serialization/src/commonMain/kotlin/arrow/core/serialization/OptionSerializer.kt, arrow-libs/core/arrow-core-serialization/src/commonMain/kotlin/arrow/core/serialization/ValidatedSerializer.kt, arrow-libs/core/arrow-core-serialization/src/commonTest/kotlin/arrow/core/serialization/BackAgainTest.kt, arrow-libs/core/arrow-core-serialization/src/commonTest/kotlin/arrow/core/serialization/Generators.kt, build.gradle.kts, gradle.properties, gradle/libs.versions.toml, settings.gradle.kts
Fixes #1829 
This defines the serializers to be used in the simplest way possible, which is "bringing them in" for `@Serializable` annotations by writing this at the top of the file (it can get smaller if fewer types are used).
```kotlin
@file:UseSerializers(
EitherSerializer::class,
IorSerializer::class,
ValidatedSerializer::class,
OptionSerializer::class,
NonEmptyListSerializer::class,
NonEmptySetSerializer::class
)
```
=> Serialization module

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Builders.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Fold.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Mappers.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Raise.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/RaiseAccumulate.kt
=> Add missing docs for `Raise` operations

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/RaiseAccumulate.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/RaiseAccumulateSpec.kt
This PR fixes #3063.
cc\\ @Zordid thanks for the bug report, and reproducible repo 🙏
=> Add mapOrAccumulate extension in RaiseAccumulate

arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/CopyTest.kt, arrow-libs/optics/arrow-optics/src/commonTest/kotlin/arrow/optics/CopyTest.kt
Based on [this discussion in Slack](https://kotlinlang.slack.com/archives/C5UPMM0A0/p1688822411819599)
The goal is to merge this to check that `@optics` keeps working as intended in 1.9.0
=> Additional tests for `copy` in Optics

gradle/libs.versions.toml
This should add `linuxArm64` to the mix
=> Update `arrow-gradle-config` to 0.12-rc.4

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Option.kt
I assume, the deprecation message for `Option.tap` should be `tap is being renamed to onSome` instead of `tap is being renamed to onNone`.
=> Fix Option.tap deprecation message.

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/NonEmptySet.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/NonEmptySetTest.kt
This PR backports the fix in commit 0f966b5ffa3977ffe6e8c7f3addc511dad7f6e9f, which is already OK in the current compiler.
=> Backport fix for K2

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Builders.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/NullableSpec.kt
Alternative to #3099, from [this Slack thread](https://kotlinlang.slack.com/archives/C5UPMM0A0/p1689601177846049)
This adds a new `ignoreErrors` function in `nullable` and `option` which "swallows" every error. This is needed because `withError` is a bit cumbersome, and it doesn't always type as nicely.
=> ignoreErrors for Raise

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-46.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-47.kt
Reported by @Zordid this PR removes the outdated references to `shift` in `Either.kt`. I checked all other references to shift, and could only find any in deprecated packages so this PR should remove all old references to `shift` in new packages.
=> Remove references to shift in Either.kt

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/NonEmptyList.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/NonEmptySet.kt
Fixes #3116 
This overrides `map` and `mapIndexed` with `inline` definitions, so they can be used in combination with `suspend` computations. Unfortunately this cannot be provided in general within `NonEmptyCollection`, because `inline` members are not allowed in interfaces.
=> Inline `NonEmpty` maps

.github/workflows/publish.yml, build.gradle.kts
enableCompatibilityMetadataVariant  is going to be removed in Kotlin 1.9.20. https://kotlinlang.org/docs/multiplatform-compatibility-guide.html#deprecated-gradle-properties-for-hierarchical-structure-support
Blocking Arrow 1.2.1 release
=> Remove enableCompatibilityMetadataVariant

.github/workflows/pull_request.yml, arrow-libs/core/arrow-atomic/build.gradle.kts, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Validated.kt, build.gradle.kts, settings.gradle.kts
We've been asked to become part of a large set of repositories which are tested with new versions of Kotlin. To become part of the program, we need to handle a few Gradle variables that set the Kotlin compiler and language version.
=> Prepare for Kotlin community build

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/TupleTest.kt
Hi 👋
Thank you for providing this beginner friendly story (https://github.com/arrow-kt/arrow/issues/2894). It was very helpful to get started with the first contribution.
I saw that Tuples 10-22 will be removed in Arrow2.0, I wasn't sure if you still wanted some test coverage for earlier versions. I have commited these tests in a seperate (atomic) commit so that it can be easily cherry-picked or removed. Let me know what you prefer and if it is of any value :)
=> Add Tuples test coverage

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Builders.kt
> Issue: #3138
Intuitively, I always expected `nullable` to accept `raise(Any?)` and swallow the error, simply returning `null`. The discussion in the linked issue brought `ignoreErrors` to my attention, which corresponds to my use-case.
To help future users discover it as well, I added a "See also" section to `nullable`'s API documentation.
=> Mention ignoreErrors in nullable's documentation

arrow-libs/core/arrow-atomic/src/nativeMain/kotlin/arrow/atomic/Atomic.kt, arrow-libs/core/arrow-atomic/src/nativeMain/kotlin/arrow/atomic/AtomicInt.kt, arrow-libs/core/arrow-atomic/src/nativeMain/kotlin/arrow/atomic/AtomicLong.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/RaceNJvmTest.kt
Kotlin Native 1.9 introduced a new [`kotlin.concurrent`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.concurrent/) module that replaces `kotlin.native.concurrent`. The deprecation period is small, and in 2.0 the `kotlin.native.concurrent` versions are already gone. Since we're already building with 1.9.10, changing feels safe.
This PR is needed to keep checking that we work OK with newer `dev` versions of Kotlin.
=> Use new Atomic types from Kotlin 1.9

arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/FlowJvmTest.kt
=> refactor: migrate FlowJvmTest to Kotlin-test

arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/ParZip9JvmTest.kt
=> Refactor ParZip9JvmTest from Kotest Plugin to Kotlin-test runtime

arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/ParZip8JvmTest.kt
=> Refactor ParZip8JvmTest from Kotest Plugin to Kotlin-test runtime

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/extensions/NumberInstancesTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/test/Laws.kt
=> refactor: migrate NumberInstancesTest to kotlin-test

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/OptionTest.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/test/Laws.kt
Closes #3174
Not sure about my implementation of `testLawsCommon` - but I couldn't find any way to dynamically generate tests using only kotlin-test: there is `@TestFactory` for JUnit5 dynamic tests but for simple kotlin-test, a simple `@Test` was the only way I could find.
(If you prefer an alternative approach, let me know and I'll change it accordingly.)
In order to run tests in JS mode, I also updated `yarn.lock` via `./gradlew kotlinUpgradeYarnLock`.
=> Refactor OptionTest to kotlin-test

arrow-libs/core/arrow-atomic/api/arrow-atomic.api, arrow-libs/core/arrow-atomic/src/commonMain/kotlin/arrow/atomic/AtomicBoolean.kt
Reverts arrow-kt/arrow#3240
Since this is failing in K2, let's maybe revert this one
=> Revert "Inline `AtomicBoolean`"

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/IorSpec.kt
=> refactor: migrate IorSpec to kotlin-test

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/ResultSpec.kt
=> refactor: migrate ResultSpec to kotlin-test

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/StructuredConcurrencySpec.kt
=> refactor: migrate StructuredConcurrencySpec to kotlin-test

arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/TraceSpec.kt
=> refactor: migrate TraceSpec to kotlin-test

arrow-libs/optics/arrow-optics-reflect/src/main/kotlin/arrow/optics/Reflection.kt
This PR does the setup work for finding the copy method of the data class and finding the relevant parameter only once, hence failing earlier if used not on a data class
This idea is based on a [video](https://www.youtube.com/watch?v=hTLUELJDaec) by @dmcg.
=> chore(KProperty1.lens): Perform check for data class only once.

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/dsl.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/utils.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/DSLTests.kt
=> Correctly escape class names in Optics KSP when a property clashes with a package name

.github/workflows/pull_request.yml, settings.gradle.kts
I think we should stop tracking the `-dev` versions of 2.0, and just use the beta's, since this is what our users are ultimately going to see
=> Run K2 using 2.0.0-Beta2

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Fold.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/EffectSpec.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/NullableSpec.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/StructuredConcurrencySpec.kt
This should be accompanied with a text in the Arrow docs.
It would be great to also detect `Deferred` or `Flow` from `kotlinx.coroutines`, but this doesn't seem like a good enough reason to add a dependency on those.
=> Safeguard for leaked 'raise' or 'bind'

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Iterable.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/NonEmptyList.kt
From what I can tell the other unzip methods have no equivalent in the stdlib.
NonEmptyList is of course covered by the Iterable#unzip, but still has a use-case because of returning a pair of NonEmptyLists rather than a pair of regular Lists.
This is Iterable#unzip in kotlin 1.9.22:
```kt
public fun <T, R> Iterable<Pair<T, R>>.unzip(): Pair<List<T>, List<R>> {
val expectedSize = collectionSizeOrDefault(10)
val listT = ArrayList<T>(expectedSize)
val listR = ArrayList<R>(expectedSize)
for (pair in this) {
listT.add(pair.first)
listR.add(pair.second)
}
return listT to listR
}
```
=> Deprecate Iterable#unzip in favor of stdlib method

arrow-libs/resilience/arrow-resilience/api/arrow-resilience.api, arrow-libs/resilience/arrow-resilience/src/commonMain/kotlin/arrow/resilience/Schedule.kt, arrow-libs/resilience/arrow-resilience/src/commonTest/kotlin/arrow/resilience/ScheduleTest.kt
Hey, with the latest API, it is easy to write Either version of the retry function. I think it could be quite useful. 
I based the implementation on 
`public suspend fun <A> Schedule<Throwable, *>.retry(action: suspend () -> A): A`
=> added retryRaise and retryEither functions

.github/workflows/pull_request.yml
According to [this blog post](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/) this can have a huge impact in our build times
=> Use macOS 14 runner

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/info.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/processor.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/LensTests.kt
=> Ignore properties in sealed hierarchies where the type changes across children

arrow-libs/core/arrow-autoclose/src/commonMain/kotlin/arrow/AutoCloseScope.kt, arrow-libs/core/arrow-autoclose/src/commonTest/kotlin/arrow/AutoCloseTest.kt
=> fix(autoclose): close `Closeable`s in reversed order

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/fx/arrow-fx-stm/api/arrow-fx-stm.api, arrow-libs/fx/arrow-fx-stm/src/commonMain/kotlin/arrow/fx/stm/STM.kt, arrow-libs/fx/arrow-fx-stm/src/commonMain/kotlin/arrow/fx/stm/internal/Hamt.kt, arrow-libs/fx/arrow-fx-stm/src/commonMain/kotlin/arrow/fx/stm/internal/Impl.kt, arrow-libs/fx/arrow-fx-stm/src/jvmMain/kotlin/arrow/fx/stm/internal/RetryException.kt
I was doing a bit of ABI cleanup, and I figured out a way to remove some duplication in the STM code, and increase the type safety (we no longer hold `Array<Any?>` but `Array<A>` in the HAMT tree).
=> Improvements to STM + do not expose internal members

arrow-libs/core/arrow-core-serialization/api/arrow-core-serialization.api, arrow-libs/core/arrow-core-serialization/src/commonMain/kotlin/arrow/core/serialization/OptionSerializer.kt, arrow-libs/core/arrow-core-serialization/src/commonMain/kotlin/arrow/core/serialization/SerializersModule.kt, arrow-libs/core/arrow-core-serialization/src/commonTest/kotlin/arrow/core/serialization/BackAgainTest.kt, arrow-libs/core/arrow-core-serialization/src/commonTest/kotlin/arrow/core/serialization/ModuleTest.kt
As discussed on [Slack](https://slack-chats.kotlinlang.org/t/18767362/hi-everyone-wave-new-to-kotlin-coming-from-scala-i-m-explori#aa329e2e-1cc5-4ef7-a2a4-49274213b577), this PR adds in an `ArrowModule` to simplify including the arrow serializers in a `SerializersModule {}` definition.
I've also lifted the restriction from `OptionSerializer` as discussed in that thread, but can roll this back if desired.
=> add arrow-core-serialization SerializersModule

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Builders.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/IorSpec.kt
Used to combine errors into the IorRaise state and trigger a Both output in a more convenient way. Previously the only mechanism to do this was to call `bind()` on an `Ior.Both`.
=> Add accumulate function to IorRaise

arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Resource.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/ResourceTest.kt
The test here is the same one added in #3387
=> Fix finalizer order for resourceScope to match autoCloseScope

arrow-libs/fx/arrow-fx-coroutines/api/arrow-fx-coroutines.api, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Resource.kt
Not sure if we're doing PRs on main or arrow-2 now
=> Modify onRelease to not require `suspend`

arrow-libs/optics/arrow-optics-compose/api/android/arrow-optics-compose.api, arrow-libs/optics/arrow-optics-compose/api/jvm/arrow-optics-compose.api, arrow-libs/optics/arrow-optics-compose/src/commonMain/kotlin/arrow/optics/Copy.kt, arrow-libs/optics/arrow-optics-compose/src/commonMain/kotlin/arrow/optics/Flow.kt, arrow-libs/optics/arrow-optics-compose/src/commonMain/kotlin/arrow/optics/State.kt
=> De-duplicate class names in `arrow-optics` and `arrow-optics-compose`

arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/DSLTests.kt
Fixes #3441 
The current `main` doesn't have this problem, because we use a different technique to generate prisms. This test checks not only prism, but also lens generation.
=> Add test for #3441

arrow-libs/core/arrow-annotations/build.gradle.kts, arrow-libs/core/arrow-atomic/build.gradle.kts, arrow-libs/core/arrow-autoclose/build.gradle.kts, arrow-libs/core/arrow-cache4k/build.gradle.kts, arrow-libs/core/arrow-core-high-arity/build.gradle.kts, arrow-libs/core/arrow-core-retrofit/build.gradle.kts, arrow-libs/core/arrow-core-serialization/build.gradle.kts, arrow-libs/core/arrow-core/build.gradle.kts, arrow-libs/core/arrow-eval/build.gradle.kts, arrow-libs/core/arrow-functions/build.gradle.kts, arrow-libs/fx/arrow-collectors/build.gradle.kts, arrow-libs/fx/arrow-fx-coroutines/build.gradle.kts, arrow-libs/fx/arrow-fx-stm/build.gradle.kts, arrow-libs/optics/arrow-optics-compose/build.gradle.kts, arrow-libs/optics/arrow-optics-ksp-plugin/build.gradle.kts, arrow-libs/optics/arrow-optics-reflect/build.gradle.kts, arrow-libs/optics/arrow-optics/build.gradle.kts, arrow-libs/resilience/arrow-resilience/build.gradle.kts, build.gradle.kts
The way we set the versions is no longer compatible with the new versions of Kotlin. And arguably, we should have always done it by setting it in the `kotlin.compilerOptions` block, instead of in each separate task.
(This was caught by early tests as part of the Kotlin User Projects run by the Kotlin Q&A team)
=> Fix incompatible versioning

settings.gradle.kts
Hopefully the final PR to make things work again in the Kotlin User Projects of the Kotlin team. It seems we had too many `2.0` hardcoded in our build files...
=> Remove optional build of `optics-compose`

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt
`Either.combine`'s method description contains an error. It states:
> "... otherwise it returns the `this` or fallbacks to [other] in case `this` is [Left]"
But the opposite is true: it returns this if this is Left and other if other is Left.
=> Fix KDoc of Either's combine method

arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/api/arrow-core.klib.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Option.kt
=> Make `raise` available in `Option.catch`

arrow-libs/core/arrow-core-high-arity/src/commonMain/kotlin/arrow/core/raise/RaiseAccumulate.kt, arrow-libs/core/arrow-core/api/arrow-core.api, arrow-libs/core/arrow-core/api/arrow-core.klib.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/RaiseAccumulate.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/raise/RaiseAccumulateSpec.kt, arrow-libs/fx/arrow-fx-coroutines/api/arrow-fx-coroutines.api, arrow-libs/fx/arrow-fx-coroutines/api/arrow-fx-coroutines.klib.api, arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/await/AwaitAllScope.kt
Since we are not 100% sure of the API, I thought it would be useful to mark those experimental for one or two releases.
=> Flag new 2.0 APIs as experimental

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/OpticsProcessorOptions.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/dsl.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/snippets.kt
Fixes #3500
It seems that the only thing we get from all the `inline` is a bunch of warnings, so it's better to switch it off by default. It's still possible to generate `inline` getters and setter by enabling the corresponding flag.
This PR also fixes the handling of the processor options, which were not completely acknowledged before. In particular, some methods would generate `inline` functions regardless of the options.
=> Switch off inlining in optics by default

README.md
Removes the old warning that discourage from using Arrow 2.0
=> Remove old Arrow 2.0 warning

arrow-libs/core/arrow-cache4k/build.gradle.kts, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/MapKTest.kt, arrow-libs/core/arrow-platform/api/arrow-platform.api, arrow-libs/core/arrow-platform/api/arrow-platform.klib.api, arrow-libs/core/arrow-platform/build.gradle.kts, arrow-libs/core/arrow-platform/src/commonMain/kotlin/arrow/platform/test/Flaky.kt, arrow-libs/core/arrow-platform/src/jsMain/kotlin/arrow/platform/test/Flaky.kt, arrow-libs/core/arrow-platform/src/jvmMain/kotlin/arrow/platform/test/Flaky.kt, arrow-libs/core/arrow-platform/src/nativeMain/kotlin/arrow/platform/test/Flaky.kt, arrow-libs/core/arrow-platform/src/wasmJsMain/kotlin/arrow/platform/test/Flaky.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/ParMapTest.kt, arrow-libs/fx/arrow-fx-coroutines/src/jvmTest/kotlin/arrow/fx/coroutines/RaceNJvmTest.kt, arrow-libs/optics/arrow-optics-compose/build.gradle.kts, gradle/libs.versions.toml
Fixes #3523
Fixes #3520
Fixes #3519
Fixes #3471 
This PR introduces a few annotations in the somehow-internal `arrow-platform` package which allows setting a test as disabled in only one platform. This should alleviate our current problems with flaky test.
=> Do not run flaky tests on corresponding platforms

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/OpticsProcessor.kt, arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/LensTests.kt
This addresses an issue introduced here: https://github.com/arrow-kt/arrow/pull/3537#issuecomment-2573056265
Essentially, at the moment, processing for any candidate class for optics is "deferred" when "validation" fails - essentially when any type in the class definition is not resolved. Unfortunately, this causes issues when these types are dependent on the lenses-to-be-generated themselves, such as in the following example:
```kotlin
@optics
data class UsingLens(val field: String) {
fun getLens() = UsingLens.field // Return type of the function is dependent on the lens
companion object
}
```
While this class obviously has unresolved types, these do not impact code generation of optics. Ideally, we should limit the validation to only check the validity of the types involved in the …
=> Add finer-grained validation for determining the symbols to defer during symbol processing

arrow-libs/integrations/arrow-core-jackson/api/arrow-core-jackson.api, arrow-libs/integrations/arrow-core-jackson/src/main/kotlin/arrow/integrations/jackson/module/ArrowModule.kt, arrow-libs/integrations/arrow-core-jackson/src/main/kotlin/arrow/integrations/jackson/module/NonEmptyCollections.kt, arrow-libs/integrations/arrow-core-jackson/src/test/kotlin/arrow/integrations/jackson/module/NonEmptyListModuleTest.kt, arrow-libs/integrations/arrow-core-jackson/src/test/kotlin/arrow/integrations/jackson/module/NonEmptySetModuleTest.kt
This adds serializers for non-empty collections for the Jackson integration module.
Note than nested fields still fail because of the [Kotlin compiler bug](https://youtrack.jetbrains.com/issue/KT-52706/Bad-signature-for-generic-value-classes-with-substituted-type-parameter) which also affects #3557.
=> Non-empty collections for Jackson

arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/OpticsProcessorOptions.kt, buildSrc/src/main/kotlin/arrow.kotlin.gradle.kts
This PR fixes some problems which may arise with empty Gradle properties, and correctly sets up Animal Sniffer for Java 1.8 and Android compatibility.
As a result of the incompatibilities found by Animal Sniffer, the minimal Android SDK version has been bumped to 24.
=> Further improvements for Kotlin Compatibility Testing

.github/workflows/publish.yml
This pull request updates the secrets necessary for signing and publishing the Arrow artifacts in Maven. This change will enable Arrow maintainers to release new versions in Maven.
=> Update secrets to sign and publish Arrow artifacts

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/map.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/MapKTest.kt
Fixes #3591
The existing test covers monoid laws but does not verify delegation to the nested monoid's `combine` function, which is why the bug went unnoticed.
This PR provides a property-based test that verifies the property of order-preservation when `Map.combine()` delegates. The test fails with the existing implementation. The PR also includes a fix that makes it pass.
I'm happy to refine the PR to better align with the project's style and conventions.
=> Test and fix for Map.combine()

arrow-libs/integrations/arrow-resilience-ktor-client/api/android/arrow-resilience-ktor-client.api, arrow-libs/integrations/arrow-resilience-ktor-client/api/arrow-resilience-ktor-client.klib.api, arrow-libs/integrations/arrow-resilience-ktor-client/api/jvm/arrow-resilience-ktor-client.api, arrow-libs/integrations/arrow-resilience-ktor-client/build.gradle.kts, arrow-libs/integrations/arrow-resilience-ktor-client/src/commonMain/kotlin/arrow/resilience/ktor/client/HttpRequestSchedule.kt, arrow-libs/integrations/arrow-resilience-ktor-client/src/jvmTest/kotlin/arrow/resilience/ktor/client/HttpRequestScheduleTest.kt, gradle/libs.versions.toml
This PR does two things:
- Moves the implementation of `HttpRequestSchedule` to the [newer API](https://ktor.io/docs/client-custom-plugins.html) based on `on`. The implementation now follows more closely what is done for `HttpRetry`.
- Updates the tests to actually simulate a failing network request. Before the tests relied on the fact that the exception from the host was propagated with `testApplication`, but now `MockEngine` directly simulates a failing connection.
=> Make implementation of `HttpRequestSchedule` closer to `HttpRetry`

arrow-libs/core/arrow-eval/api/android/arrow-eval.api, arrow-libs/core/arrow-eval/api/arrow-eval.klib.api, arrow-libs/core/arrow-eval/api/jvm/arrow-eval.api, arrow-libs/core/arrow-eval/src/commonMain/kotlin/arrow/eval/Eval.kt, arrow-libs/core/arrow-eval/src/commonMain/kotlin/arrow/eval/SuspendEval.kt, arrow-libs/core/arrow-eval/src/commonTest/kotlin/arrow/eval/SuspendEvalTest.kt
Coming from [this Slack thread](https://kotlinlang.slack.com/archives/C5UPMM0A0/p1741261169119059)
This brings a version of `Eval` which wraps `suspend` functions. The approach is very similar to the one in `arrow-collectors`, in which `SuspendEval` becomes a supertype of `Eval`. This allows freely mixing `SuspendEval` with `Eval` to get a `SuspendEval`, or use just `Eval` to keep `Eval`s.
=> `Eval` for `suspend` functions

arrow-libs/integrations/arrow-core-jackson/api/arrow-core-jackson.api, arrow-libs/integrations/arrow-core-jackson/src/main/kotlin/arrow/integrations/jackson/module/OptionModule.kt, arrow-libs/integrations/arrow-core-jackson/src/test/kotlin/arrow/integrations/jackson/module/DataHelpers.kt, arrow-libs/integrations/arrow-core-jackson/src/test/kotlin/arrow/integrations/jackson/module/EitherModuleTest.kt, arrow-libs/integrations/arrow-core-jackson/src/test/kotlin/arrow/integrations/jackson/module/IorModuleTest.kt, arrow-libs/integrations/arrow-core-jackson/src/test/kotlin/arrow/integrations/jackson/module/NonEmptyListModuleTest.kt, arrow-libs/integrations/arrow-core-jackson/src/test/kotlin/arrow/integrations/jackson/module/OptionModuleTest.kt, arrow-libs/integrations/arrow-core-jackson/src/test/kotlin/arrow/integrations/jackson/module/TestHelper.kt
This moves `OptionDeserializer` in line with the rest of the implementations; and seems to be much more resilient than before.
Fixes https://github.com/arrow-kt/arrow-integrations/issues/131
=> Rewrite `OptionDeserializer` for Jackson

arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/map.kt
I based this implementation on `getOrElseNullable`, which is an internal method in the stdlib. As you can see, it only calls `containsKey` if the value is null, which makes it slightly faster for non-nullable values, and the same speed-ish for nullable ones (conjecture, but clearly it doesn't recalculate hashcode for non-nullable values, which is good, and the only extra instruction for nullable values is just the null check. Realistically, the null check is irrelevant compared to the object allocation, but the hashcode recalculation definitely isn't, since it can be expensive depending on the data structure).
=> (minor): Slightly Optimize Map.getOrNone

arrow-libs/fx/arrow-fx-coroutines/src/commonMain/kotlin/arrow/fx/coroutines/Resource.kt, arrow-libs/fx/arrow-fx-coroutines/src/commonTest/kotlin/arrow/fx/coroutines/ResourceTest.kt
Also showcase this by updating a test to call `Resource.bind` inside `install`
I discussed this with @nomisRev a while ago. We're rather sure that `AcquireStep` preventing installation inside `install` is completely unnecessary.
=> Unmark AcquireStep to allow installing resources inside `install`

arrow-libs/core/arrow-core-high-arity/src/commonMain/kotlin/arrow/core/raise/RaiseAccumulate.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Fold.kt, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/raise/Raise.kt
Fixes #3678
This seems to work just fine and stay source-compatible, but allows invoking to work normally for inline functions
=> Unmark Effect.invoke as operator

arrow-libs/version-catalog/README.MD, arrow-libs/version-catalog/build.gradle.kts, arrow-libs/version-catalog/gradle.properties, settings.gradle.kts
Introduced a new module for managing version catalogs for Arrow Kotlin libraries. This includes updates to `settings.gradle.kts`, a `build.gradle.kts` configuration, and a README file with setup instructions. The catalog simplifies dependency management for various Arrow libraries.
=> Add Arrow Version Catalog module

arrow-libs/core/arrow-core/api/android/arrow-core.api, arrow-libs/core/arrow-core/api/arrow-core.klib.api, arrow-libs/core/arrow-core/api/jvm/arrow-core.api, arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt, arrow-libs/core/arrow-core/src/commonTest/kotlin/arrow/core/EitherTest.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-32.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-33.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-34.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-35.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-36.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/example-either-37.kt, arrow-libs/core/arrow-core/src/jvmTest/kotlin/examples/test/EitherKnitTest.kt
Fixes #3639
Closes #3711
This is the result of the discussion in #3711 (it was easier for me to create a new PR than to rollback all the changes there). This PR introduces a single `validate` function that runs a `Raise` block on `Right` values, but leaves them unchanged until something `raise`s. This seems quite effective in combination with `ensure` to write one-liners:
```kotlin
fun failOnMoreConditionsWithBindMap(): Either<String, Int> =
randomNumber()
.validate { ensure(it != 10) { "Number 10 also not allowed" } }
.map { it + 100 }
```
=> `validate` for `Either`
